# ┌──────────────────────────────────────────────────────────────┐
# │  resource: google_cloudfunctions_function                      │
# └──────────────────────────────────────────────────────────────┘
resource "google_cloudfunctions_function" "this" {

  name                          = ""     # string | required | A user-defined name of the function. Function names must be …
  runtime                       = ""     # string | required | The runtime in which the function is going to run. Eg. "node…
  available_memory_mb           = 0      # number | optional | Memory (in MB), available to the function. Default value is …
  build_environment_variables   = {}     # map(string) | optional |  A set of key/value environment variable pairs available dur…
  build_service_account         = ""     # string | optional+computed | The fully-qualified name of the service account to be used f…
  build_worker_pool             = ""     # string | optional | Name of the Cloud Build Custom Worker Pool that should be us…
  description                   = ""     # string | optional | Description of the function.
  docker_registry               = ""     # string | optional+computed | Docker Registry to use for storing the function's Docker ima…
  docker_repository             = ""     # string | optional | User managed repository created in Artifact Registry optiona…
  entry_point                   = ""     # string | optional | Name of the function that will be executed when the Google C…
  environment_variables         = {}     # map(string) | optional | A set of key/value environment variable pairs to assign to t…
  https_trigger_security_level  = ""     # string | optional+computed | The security level for the function. Defaults to SECURE_OPTI…
  https_trigger_url             = ""     # string | optional+computed | URL which triggers function execution. Returned only if trig…
  id                            = ""     # string | optional+computed
  ingress_settings              = ""     # string | optional | String value that controls what traffic can reach the functi…
  kms_key_name                  = ""     # string | optional | Resource name of a KMS crypto key (managed by the user) used…
  labels                        = {}     # map(string) | optional | A set of key/value label pairs to assign to the function. La…
  max_instances                 = 0      # number | optional+computed | The limit on the maximum number of function instances that m…
  min_instances                 = 0      # number | optional | The limit on the minimum number of function instances that m…
  project                       = ""     # string | optional+computed | Project of the function. If it is not provided, the provider…
  region                        = ""     # string | optional+computed | Region of function. If it is not provided, the provider regi…
  service_account_email         = ""     # string | optional+computed |  If provided, the self-provided service account to run the f…
  source_archive_bucket         = ""     # string | optional | The GCS bucket containing the zip archive which contains the…
  source_archive_object         = ""     # string | optional | The source archive object (file) in archive bucket.
  timeout                       = 0      # number | optional | Timeout (in seconds) for the function. Default value is 60 s…
  trigger_http                  = false  # bool | optional | Boolean variable. Any HTTP request (of a supported type) to …
  vpc_connector                 = ""     # string | optional | The VPC Network Connector that this cloud function can conne…
  vpc_connector_egress_settings = ""     # string | optional+computed | The egress settings for the connector, controlling what traf…

  # effective_labels              = {}     # map(string) | computed | All of labels (key/value pairs) present on the resource in G…
  # status                        = ""     # string | computed | Describes the current stage of a deployment.
  # terraform_labels              = {}     # map(string) | computed | The combination of labels configured directly on the resourc…
  # version_id                    = ""     # string | computed | The version identifier of the Cloud Function. Each deploymen…

  event_trigger { # list [0..1]
    event_type = ""     # string | required | The type of event to observe. For example: "google.storage.o…
    resource   = ""     # string | required | The name or partial URI of the resource from which to observ…

    failure_policy { # list [0..1]
      retry = false  # bool | required | Whether the function should be retried on failure. Defaults …

    }

  }

  secret_environment_variables { # list
    key        = ""     # string | required | Name of the environment variable.
    secret     = ""     # string | required | ID of the secret in secret manager (not the full resource na…
    version    = ""     # string | required | Version of the secret (version number or the string "latest"…
    project_id = ""     # string | optional+computed | Project identifier (due to a known limitation, only project …

  }

  secret_volumes { # list
    mount_path = ""     # string | required | The path within the container to mount the secret volume. Fo…
    secret     = ""     # string | required | ID of the secret in secret manager (not the full resource na…
    project_id = ""     # string | optional+computed | Project identifier (due to a known limitation, only project …

    versions { # list
      path    = ""     # string | required | Relative path of the file under the mount path where the sec…
      version = ""     # string | required | Version of the secret (version number or the string "latest"…

    }

  }

  source_repository { # list [0..1]
    url          = ""     # string | required | The URL pointing to the hosted repository where the function…

    # deployed_url = ""     # string | computed | The URL pointing to the hosted repository where the function…

  }

  timeouts { # single
    create = ""     # string | optional
    delete = ""     # string | optional
    read   = ""     # string | optional
    update = ""     # string | optional

  }

}

