# ┌──────────────────────────────────────────────────────────────┐
# │  resource: google_compute_health_check                         │
# └──────────────────────────────────────────────────────────────┘
resource "google_compute_health_check" "this" {

  name                = ""     # string | required | Name of the resource. Provided by the client when the resour…
  check_interval_sec  = 0      # number | optional | How often (in seconds) to send a health check. The default v…
  description         = ""     # string | optional | An optional description of this resource. Provide this prope…
  healthy_threshold   = 0      # number | optional | A so-far unhealthy instance will be marked healthy after thi…
  id                  = ""     # string | optional+computed
  project             = ""     # string | optional+computed
  source_regions      = []     # list(string) | optional | The list of cloud regions from which health checks are perfo…
  timeout_sec         = 0      # number | optional | How long (in seconds) to wait before claiming failure. The d…
  unhealthy_threshold = 0      # number | optional | A so-far healthy instance will be marked unhealthy after thi…

  # creation_timestamp  = ""     # string | computed | Creation timestamp in RFC3339 text format.
  # self_link           = ""     # string | computed
  # type                = ""     # string | computed | The type of the health check. One of HTTP, HTTPS, TCP, or SS…

  grpc_health_check { # list [0..1]
    grpc_service_name  = ""     # string | optional | The gRPC service name for the health check. The value of grp…
    port               = 0      # number | optional | The port number for the health check request. Must be specif…
    port_name          = ""     # string | optional | Port name as defined in InstanceGroup#NamedPort#name. If bot…
    port_specification = ""     # string | optional | Specifies how port is selected for health checking, can be o…

  }

  http2_health_check { # list [0..1]
    host               = ""     # string | optional | The value of the host header in the HTTP2 health check reque…
    port               = 0      # number | optional | The TCP port number for the HTTP2 health check request. The …
    port_name          = ""     # string | optional | Port name as defined in InstanceGroup#NamedPort#name. If bot…
    port_specification = ""     # string | optional | Specifies how port is selected for health checking, can be o…
    proxy_header       = ""     # string | optional | Specifies the type of proxy header to append before sending …
    request_path       = ""     # string | optional | The request path of the HTTP2 health check request. The defa…
    response           = ""     # string | optional | The bytes to match against the beginning of the response dat…

  }

  http_health_check { # list [0..1]
    host               = ""     # string | optional | The value of the host header in the HTTP health check reques…
    port               = 0      # number | optional | The TCP port number for the HTTP health check request. The d…
    port_name          = ""     # string | optional | Port name as defined in InstanceGroup#NamedPort#name. If bot…
    port_specification = ""     # string | optional | Specifies how port is selected for health checking, can be o…
    proxy_header       = ""     # string | optional | Specifies the type of proxy header to append before sending …
    request_path       = ""     # string | optional | The request path of the HTTP health check request. The defau…
    response           = ""     # string | optional | The bytes to match against the beginning of the response dat…

  }

  https_health_check { # list [0..1]
    host               = ""     # string | optional | The value of the host header in the HTTPS health check reque…
    port               = 0      # number | optional | The TCP port number for the HTTPS health check request. The …
    port_name          = ""     # string | optional | Port name as defined in InstanceGroup#NamedPort#name. If bot…
    port_specification = ""     # string | optional | Specifies how port is selected for health checking, can be o…
    proxy_header       = ""     # string | optional | Specifies the type of proxy header to append before sending …
    request_path       = ""     # string | optional | The request path of the HTTPS health check request. The defa…
    response           = ""     # string | optional | The bytes to match against the beginning of the response dat…

  }

  log_config { # list [0..1]
    enable = false  # bool | optional | Indicates whether or not to export logs. This is false by de…

  }

  ssl_health_check { # list [0..1]
    port               = 0      # number | optional | The TCP port number for the SSL health check request. The de…
    port_name          = ""     # string | optional | Port name as defined in InstanceGroup#NamedPort#name. If bot…
    port_specification = ""     # string | optional | Specifies how port is selected for health checking, can be o…
    proxy_header       = ""     # string | optional | Specifies the type of proxy header to append before sending …
    request            = ""     # string | optional | The application data to send once the SSL connection has bee…
    response           = ""     # string | optional | The bytes to match against the beginning of the response dat…

  }

  tcp_health_check { # list [0..1]
    port               = 0      # number | optional | The TCP port number for the TCP health check request. The de…
    port_name          = ""     # string | optional | Port name as defined in InstanceGroup#NamedPort#name. If bot…
    port_specification = ""     # string | optional | Specifies how port is selected for health checking, can be o…
    proxy_header       = ""     # string | optional | Specifies the type of proxy header to append before sending …
    request            = ""     # string | optional | The application data to send once the TCP connection has bee…
    response           = ""     # string | optional | The bytes to match against the beginning of the response dat…

  }

  timeouts { # single
    create = ""     # string | optional
    delete = ""     # string | optional
    update = ""     # string | optional

  }

}

