# ┌──────────────────────────────────────────────────────────────┐
# │  resource: aws_timestreaminfluxdb_db_instance                  │
# └──────────────────────────────────────────────────────────────┘
resource "aws_timestreaminfluxdb_db_instance" "this" {

  allocated_storage                 = 0      # number | required | The amount of storage to allocate for your DB storage type i…
  bucket                            = ""     # string | required | The name of the initial InfluxDB bucket. All InfluxDB data i…
  db_instance_type                  = ""     # string | required | The Timestream for InfluxDB DB instance type to run InfluxDB…
  name                              = ""     # string | required | The name that uniquely identifies the DB instance when inter…
  organization                      = ""     # string | required | The name of the initial organization for the initial admin u…
  password                          = ""     # string | required+sensitive | The password of the initial admin user created in InfluxDB. …
  username                          = ""     # string | required | The username of the initial admin user created in InfluxDB. …
  vpc_security_group_ids            = []     # set(string) | required | A list of VPC security group IDs to associate with the DB in…
  vpc_subnet_ids                    = []     # set(string) | required | A list of VPC subnet IDs to associate with the DB instance. …
  db_parameter_group_identifier     = ""     # string | optional | The id of the DB parameter group assigned to your DB instanc…
  db_storage_type                   = ""     # string | optional+computed | The Timestream for InfluxDB DB storage type to read and writ…
  deployment_type                   = ""     # string | optional+computed | Specifies whether the DB instance will be deployed as a stan…
  network_type                      = ""     # string | optional+computed | Specifies whether the networkType of the Timestream for Infl…
  port                              = 0      # number | optional+computed | The port number on which InfluxDB accepts connections.
  publicly_accessible               = false  # bool | optional+computed | Configures the DB instance with a public IP to facilitate ac…
  tags                              = {}     # map(string) | optional

  # arn                               = ""     # string | computed
  # availability_zone                 = ""     # string | computed | The Availability Zone in which the DB instance resides.
  # endpoint                          = ""     # string | computed | The endpoint used to connect to InfluxDB. The default Influx…
  # id                                = ""     # string | computed
  # influx_auth_parameters_secret_arn = ""     # string | computed | The Amazon Resource Name (ARN) of the AWS Secrets Manager se…
  # secondary_availability_zone       = ""     # string | computed | The Availability Zone in which the standby instance is locat…
  # tags_all                          = {}     # map(string) | computed

  log_delivery_configuration { # list

    s3_configuration { # list
      bucket_name = ""     # string | required | The name of the S3 bucket to deliver logs to.
      enabled     = false  # bool | required | Indicates whether log delivery to the S3 bucket is enabled.

    }

  }

  timeouts { # single
    create = ""     # string | optional | A string that can be [parsed as a duration](https://pkg.go.d…
    delete = ""     # string | optional | A string that can be [parsed as a duration](https://pkg.go.d…
    update = ""     # string | optional | A string that can be [parsed as a duration](https://pkg.go.d…

  }

}

