# ┌──────────────────────────────────────────────────────────────┐
# │  resource: aws_neptunegraph_graph                              │
# └──────────────────────────────────────────────────────────────┘
resource "aws_neptunegraph_graph" "this" {

  provisioned_memory  = 0      # number | required | The provisioned memory-optimized Neptune Capacity Units (m-N…
  deletion_protection = false  # bool | optional+computed | A value that indicates whether the graph has deletion protec…
  graph_name          = ""     # string | optional+computed | The graph name. For example: my-graph-1. 								The name mu…
  graph_name_prefix   = ""     # string | optional | Allows user to specify name prefix and have remainder of nam…
  kms_key_identifier  = ""     # string | optional+computed | Specifies a KMS key to use to encrypt data in the new graph.…
  public_connectivity = false  # bool | optional+computed | Specifies whether or not the graph can be reachable over the…
  replica_count       = 0      # number | optional+computed | The number of replicas in other AZs.  Value must be between …
  tags                = {}     # map(string) | optional

  # arn                 = ""     # string | computed
  # endpoint            = ""     # string | computed
  # id                  = ""     # string | computed
  # tags_all            = {}     # map(string) | computed

  timeouts { # single
    create = ""     # string | optional | A string that can be [parsed as a duration](https://pkg.go.d…
    delete = ""     # string | optional | A string that can be [parsed as a duration](https://pkg.go.d…
    update = ""     # string | optional | A string that can be [parsed as a duration](https://pkg.go.d…

  }

  vector_search_configuration { # list
    vector_search_dimension = 0      # number | optional | Specifies the number of dimensions for vector embeddings.  V…

  }

}

