# ┌──────────────────────────────────────────────────────────────┐
# │  data: google_project                                          │
# └──────────────────────────────────────────────────────────────┘
data "google_project" "this" {

  id                  = ""     # string | optional+computed
  project_id          = ""     # string | optional | The project ID. Changing this forces a new project to be cre…

  # auto_create_network = false  # bool | computed | Create the 'default' network automatically.  Default true. I…
  # billing_account     = ""     # string | computed | The alphanumeric ID of the billing account this project belo…
  # deletion_policy     = ""     # string | computed | The deletion policy for the Project. Setting PREVENT will pr…
  # effective_labels    = {}     # map(string) | computed | All of labels (key/value pairs) present on the resource in G…
  # folder_id           = ""     # string | computed | The numeric ID of the folder this project should be created …
  # labels              = {}     # map(string) | computed | A set of key/value label pairs to assign to the project. 			…
  # name                = ""     # string | computed | The display name of the project.
  # number              = ""     # string | computed | The numeric identifier of the project.
  # org_id              = ""     # string | computed | The numeric ID of the organization this project belongs to. …
  # skip_delete         = false  # bool | computed | If true, the Terraform resource can be deleted without delet…
  # terraform_labels    = {}     # map(string) | computed | (ReadOnly) The combination of labels configured directly on …

}

