# ┌──────────────────────────────────────────────────────────────┐
# │  resource: google_data_pipeline_pipeline                       │
# └──────────────────────────────────────────────────────────────┘
resource "google_data_pipeline_pipeline" "this" {

  name                            = ""     # string | required | "The pipeline name. For example': 'projects/PROJECT_ID/locat…
  state                           = ""     # string | required | The state of the pipeline. When the pipeline is created, the…
  type                            = ""     # string | required | The type of the pipeline. This field affects the scheduling …
  display_name                    = ""     # string | optional | The display name of the pipeline. It can contain only letter…
  id                              = ""     # string | optional+computed
  pipeline_sources                = {}     # map(string) | optional | The sources of the pipeline (for example, Dataplex). The key…
  project                         = ""     # string | optional+computed
  region                          = ""     # string | optional | A reference to the region
  scheduler_service_account_email = ""     # string | optional+computed | Optional. A service account email to be used with the Cloud …

  # create_time                     = ""     # string | computed | The timestamp when the pipeline was initially created. Set b…
  # job_count                       = 0      # number | computed | Number of jobs.
  # last_update_time                = ""     # string | computed | The timestamp when the pipeline was last modified. Set by th…

  schedule_info { # list [0..1]
    schedule      = ""     # string | optional | Unix-cron format of the schedule. This information is retrie…
    time_zone     = ""     # string | optional | Timezone ID. This matches the timezone IDs used by the Cloud…

    # next_job_time = ""     # string | computed | When the next Scheduler job is going to run. A timestamp in …

  }

  timeouts { # single
    create = ""     # string | optional
    delete = ""     # string | optional
    update = ""     # string | optional

  }

  workload { # list [0..1]

    dataflow_flex_template_request { # list [0..1]
      location      = ""     # string | required | The regional endpoint to which to direct the request. For ex…
      project_id    = ""     # string | required | The ID of the Cloud Platform project that the job belongs to…
      validate_only = false  # bool | optional | If true, the request is validated but not actually executed.…

      launch_parameter { # list [1..1]
        job_name                = ""     # string | required | The job name to use for the created job. For an update job r…
        container_spec_gcs_path = ""     # string | optional | Cloud Storage path to a file with a JSON-serialized Containe…
        launch_options          = {}     # map(string) | optional | Launch options for this Flex Template job. This is a common …
        parameters              = {}     # map(string) | optional | 'The parameters for the Flex Template. Example: {"numWorkers…
        transform_name_mappings = {}     # map(string) | optional | 'Use this to pass transform name mappings for streaming upda…
        update                  = false  # bool | optional | Set this to true if you are sending a request to update a ru…

        environment { # list [0..1]
          additional_experiments  = []     # list(string) | optional | Additional experiment flags for the job.
          additional_user_labels  = {}     # map(string) | optional | Additional user labels to be specified for the job. Keys and…
          enable_streaming_engine = false  # bool | optional | Whether to enable Streaming Engine for the job.
          flexrs_goal             = ""     # string | optional | Set FlexRS goal for the job. https://cloud.google.com/datafl…
          ip_configuration        = ""     # string | optional | Configuration for VM IPs. https://cloud.google.com/dataflow/…
          kms_key_name            = ""     # string | optional | 'Name for the Cloud KMS key for the job. The key format is: …
          machine_type            = ""     # string | optional | The machine type to use for the job. Defaults to the value f…
          max_workers             = 0      # number | optional | The maximum number of Compute Engine instances to be made av…
          network                 = ""     # string | optional | Network to which VMs will be assigned. If empty or unspecifi…
          num_workers             = 0      # number | optional | The initial number of Compute Engine instances for the job.
          service_account_email   = ""     # string | optional | The email address of the service account to run the job as.
          subnetwork              = ""     # string | optional | Subnetwork to which VMs will be assigned, if desired. You ca…
          temp_location           = ""     # string | optional | The Cloud Storage path to use for temporary files. Must be a…
          worker_region           = ""     # string | optional | The Compute Engine region (https://cloud.google.com/compute/…
          worker_zone             = ""     # string | optional | The Compute Engine zone (https://cloud.google.com/compute/do…
          zone                    = ""     # string | optional | The Compute Engine availability zone for launching worker in…

        }

      }

    }

    dataflow_launch_template_request { # list [0..1]
      project_id    = ""     # string | required | The ID of the Cloud Platform project that the job belongs to…
      gcs_path      = ""     # string | optional | A Cloud Storage path to the template from which to create th…
      location      = ""     # string | optional | The regional endpoint to which to direct the request.
      validate_only = false  # bool | optional

      launch_parameters { # list [0..1]
        job_name               = ""     # string | required | The job name to use for the created job.
        parameters             = {}     # map(string) | optional | The runtime parameters to pass to the job. 'An object contai…
        transform_name_mapping = {}     # map(string) | optional | Map of transform name prefixes of the job to be replaced to …
        update                 = false  # bool | optional | If set, replace the existing pipeline with the name specifie…

        environment { # list [0..1]
          additional_experiments     = []     # list(string) | optional | Additional experiment flags for the job.
          additional_user_labels     = {}     # map(string) | optional | Additional user labels to be specified for the job. Keys and…
          bypass_temp_dir_validation = false  # bool | optional | Whether to bypass the safety checks for the job's temporary …
          enable_streaming_engine    = false  # bool | optional | Whether to enable Streaming Engine for the job.
          ip_configuration           = ""     # string | optional | Configuration for VM IPs. https://cloud.google.com/dataflow/…
          kms_key_name               = ""     # string | optional | 'Name for the Cloud KMS key for the job. The key format is: …
          machine_type               = ""     # string | optional | The machine type to use for the job. Defaults to the value f…
          max_workers                = 0      # number | optional | The maximum number of Compute Engine instances to be made av…
          network                    = ""     # string | optional+computed | Network to which VMs will be assigned. If empty or unspecifi…
          num_workers                = 0      # number | optional | The initial number of Compute Engine instances for the job.
          service_account_email      = ""     # string | optional | The email address of the service account to run the job as.
          subnetwork                 = ""     # string | optional | Subnetwork to which VMs will be assigned, if desired. You ca…
          temp_location              = ""     # string | optional | The Cloud Storage path to use for temporary files. Must be a…
          worker_region              = ""     # string | optional | The Compute Engine region (https://cloud.google.com/compute/…
          worker_zone                = ""     # string | optional | The Compute Engine zone (https://cloud.google.com/compute/do…
          zone                       = ""     # string | optional | The Compute Engine availability zone for launching worker in…

        }

      }

    }

  }

}

