# ┌──────────────────────────────────────────────────────────────┐
# │  resource: google_network_services_edge_cache_service          │
# └──────────────────────────────────────────────────────────────┘
resource "google_network_services_edge_cache_service" "this" {

  name                  = ""     # string | required | Name of the resource; provided by the client when the resour…
  description           = ""     # string | optional | A human-readable description of the resource.
  disable_http2         = false  # bool | optional | Disables HTTP/2.  HTTP/2 (h2) is enabled by default and reco…
  disable_quic          = false  # bool | optional+computed | HTTP/3 (IETF QUIC) and Google QUIC are enabled by default.
  edge_security_policy  = ""     # string | optional | Resource URL that points at the Cloud Armor edge security po…
  edge_ssl_certificates = []     # list(string) | optional | URLs to sslCertificate resources that are used to authentica…
  id                    = ""     # string | optional+computed
  labels                = {}     # map(string) | optional | Set of label tags associated with the EdgeCache resource.  *…
  project               = ""     # string | optional+computed
  require_tls           = false  # bool | optional+computed | Require TLS (HTTPS) for all clients connecting to this servi…
  ssl_policy            = ""     # string | optional | URL of the SslPolicy resource that will be associated with t…

  # effective_labels      = {}     # map(string) | computed | All of labels (key/value pairs) present on the resource in G…
  # ipv4_addresses        = []     # list(string) | computed | The IPv4 addresses associated with this service. Addresses a…
  # ipv6_addresses        = []     # list(string) | computed | The IPv6 addresses associated with this service. Addresses a…
  # terraform_labels      = {}     # map(string) | computed | The combination of labels configured directly on the resourc…

  log_config { # list [0..1]
    enable      = false  # bool | optional+computed | Specifies whether to enable logging for traffic served by th…
    sample_rate = 0      # number | optional | Configures the sampling rate of requests, where 1.0 means al…

  }

  routing { # list [1..1]

    host_rule { # list [1..10]
      hosts        = []     # list(string) | required | The list of host patterns to match.  Host patterns must be v…
      path_matcher = ""     # string | required | The name of the pathMatcher associated with this hostRule.
      description  = ""     # string | optional | A human-readable description of the hostRule.

    }

    path_matcher { # list [1..10]
      name        = ""     # string | required | The name to which this PathMatcher is referred by the HostRu…
      description = ""     # string | optional | A human-readable description of the resource.

      route_rule { # list [1..200]
        priority    = ""     # string | required | The priority of this route rule, where 1 is the highest prio…
        description = ""     # string | optional | A human-readable description of the routeRule.
        origin      = ""     # string | optional | The Origin resource that requests to this route should fetch…

        header_action { # list [0..1]

          request_header_to_add { # list [0..25]
            header_name  = ""     # string | required | The name of the header to add.
            header_value = ""     # string | required | The value of the header to add.
            replace      = false  # bool | optional+computed | Whether to replace all existing headers with the same name.

          }

          request_header_to_remove { # list [0..25]
            header_name = ""     # string | required | The name of the header to remove.

          }

          response_header_to_add { # list [0..25]
            header_name  = ""     # string | required | The name of the header to add.
            header_value = ""     # string | required | The value of the header to add.
            replace      = false  # bool | optional+computed | Whether to replace all existing headers with the same name.

          }

          response_header_to_remove { # list [0..25]
            header_name = ""     # string | required | Headers to remove from the response prior to sending it back…

          }

        }

        match_rule { # list [1..5]
          full_path_match     = ""     # string | optional | For satisfying the matchRule condition, the path of the requ…
          ignore_case         = false  # bool | optional+computed | Specifies that prefixMatch and fullPathMatch matches are cas…
          path_template_match = ""     # string | optional | For satisfying the matchRule condition, the path of the requ…
          prefix_match        = ""     # string | optional | For satisfying the matchRule condition, the request's path m…

          header_match { # list [0..3]
            header_name   = ""     # string | required | The header name to match on.
            exact_match   = ""     # string | optional | The value of the header should exactly match contents of exa…
            invert_match  = false  # bool | optional+computed | If set to false (default), the headerMatch is considered a m…
            prefix_match  = ""     # string | optional | The value of the header must start with the contents of pref…
            present_match = false  # bool | optional | A header with the contents of headerName must exist. The mat…
            suffix_match  = ""     # string | optional | The value of the header must end with the contents of suffix…

          }

          query_parameter_match { # list [0..5]
            name          = ""     # string | required | The name of the query parameter to match. The query paramete…
            exact_match   = ""     # string | optional | The queryParameterMatch matches if the value of the paramete…
            present_match = false  # bool | optional | Specifies that the queryParameterMatch matches if the reques…

          }

        }

        route_action { # list [0..1]

          cdn_policy { # list [0..1]
            cache_mode                            = ""     # string | optional+computed | Cache modes allow users to control the behaviour of the cach…
            client_ttl                            = ""     # string | optional | Specifies a separate client (e.g. browser client) TTL, separ…
            default_ttl                           = ""     # string | optional+computed | Specifies the default TTL for cached content served by this …
            max_ttl                               = ""     # string | optional+computed | Specifies the maximum allowed TTL for cached content served …
            negative_caching                      = false  # bool | optional | Negative caching allows per-status code TTLs to be set, in o…
            negative_caching_policy               = {}     # map(string) | optional | Sets a cache TTL for the specified HTTP status code. negativ…
            signed_request_keyset                 = ""     # string | optional+computed | The EdgeCacheKeyset containing the set of public keys used t…
            signed_request_maximum_expiration_ttl = ""     # string | optional | Limit how far into the future the expiration time of a signe…
            signed_request_mode                   = ""     # string | optional+computed | Whether to enforce signed requests. The default value is DIS…

            add_signatures { # list [0..1]
              actions               = []     # list(string) | required | The actions to take to add signatures to responses. Possible…
              copied_parameters     = []     # list(string) | optional | The parameters to copy from the verified token to the genera…
              keyset                = ""     # string | optional | The keyset to use for signature generation.  The following a…
              token_query_parameter = ""     # string | optional | The query parameter in which to put the generated token.  If…
              token_ttl             = ""     # string | optional | The duration the token is valid starting from the moment the…

            }

            cache_key_policy { # list [0..1]
              exclude_host              = false  # bool | optional+computed | If true, requests to different hosts will be cached separate…
              exclude_query_string      = false  # bool | optional | If true, exclude query string parameters from the cache key …
              excluded_query_parameters = []     # list(string) | optional | Names of query string parameters to exclude from cache keys.…
              include_protocol          = false  # bool | optional+computed | If true, http and https requests will be cached separately.
              included_cookie_names     = []     # list(string) | optional | Names of Cookies to include in cache keys.  The cookie name …
              included_header_names     = []     # list(string) | optional | Names of HTTP request headers to include in cache keys. The …
              included_query_parameters = []     # list(string) | optional | Names of query string parameters to include in cache keys. A…

            }

            signed_token_options { # list [0..1]
              allowed_signature_algorithms = []     # list(string) | optional | The allowed signature algorithms to use.  Defaults to using …
              token_query_parameter        = ""     # string | optional | The query parameter in which to find the token.  The name mu…

            }

          }

          cors_policy { # list [0..1]
            max_age           = ""     # string | required | Specifies how long results of a preflight request can be cac…
            allow_credentials = false  # bool | optional | In response to a preflight request, setting this to true ind…
            allow_headers     = []     # list(string) | optional | Specifies the content for the Access-Control-Allow-Headers r…
            allow_methods     = []     # list(string) | optional | Specifies the content for the Access-Control-Allow-Methods r…
            allow_origins     = []     # list(string) | optional | Specifies the list of origins that will be allowed to do COR…
            disabled          = false  # bool | optional | If true, specifies the CORS policy is disabled. The default …
            expose_headers    = []     # list(string) | optional | Specifies the content for the Access-Control-Allow-Headers r…

          }

          url_rewrite { # list [0..1]
            host_rewrite          = ""     # string | optional | Prior to forwarding the request to the selected origin, the …
            path_prefix_rewrite   = ""     # string | optional | Prior to forwarding the request to the selected origin, the …
            path_template_rewrite = ""     # string | optional | Prior to forwarding the request to the selected origin, if t…

          }

        }

        url_redirect { # list [0..1]
          host_redirect          = ""     # string | optional | The host that will be used in the redirect response instead …
          https_redirect         = false  # bool | optional+computed | If set to true, the URL scheme in the redirected request is …
          path_redirect          = ""     # string | optional | The path that will be used in the redirect response instead …
          prefix_redirect        = ""     # string | optional | The prefix that replaces the prefixMatch specified in the ro…
          redirect_response_code = ""     # string | optional+computed | The HTTP Status code to use for this RedirectAction.  The su…
          strip_query            = false  # bool | optional+computed | If set to true, any accompanying query portion of the origin…

        }

      }

    }

  }

  timeouts { # single
    create = ""     # string | optional
    delete = ""     # string | optional
    update = ""     # string | optional

  }

}

