# ┌──────────────────────────────────────────────────────────────┐
# │  resource: google_privateca_ca_pool                            │
# └──────────────────────────────────────────────────────────────┘
resource "google_privateca_ca_pool" "this" {

  location         = ""     # string | required | Location of the CaPool. A full list of valid locations can b…
  name             = ""     # string | required | The name for this CaPool.
  tier             = ""     # string | required | The Tier of this CaPool. Possible values: ["ENTERPRISE", "DE…
  id               = ""     # string | optional+computed
  labels           = {}     # map(string) | optional | Labels with user-defined metadata.  An object containing a l…
  project          = ""     # string | optional+computed

  # effective_labels = {}     # map(string) | computed | All of labels (key/value pairs) present on the resource in G…
  # terraform_labels = {}     # map(string) | computed | The combination of labels configured directly on the resourc…

  issuance_policy { # list [0..1]
    maximum_lifetime = ""     # string | optional | The maximum lifetime allowed for issued Certificates. Note t…

    allowed_issuance_modes { # list [0..1]
      allow_config_based_issuance = false  # bool | required | When true, allows callers to create Certificates by specifyi…
      allow_csr_based_issuance    = false  # bool | required | When true, allows callers to create Certificates by specifyi…

    }

    allowed_key_types { # list

      elliptic_curve { # list [0..1]
        signature_algorithm = ""     # string | required | The algorithm used. Possible values: ["ECDSA_P256", "ECDSA_P…

      }

      rsa { # list [0..1]
        max_modulus_size = ""     # string | optional | The maximum allowed RSA modulus size, in bits. If this is no…
        min_modulus_size = ""     # string | optional | The minimum allowed RSA modulus size, in bits. If this is no…

      }

    }

    baseline_values { # list [0..1]
      aia_ocsp_servers = []     # list(string) | optional | Describes Online Certificate Status Protocol (OCSP) endpoint…

      additional_extensions { # list
        critical = false  # bool | required | Indicates whether or not this extension is critical (i.e., i…
        value    = ""     # string | required | The value of this X.509 extension. A base64-encoded string.

        object_id { # list [1..1]
          object_id_path = []     # list(number) | required | An ObjectId specifies an object identifier (OID). These prov…

        }

      }

      ca_options { # list [1..1]
        is_ca                       = false  # bool | optional | When true, the "CA" in Basic Constraints extension will be s…
        max_issuer_path_length      = 0      # number | optional | Refers to the "path length constraint" in Basic Constraints …
        non_ca                      = false  # bool | optional | When true, the "CA" in Basic Constraints extension will be s…
        zero_max_issuer_path_length = false  # bool | optional | When true, the "path length constraint" in Basic Constraints…

      }

      key_usage { # list [1..1]

        base_key_usage { # list [1..1]
          cert_sign          = false  # bool | optional | The key may be used to sign certificates.
          content_commitment = false  # bool | optional | The key may be used for cryptographic commitments. Note that…
          crl_sign           = false  # bool | optional | The key may be used sign certificate revocation lists.
          data_encipherment  = false  # bool | optional | The key may be used to encipher data.
          decipher_only      = false  # bool | optional | The key may be used to decipher only.
          digital_signature  = false  # bool | optional | The key may be used for digital signatures.
          encipher_only      = false  # bool | optional | The key may be used to encipher only.
          key_agreement      = false  # bool | optional | The key may be used in a key agreement protocol.
          key_encipherment   = false  # bool | optional | The key may be used to encipher other keys.

        }

        extended_key_usage { # list [1..1]
          client_auth      = false  # bool | optional | Corresponds to OID 1.3.6.1.5.5.7.3.2. Officially described a…
          code_signing     = false  # bool | optional | Corresponds to OID 1.3.6.1.5.5.7.3.3. Officially described a…
          email_protection = false  # bool | optional | Corresponds to OID 1.3.6.1.5.5.7.3.4. Officially described a…
          ocsp_signing     = false  # bool | optional | Corresponds to OID 1.3.6.1.5.5.7.3.9. Officially described a…
          server_auth      = false  # bool | optional | Corresponds to OID 1.3.6.1.5.5.7.3.1. Officially described a…
          time_stamping    = false  # bool | optional | Corresponds to OID 1.3.6.1.5.5.7.3.8. Officially described a…

        }

        unknown_extended_key_usages { # list
          object_id_path = []     # list(number) | required | An ObjectId specifies an object identifier (OID). These prov…

        }

      }

      name_constraints { # list [0..1]
        critical                  = false  # bool | required | Indicates whether or not the name constraints are marked cri…
        excluded_dns_names        = []     # list(string) | optional | Contains excluded DNS names. Any DNS name that can be constr…
        excluded_email_addresses  = []     # list(string) | optional | Contains the excluded email addresses. The value can be a pa…
        excluded_ip_ranges        = []     # list(string) | optional | Contains the excluded IP ranges. For IPv4 addresses, the ran…
        excluded_uris             = []     # list(string) | optional | Contains the excluded URIs that apply to the host part of th…
        permitted_dns_names       = []     # list(string) | optional | Contains permitted DNS names. Any DNS name that can be const…
        permitted_email_addresses = []     # list(string) | optional | Contains the permitted email addresses. The value can be a p…
        permitted_ip_ranges       = []     # list(string) | optional | Contains the permitted IP ranges. For IPv4 addresses, the ra…
        permitted_uris            = []     # list(string) | optional | Contains the permitted URIs that apply to the host part of t…

      }

      policy_ids { # list
        object_id_path = []     # list(number) | required | An ObjectId specifies an object identifier (OID). These prov…

      }

    }

    identity_constraints { # list [0..1]
      allow_subject_alt_names_passthrough = false  # bool | required | If this is set, the SubjectAltNames extension may be copied …
      allow_subject_passthrough           = false  # bool | required | If this is set, the Subject field may be copied from a certi…

      cel_expression { # list [0..1]
        expression  = ""     # string | required | Textual representation of an expression in Common Expression…
        description = ""     # string | optional | Description of the expression. This is a longer text which d…
        location    = ""     # string | optional | String indicating the location of the expression for error r…
        title       = ""     # string | optional | Title for the expression, i.e. a short string describing its…

      }

    }

  }

  publishing_options { # list [0..1]
    publish_ca_cert = false  # bool | required | When true, publishes each CertificateAuthority's CA certific…
    publish_crl     = false  # bool | required | When true, publishes each CertificateAuthority's CRL and inc…
    encoding_format = ""     # string | optional | Specifies the encoding format of each CertificateAuthority's…

  }

  timeouts { # single
    create = ""     # string | optional
    delete = ""     # string | optional
    update = ""     # string | optional

  }

}

