# ┌──────────────────────────────────────────────────────────────┐
# │  resource: google_filestore_instance                           │
# └──────────────────────────────────────────────────────────────┘
resource "google_filestore_instance" "this" {

  name             = ""     # string | required | The resource name of the instance.
  tier             = ""     # string | required | The service tier of the instance. Possible values include: S…
  description      = ""     # string | optional | A description of the instance.
  id               = ""     # string | optional+computed
  kms_key_name     = ""     # string | optional | KMS key name used for data encryption.
  labels           = {}     # map(string) | optional | Resource labels to represent user-provided metadata.   **Not…
  location         = ""     # string | optional+computed | The name of the location of the instance. This can be a regi…
  project          = ""     # string | optional+computed
  zone             = ""     # string | optional+computed+DEPRECATED | The name of the Filestore zone of the instance.

  # create_time      = ""     # string | computed | Creation timestamp in RFC3339 text format.
  # effective_labels = {}     # map(string) | computed | All of labels (key/value pairs) present on the resource in G…
  # etag             = ""     # string | computed | Server-specified ETag for the instance resource to prevent s…
  # terraform_labels = {}     # map(string) | computed | The combination of labels configured directly on the resourc…

  file_shares { # list [1..1]
    capacity_gb   = 0      # number | required | File share capacity in GiB. This must be at least 1024 GiB f…
    name          = ""     # string | required | The name of the fileshare (16 characters or less)
    source_backup = ""     # string | optional | The resource name of the backup, in the format projects/{pro…

    nfs_export_options { # list [0..10]
      access_mode = ""     # string | optional | Either READ_ONLY, for allowing only read requests on the exp…
      anon_gid    = 0      # number | optional | An integer representing the anonymous group id with a defaul…
      anon_uid    = 0      # number | optional | An integer representing the anonymous user id with a default…
      ip_ranges   = []     # list(string) | optional | List of either IPv4 addresses, or ranges in CIDR notation wh…
      squash_mode = ""     # string | optional | Either NO_ROOT_SQUASH, for allowing root access on the expor…

    }

  }

  networks { # list [1..*]
    modes             = []     # list(string) | required | IP versions for which the instance has IP addresses assigned…
    network           = ""     # string | required | The name of the GCE VPC network to which the instance is con…
    connect_mode      = ""     # string | optional | The network connect mode of the Filestore instance. If not p…
    reserved_ip_range = ""     # string | optional+computed | A /29 CIDR block that identifies the range of IP addresses r…

    # ip_addresses      = []     # list(string) | computed | A list of IPv4 or IPv6 addresses.

  }

  timeouts { # single
    create = ""     # string | optional
    delete = ""     # string | optional
    update = ""     # string | optional

  }

}

