# ┌──────────────────────────────────────────────────────────────┐
# │  resource: google_dataproc_workflow_template                   │
# └──────────────────────────────────────────────────────────────┘
resource "google_dataproc_workflow_template" "this" {

  location         = ""     # string | required | The location for the resource
  name             = ""     # string | required | Output only. The resource name of the workflow template, as …
  dag_timeout      = ""     # string | optional | Optional. Timeout duration for the DAG of jobs, expressed in…
  id               = ""     # string | optional+computed
  labels           = {}     # map(string) | optional | Optional. The labels to associate with this template. These …
  project          = ""     # string | optional+computed | The project for the resource
  version          = 0      # number | optional+computed+DEPRECATED | Output only. The current version of this workflow template.

  # create_time      = ""     # string | computed | Output only. The time template was created.
  # effective_labels = {}     # map(string) | computed | All of labels (key/value pairs) present on the resource in G…
  # terraform_labels = {}     # map(string) | computed | The combination of labels configured directly on the resourc…
  # update_time      = ""     # string | computed | Output only. The time template was last updated.

  jobs { # list [1..*]
    step_id               = ""     # string | required | Required. The step id. The id must be unique among all jobs …
    labels                = {}     # map(string) | optional | Optional. The labels to associate with this job. Label keys …
    prerequisite_step_ids = []     # list(string) | optional | Optional. The optional list of prerequisite job step_ids. If…

    hadoop_job { # list [0..1]
      archive_uris      = []     # list(string) | optional | Optional. HCFS URIs of archives to be extracted in the worki…
      args              = []     # list(string) | optional | Optional. The arguments to pass to the driver. Do not includ…
      file_uris         = []     # list(string) | optional | Optional. HCFS (Hadoop Compatible Filesystem) URIs of files …
      jar_file_uris     = []     # list(string) | optional | Optional. Jar file URIs to add to the CLASSPATHs of the Hado…
      main_class        = ""     # string | optional | The name of the driver's main class. The jar file containing…
      main_jar_file_uri = ""     # string | optional | The HCFS URI of the jar file containing the main class. Exam…
      properties        = {}     # map(string) | optional | Optional. A mapping of property names to values, used to con…

      logging_config { # list [0..1]
        driver_log_levels = {}     # map(string) | optional | The per-package log levels for the driver. This may include …

      }

    }

    hive_job { # list [0..1]
      continue_on_failure = false  # bool | optional | Optional. Whether to continue executing queries if a query f…
      jar_file_uris       = []     # list(string) | optional | Optional. HCFS URIs of jar files to add to the CLASSPATH of …
      properties          = {}     # map(string) | optional | Optional. A mapping of property names and values, used to co…
      query_file_uri      = ""     # string | optional | The HCFS URI of the script that contains Hive queries.
      script_variables    = {}     # map(string) | optional | Optional. Mapping of query variable names to values (equival…

      query_list { # list [0..1]
        queries = []     # list(string) | required | Required. The queries to execute. You do not need to end a q…

      }

    }

    pig_job { # list [0..1]
      continue_on_failure = false  # bool | optional | Optional. Whether to continue executing queries if a query f…
      jar_file_uris       = []     # list(string) | optional | Optional. HCFS URIs of jar files to add to the CLASSPATH of …
      properties          = {}     # map(string) | optional | Optional. A mapping of property names to values, used to con…
      query_file_uri      = ""     # string | optional | The HCFS URI of the script that contains the Pig queries.
      script_variables    = {}     # map(string) | optional | Optional. Mapping of query variable names to values (equival…

      logging_config { # list [0..1]
        driver_log_levels = {}     # map(string) | optional | The per-package log levels for the driver. This may include …

      }

      query_list { # list [0..1]
        queries = []     # list(string) | required | Required. The queries to execute. You do not need to end a q…

      }

    }

    presto_job { # list [0..1]
      client_tags         = []     # list(string) | optional | Optional. Presto client tags to attach to this query
      continue_on_failure = false  # bool | optional | Optional. Whether to continue executing queries if a query f…
      output_format       = ""     # string | optional | Optional. The format in which query output will be displayed…
      properties          = {}     # map(string) | optional | Optional. A mapping of property names to values. Used to set…
      query_file_uri      = ""     # string | optional | The HCFS URI of the script that contains SQL queries.

      logging_config { # list [0..1]
        driver_log_levels = {}     # map(string) | optional | The per-package log levels for the driver. This may include …

      }

      query_list { # list [0..1]
        queries = []     # list(string) | required | Required. The queries to execute. You do not need to end a q…

      }

    }

    pyspark_job { # list [0..1]
      main_python_file_uri = ""     # string | required | Required. The HCFS URI of the main Python file to use as the…
      archive_uris         = []     # list(string) | optional | Optional. HCFS URIs of archives to be extracted into the wor…
      args                 = []     # list(string) | optional | Optional. The arguments to pass to the driver. Do not includ…
      file_uris            = []     # list(string) | optional | Optional. HCFS URIs of files to be placed in the working dir…
      jar_file_uris        = []     # list(string) | optional | Optional. HCFS URIs of jar files to add to the CLASSPATHs of…
      properties           = {}     # map(string) | optional | Optional. A mapping of property names to values, used to con…
      python_file_uris     = []     # list(string) | optional | Optional. HCFS file URIs of Python files to pass to the PySp…

      logging_config { # list [0..1]
        driver_log_levels = {}     # map(string) | optional | The per-package log levels for the driver. This may include …

      }

    }

    scheduling { # list [0..1]
      max_failures_per_hour = 0      # number | optional | Optional. Maximum number of times per hour a driver may be r…
      max_failures_total    = 0      # number | optional | Optional. Maximum number of times in total a driver may be r…

    }

    spark_job { # list [0..1]
      archive_uris      = []     # list(string) | optional | Optional. HCFS URIs of archives to be extracted into the wor…
      args              = []     # list(string) | optional | Optional. The arguments to pass to the driver. Do not includ…
      file_uris         = []     # list(string) | optional | Optional. HCFS URIs of files to be placed in the working dir…
      jar_file_uris     = []     # list(string) | optional | Optional. HCFS URIs of jar files to add to the CLASSPATHs of…
      main_class        = ""     # string | optional | The name of the driver's main class. The jar file that conta…
      main_jar_file_uri = ""     # string | optional | The HCFS URI of the jar file that contains the main class.
      properties        = {}     # map(string) | optional | Optional. A mapping of property names to values, used to con…

      logging_config { # list [0..1]
        driver_log_levels = {}     # map(string) | optional | The per-package log levels for the driver. This may include …

      }

    }

    spark_r_job { # list [0..1]
      main_r_file_uri = ""     # string | required | Required. The HCFS URI of the main R file to use as the driv…
      archive_uris    = []     # list(string) | optional | Optional. HCFS URIs of archives to be extracted into the wor…
      args            = []     # list(string) | optional | Optional. The arguments to pass to the driver. Do not includ…
      file_uris       = []     # list(string) | optional | Optional. HCFS URIs of files to be placed in the working dir…
      properties      = {}     # map(string) | optional | Optional. A mapping of property names to values, used to con…

      logging_config { # list [0..1]
        driver_log_levels = {}     # map(string) | optional | The per-package log levels for the driver. This may include …

      }

    }

    spark_sql_job { # list [0..1]
      jar_file_uris    = []     # list(string) | optional | Optional. HCFS URIs of jar files to be added to the Spark CL…
      properties       = {}     # map(string) | optional | Optional. A mapping of property names to values, used to con…
      query_file_uri   = ""     # string | optional | The HCFS URI of the script that contains SQL queries.
      script_variables = {}     # map(string) | optional | Optional. Mapping of query variable names to values (equival…

      logging_config { # list [0..1]
        driver_log_levels = {}     # map(string) | optional | The per-package log levels for the driver. This may include …

      }

      query_list { # list [0..1]
        queries = []     # list(string) | required | Required. The queries to execute. You do not need to end a q…

      }

    }

  }

  parameters { # list
    fields      = []     # list(string) | required | Required. Paths to all fields that the parameter replaces. A…
    name        = ""     # string | required | Required. Parameter name. The parameter name is used as the …
    description = ""     # string | optional | Optional. Brief description of the parameter. Must not excee…

    validation { # list [0..1]

      regex { # list [0..1]
        regexes = []     # list(string) | required | Required. RE2 regular expressions used to validate the param…

      }

      values { # list [0..1]
        values = []     # list(string) | required | Required. List of allowed values for the parameter.

      }

    }

  }

  placement { # list [1..1]

    cluster_selector { # list [0..1]
      cluster_labels = {}     # map(string) | required | Required. The cluster labels. Cluster must have all labels t…
      zone           = ""     # string | optional+computed | Optional. The zone where workflow process executes. This par…

    }

    managed_cluster { # list [0..1]
      cluster_name = ""     # string | required | Required. The cluster name prefix. A unique cluster name wil…
      labels       = {}     # map(string) | optional | Optional. The labels to associate with this cluster. Label k…

      config { # list [1..1]
        staging_bucket = ""     # string | optional | Optional. A Cloud Storage bucket used to stage job dependenc…
        temp_bucket    = ""     # string | optional | Optional. A Cloud Storage bucket used to store ephemeral clu…

        autoscaling_config { # list [0..1]
          policy = ""     # string | optional | Optional. The autoscaling policy used by the cluster. Only r…

        }

        encryption_config { # list [0..1]
          gce_pd_kms_key_name = ""     # string | optional | Optional. The Cloud KMS key name to use for PD disk encrypti…

        }

        endpoint_config { # list [0..1]
          enable_http_port_access = false  # bool | optional | Optional. If true, enable http access to specific ports on t…

          # http_ports              = {}     # map(string) | computed | Output only. The map of port descriptions to URLs. Will only…

        }

        gce_cluster_config { # list [0..1]
          internal_ip_only           = false  # bool | optional+computed | Optional. If true, all instances in the cluster will only ha…
          metadata                   = {}     # map(string) | optional | The Compute Engine metadata entries to add to all instances …
          network                    = ""     # string | optional | Optional. The Compute Engine network to be used for machine …
          private_ipv6_google_access = ""     # string | optional | Optional. The type of IPv6 access for a cluster. Possible va…
          service_account            = ""     # string | optional | Optional. The [Dataproc service account](https://cloud.googl…
          service_account_scopes     = []     # list(string) | optional | Optional. The URIs of service account scopes to be included …
          subnetwork                 = ""     # string | optional | Optional. The Compute Engine subnetwork to be used for machi…
          tags                       = []     # set(string) | optional | The Compute Engine tags to add to all instances (see [Taggin…
          zone                       = ""     # string | optional+computed | Optional. The zone where the Compute Engine cluster will be …

          node_group_affinity { # list [0..1]
            node_group = ""     # string | required | Required. The URI of a sole-tenant [node group resource](htt…

          }

          reservation_affinity { # list [0..1]
            consume_reservation_type = ""     # string | optional | Optional. Type of reservation to consume Possible values: TY…
            key                      = ""     # string | optional | Optional. Corresponds to the label key of reservation resour…
            values                   = []     # list(string) | optional | Optional. Corresponds to the label values of reservation res…

          }

          shielded_instance_config { # list [0..1]
            enable_integrity_monitoring = false  # bool | optional | Optional. Defines whether instances have integrity monitorin…
            enable_secure_boot          = false  # bool | optional | Optional. Defines whether the instances have Secure Boot ena…
            enable_vtpm                 = false  # bool | optional | Optional. Defines whether the instance have the vTPM enabled…

          }

        }

        initialization_actions { # list
          executable_file   = ""     # string | optional | Required. Cloud Storage URI of executable file.
          execution_timeout = ""     # string | optional | Optional. Amount of time executable has to complete. Default…

        }

        lifecycle_config { # list [0..1]
          auto_delete_time = ""     # string | optional | Optional. The time when cluster will be auto-deleted (see JS…
          auto_delete_ttl  = ""     # string | optional | Optional. The lifetime duration of cluster. The cluster will…
          idle_delete_ttl  = ""     # string | optional | Optional. The duration to keep the cluster alive while idlin…

          # idle_start_time  = ""     # string | computed | Output only. The time when cluster became idle (most recent …

        }

        master_config { # list [0..1]
          image                = ""     # string | optional | Optional. The Compute Engine image resource used for cluster…
          machine_type         = ""     # string | optional | Optional. The Compute Engine machine type used for cluster i…
          min_cpu_platform     = ""     # string | optional+computed | Optional. Specifies the minimum cpu platform for the Instanc…
          num_instances        = 0      # number | optional | Optional. The number of VM instances in the instance group. …
          preemptibility       = ""     # string | optional | Optional. Specifies the preemptibility of the instance group…

          # instance_names       = []     # list(string) | computed | Output only. The list of instance names. Dataproc derives th…
          # is_preemptible       = false  # bool | computed | Output only. Specifies that this instance group contains pre…
          # managed_group_config = [  # list(object)
          #   {
          #     instance_group_manager_name = ""
          #     instance_template_name = ""
          #   }
          # ]

          accelerators { # list
            accelerator_count = 0      # number | optional | The number of the accelerator cards of this type exposed to …
            accelerator_type  = ""     # string | optional | Full URL, partial URI, or short name of the accelerator type…

          }

          disk_config { # list [0..1]
            boot_disk_size_gb = 0      # number | optional | Optional. Size in GB of the boot disk (default is 500GB).
            boot_disk_type    = ""     # string | optional | Optional. Type of the boot disk (default is "pd-standard"). …
            num_local_ssds    = 0      # number | optional+computed | Optional. Number of attached SSDs, from 0 to 4 (default is 0…

          }

        }

        secondary_worker_config { # list [0..1]
          image                = ""     # string | optional | Optional. The Compute Engine image resource used for cluster…
          machine_type         = ""     # string | optional | Optional. The Compute Engine machine type used for cluster i…
          min_cpu_platform     = ""     # string | optional+computed | Optional. Specifies the minimum cpu platform for the Instanc…
          num_instances        = 0      # number | optional | Optional. The number of VM instances in the instance group. …
          preemptibility       = ""     # string | optional | Optional. Specifies the preemptibility of the instance group…

          # instance_names       = []     # list(string) | computed | Output only. The list of instance names. Dataproc derives th…
          # is_preemptible       = false  # bool | computed | Output only. Specifies that this instance group contains pre…
          # managed_group_config = [  # list(object)
          #   {
          #     instance_group_manager_name = ""
          #     instance_template_name = ""
          #   }
          # ]

          accelerators { # list
            accelerator_count = 0      # number | optional | The number of the accelerator cards of this type exposed to …
            accelerator_type  = ""     # string | optional | Full URL, partial URI, or short name of the accelerator type…

          }

          disk_config { # list [0..1]
            boot_disk_size_gb = 0      # number | optional | Optional. Size in GB of the boot disk (default is 500GB).
            boot_disk_type    = ""     # string | optional | Optional. Type of the boot disk (default is "pd-standard"). …
            num_local_ssds    = 0      # number | optional+computed | Optional. Number of attached SSDs, from 0 to 4 (default is 0…

          }

        }

        security_config { # list [0..1]

          kerberos_config { # list [0..1]
            cross_realm_trust_admin_server    = ""     # string | optional | Optional. The admin server (IP or hostname) for the remote t…
            cross_realm_trust_kdc             = ""     # string | optional | Optional. The KDC (IP or hostname) for the remote trusted re…
            cross_realm_trust_realm           = ""     # string | optional | Optional. The remote realm the Dataproc on-cluster KDC will …
            cross_realm_trust_shared_password = ""     # string | optional | Optional. The Cloud Storage URI of a KMS encrypted file cont…
            enable_kerberos                   = false  # bool | optional | Optional. Flag to indicate whether to Kerberize the cluster …
            kdc_db_key                        = ""     # string | optional | Optional. The Cloud Storage URI of a KMS encrypted file cont…
            key_password                      = ""     # string | optional | Optional. The Cloud Storage URI of a KMS encrypted file cont…
            keystore                          = ""     # string | optional | Optional. The Cloud Storage URI of the keystore file used fo…
            keystore_password                 = ""     # string | optional | Optional. The Cloud Storage URI of a KMS encrypted file cont…
            kms_key                           = ""     # string | optional | Optional. The uri of the KMS key used to encrypt various sen…
            realm                             = ""     # string | optional | Optional. The name of the on-cluster Kerberos realm. If not …
            root_principal_password           = ""     # string | optional | Optional. The Cloud Storage URI of a KMS encrypted file cont…
            tgt_lifetime_hours                = 0      # number | optional | Optional. The lifetime of the ticket granting ticket, in hou…
            truststore                        = ""     # string | optional | Optional. The Cloud Storage URI of the truststore file used …
            truststore_password               = ""     # string | optional | Optional. The Cloud Storage URI of a KMS encrypted file cont…

          }

        }

        software_config { # list [0..1]
          image_version       = ""     # string | optional | Optional. The version of software inside the cluster. It mus…
          optional_components = []     # list(string) | optional | Optional. The set of components to activate on the cluster.
          properties          = {}     # map(string) | optional | Optional. The properties to set on daemon config files. Prop…

        }

        worker_config { # list [0..1]
          image                = ""     # string | optional | Optional. The Compute Engine image resource used for cluster…
          machine_type         = ""     # string | optional | Optional. The Compute Engine machine type used for cluster i…
          min_cpu_platform     = ""     # string | optional+computed | Optional. Specifies the minimum cpu platform for the Instanc…
          num_instances        = 0      # number | optional | Optional. The number of VM instances in the instance group. …
          preemptibility       = ""     # string | optional | Optional. Specifies the preemptibility of the instance group…

          # instance_names       = []     # list(string) | computed | Output only. The list of instance names. Dataproc derives th…
          # is_preemptible       = false  # bool | computed | Output only. Specifies that this instance group contains pre…
          # managed_group_config = [  # list(object)
          #   {
          #     instance_group_manager_name = ""
          #     instance_template_name = ""
          #   }
          # ]

          accelerators { # list
            accelerator_count = 0      # number | optional | The number of the accelerator cards of this type exposed to …
            accelerator_type  = ""     # string | optional | Full URL, partial URI, or short name of the accelerator type…

          }

          disk_config { # list [0..1]
            boot_disk_size_gb = 0      # number | optional | Optional. Size in GB of the boot disk (default is 500GB).
            boot_disk_type    = ""     # string | optional | Optional. Type of the boot disk (default is "pd-standard"). …
            num_local_ssds    = 0      # number | optional+computed | Optional. Number of attached SSDs, from 0 to 4 (default is 0…

          }

        }

      }

    }

  }

  timeouts { # single
    create = ""     # string | optional
    delete = ""     # string | optional
    update = ""     # string | optional

  }

}

