# ┌──────────────────────────────────────────────────────────────┐
# │  resource: google_scc_management_project_security_health_analytics_custom_module  │
# └──────────────────────────────────────────────────────────────┘
resource "google_scc_management_project_security_health_analytics_custom_module" "this" {

  display_name     = ""     # string | optional | The display name of the Security Health Analytics custom mod…
  enablement_state = ""     # string | optional | The enablement state of the custom module. Possible values: …
  id               = ""     # string | optional+computed
  location         = ""     # string | optional | Location ID of the parent organization. If not provided, 'gl…
  project          = ""     # string | optional+computed

  # ancestor_module  = ""     # string | computed | If empty, indicates that the custom module was created in th…
  # last_editor      = ""     # string | computed | The editor that last updated the custom module.
  # name             = ""     # string | computed | The resource name of the custom module. Its format is "proje…
  # update_time      = ""     # string | computed | The time at which the custom module was last updated.  A tim…

  custom_config { # list [0..1]
    recommendation = ""     # string | required | An explanation of the recommended steps that security teams …
    severity       = ""     # string | required | The severity to assign to findings generated by the module. …
    description    = ""     # string | optional | Text that describes the vulnerability or misconfiguration th…

    custom_output { # list [0..1]

      properties { # list
        name = ""     # string | optional | Name of the property for the custom output.

        value_expression { # list [0..1]
          expression  = ""     # string | required | Textual representation of an expression in Common Expression…
          description = ""     # string | optional | Description of the expression. This is a longer text which d…
          location    = ""     # string | optional | String indicating the location of the expression for error r…
          title       = ""     # string | optional | Title for the expression, i.e. a short string describing its…

        }

      }

    }

    predicate { # list [1..1]
      expression  = ""     # string | required | Textual representation of an expression in Common Expression…
      description = ""     # string | optional | Description of the expression. This is a longer text which d…
      location    = ""     # string | optional | String indicating the location of the expression for error r…
      title       = ""     # string | optional | Title for the expression, i.e. a short string describing its…

    }

    resource_selector { # list [1..1]
      resource_types = []     # list(string) | required | The resource types to run the detector on.

    }

  }

  timeouts { # single
    create = ""     # string | optional
    delete = ""     # string | optional
    update = ""     # string | optional

  }

}

