# ┌──────────────────────────────────────────────────────────────┐
# │  resource: google_app_engine_standard_app_version              │
# └──────────────────────────────────────────────────────────────┘
resource "google_app_engine_standard_app_version" "this" {

  runtime                   = ""     # string | required | Desired runtime. Example python27.
  service                   = ""     # string | required | AppEngine service resource
  app_engine_apis           = false  # bool | optional | Allows App Engine second generation runtimes to access the l…
  delete_service_on_destroy = false  # bool | optional | If set to 'true', the service will be deleted if it is the l…
  env_variables             = {}     # map(string) | optional | Environment variables available to the application.
  id                        = ""     # string | optional+computed
  inbound_services          = []     # set(string) | optional | A list of the types of messages that this application is abl…
  instance_class            = ""     # string | optional+computed | Instance class that is used to run this version. Valid value…
  noop_on_destroy           = false  # bool | optional | If set to 'true', the application version will not be delete…
  project                   = ""     # string | optional+computed
  runtime_api_version       = ""     # string | optional | The version of the API in the given runtime environment. Ple…
  service_account           = ""     # string | optional+computed | The identity that the deployed version will run as. Admin AP…
  threadsafe                = false  # bool | optional | Whether multiple requests can be dispatched to this version …
  version_id                = ""     # string | optional | Relative name of the version within the service. For example…

  # name                      = ""     # string | computed | Full path to the Version resource in the API. Example, "v1".

  automatic_scaling { # list [0..1]
    max_concurrent_requests = 0      # number | optional | Number of concurrent requests an automatic scaling instance …
    max_idle_instances      = 0      # number | optional | Maximum number of idle instances that should be maintained f…
    max_pending_latency     = ""     # string | optional | Maximum amount of time that a request should wait in the pen…
    min_idle_instances      = 0      # number | optional | Minimum number of idle instances that should be maintained f…
    min_pending_latency     = ""     # string | optional | Minimum amount of time a request should wait in the pending …

    standard_scheduler_settings { # list [0..1]
      max_instances                 = 0      # number | optional | Maximum number of instances to run for this version. Set to …
      min_instances                 = 0      # number | optional | Minimum number of instances to run for this version. Set to …
      target_cpu_utilization        = 0      # number | optional | Target CPU utilization ratio to maintain when scaling. Shoul…
      target_throughput_utilization = 0      # number | optional | Target throughput utilization ratio to maintain when scaling…

    }

  }

  basic_scaling { # list [0..1]
    max_instances = 0      # number | required | Maximum number of instances to create for this version. Must…
    idle_timeout  = ""     # string | optional | Duration of time after the last request that an instance mus…

  }

  deployment { # list [1..1]

    files { # set
      name       = ""     # string | required
      source_url = ""     # string | required | Source URL
      sha1_sum   = ""     # string | optional | SHA1 checksum of the file

    }

    zip { # list [0..1]
      source_url  = ""     # string | required | Source URL
      files_count = 0      # number | optional | files count

    }

  }

  entrypoint { # list [1..1]
    shell = ""     # string | required | The format should be a shell command that can be fed to bash…

  }

  handlers { # list
    auth_fail_action            = ""     # string | optional | Actions to take when the user is not logged in. Possible val…
    login                       = ""     # string | optional | Methods to restrict access to a URL based on login status. P…
    redirect_http_response_code = ""     # string | optional | 30x code to use when performing redirects for the secure fie…
    security_level              = ""     # string | optional | Security (HTTPS) enforcement for this URL. Possible values: …
    url_regex                   = ""     # string | optional | URL prefix. Uses regular expression syntax, which means rege…

    script { # list [0..1]
      script_path = ""     # string | required | Path to the script from the application root directory.

    }

    static_files { # list [0..1]
      application_readable  = false  # bool | optional | Whether files should also be uploaded as code data. By defau…
      expiration            = ""     # string | optional | Time a static file served by this handler should be cached b…
      http_headers          = {}     # map(string) | optional | HTTP headers to use for all responses from these URLs. An ob…
      mime_type             = ""     # string | optional | MIME type used to serve all files served by this handler. De…
      path                  = ""     # string | optional | Path to the static files matched by the URL pattern, from th…
      require_matching_file = false  # bool | optional | Whether this handler should match the request if the file re…
      upload_path_regex     = ""     # string | optional | Regular expression that matches the file paths for all files…

    }

  }

  libraries { # list
    name    = ""     # string | optional | Name of the library. Example "django".
    version = ""     # string | optional | Version of the library to select, or "latest".

  }

  manual_scaling { # list [0..1]
    instances = 0      # number | required | Number of instances to assign to the service at the start.  …

  }

  timeouts { # single
    create = ""     # string | optional
    delete = ""     # string | optional
    update = ""     # string | optional

  }

  vpc_access_connector { # list [0..1]
    name           = ""     # string | required | Full Serverless VPC Access Connector name e.g. /projects/my-…
    egress_setting = ""     # string | optional | The egress setting for the connector, controlling what traff…

  }

}

