# ┌──────────────────────────────────────────────────────────────┐
# │  resource: google_workflows_workflow                           │
# └──────────────────────────────────────────────────────────────┘
resource "google_workflows_workflow" "this" {

  call_log_level   = ""     # string | optional | Describes the level of platform logging to apply to calls an…
  crypto_key_name  = ""     # string | optional | The KMS key used to encrypt workflow and execution data.  Fo…
  description      = ""     # string | optional+computed | Description of the workflow provided by the user. Must be at…
  id               = ""     # string | optional+computed
  labels           = {}     # map(string) | optional | A set of key/value label pairs to assign to this Workflow.  …
  name             = ""     # string | optional+computed | Name of the Workflow.
  name_prefix      = ""     # string | optional+computed
  project          = ""     # string | optional+computed
  region           = ""     # string | optional | The region of the workflow.
  service_account  = ""     # string | optional+computed | Name of the service account associated with the latest workf…
  source_contents  = ""     # string | optional | Workflow code to be executed. The size limit is 128KB.
  user_env_vars    = {}     # map(string) | optional | User-defined environment variables associated with this work…

  # create_time      = ""     # string | computed | The timestamp of when the workflow was created in RFC3339 UT…
  # effective_labels = {}     # map(string) | computed | All of labels (key/value pairs) present on the resource in G…
  # revision_id      = ""     # string | computed | The revision of the workflow. A new one is generated if the …
  # state            = ""     # string | computed | State of the workflow deployment.
  # terraform_labels = {}     # map(string) | computed | The combination of labels configured directly on the resourc…
  # update_time      = ""     # string | computed | The timestamp of when the workflow was last updated in RFC33…

  timeouts { # single
    create = ""     # string | optional
    delete = ""     # string | optional
    update = ""     # string | optional

  }

}

