# ┌──────────────────────────────────────────────────────────────┐
# │  resource: google_cloudbuild_trigger                           │
# └──────────────────────────────────────────────────────────────┘
resource "google_cloudbuild_trigger" "this" {

  description        = ""     # string | optional | Human-readable description of the trigger.
  disabled           = false  # bool | optional | Whether the trigger is disabled or not. If true, the trigger…
  filename           = ""     # string | optional | Path, from the source root, to a file whose contents is used…
  filter             = ""     # string | optional | A Common Expression Language string. Used only with Pub/Sub …
  id                 = ""     # string | optional+computed
  ignored_files      = []     # list(string) | optional | ignoredFiles and includedFiles are file glob matches using h…
  include_build_logs = ""     # string | optional | Build logs will be sent back to GitHub as part of the checkr…
  included_files     = []     # list(string) | optional | ignoredFiles and includedFiles are file glob matches using h…
  location           = ""     # string | optional | The [Cloud Build location](https://cloud.google.com/build/do…
  name               = ""     # string | optional+computed | Name of the trigger. Must be unique within the project.
  project            = ""     # string | optional+computed
  service_account    = ""     # string | optional | The service account used for all user-controlled operations …
  substitutions      = {}     # map(string) | optional | Substitutions data for Build resource.
  tags               = []     # list(string) | optional | Tags for annotation of a BuildTrigger

  # create_time        = ""     # string | computed | Time when the trigger was created.
  # trigger_id         = ""     # string | computed | The unique identifier for the trigger.

  approval_config { # list [0..1]
    approval_required = false  # bool | optional | Whether or not approval is needed. If this is set on a build…

  }

  bitbucket_server_trigger_config { # list [0..1]
    bitbucket_server_config_resource = ""     # string | required | The Bitbucket server config resource that this trigger confi…
    project_key                      = ""     # string | required | Key of the project that the repo is in. For example: The key…
    repo_slug                        = ""     # string | required | Slug of the repository. A repository slug is a URL-friendly …

    pull_request { # list [0..1]
      branch          = ""     # string | required | Regex of branches to match. The syntax of the regular expres…
      comment_control = ""     # string | optional | Configure builds to run whether a repository owner or collab…
      invert_regex    = false  # bool | optional | If true, branches that do NOT match the git_ref will trigger…

    }

    push { # list [0..1]
      branch       = ""     # string | optional | Regex of branches to match.  Specify only one of branch or t…
      invert_regex = false  # bool | optional | When true, only trigger a build if the revision regex does N…
      tag          = ""     # string | optional | Regex of tags to match.  Specify only one of branch or tag.

    }

  }

  build { # list [0..1]
    images        = []     # list(string) | optional | A list of images to be pushed upon the successful completion…
    logs_bucket   = ""     # string | optional | Google Cloud Storage bucket where logs should be written. Lo…
    queue_ttl     = ""     # string | optional | TTL in queue for this build. If provided and the build is en…
    substitutions = {}     # map(string) | optional | Substitutions data for Build resource.
    tags          = []     # list(string) | optional | Tags for annotation of a Build. These are not docker tags.
    timeout       = ""     # string | optional | Amount of time that this build should be allowed to run, to …

    artifacts { # list [0..1]
      images = []     # list(string) | optional | A list of images to be pushed upon the successful completion…

      maven_artifacts { # list
        artifact_id = ""     # string | optional | Maven artifactId value used when uploading the artifact to A…
        group_id    = ""     # string | optional | Maven groupId value used when uploading the artifact to Arti…
        path        = ""     # string | optional | Path to an artifact in the build's workspace to be uploaded …
        repository  = ""     # string | optional | Artifact Registry repository, in the form "https://$REGION-m…
        version     = ""     # string | optional | Maven version value used when uploading the artifact to Arti…

      }

      npm_packages { # list
        package_path = ""     # string | optional | Path to the package.json. e.g. workspace/path/to/package
        repository   = ""     # string | optional | Artifact Registry repository, in the form "https://$REGION-n…

      }

      objects { # list [0..1]
        location = ""     # string | optional | Cloud Storage bucket and optional object path, in the form "…
        paths    = []     # list(string) | optional | Path globs used to match files in the build's workspace.

        # timing = [  # list(object)
        #   {
        #     end_time = ""
        #     start_time = ""
        #   }
        # ]

      }

      python_packages { # list
        paths      = []     # list(string) | optional | Path globs used to match files in the build's workspace. For…
        repository = ""     # string | optional | Artifact Registry repository, in the form "https://$REGION-p…

      }

    }

    available_secrets { # list [0..1]

      secret_manager { # list [1..*]
        env          = ""     # string | required | Environment variable name to associate with the secret. Secr…
        version_name = ""     # string | required | Resource name of the SecretVersion. In format: projects/*/se…

      }

    }

    options { # list [0..1]
      disk_size_gb            = 0      # number | optional | Requested disk size for the VM that runs the build. Note tha…
      dynamic_substitutions   = false  # bool | optional | Option to specify whether or not to apply bash style string …
      env                     = []     # list(string) | optional | A list of global environment variable definitions that will …
      log_streaming_option    = ""     # string | optional | Option to define build log streaming behavior to Google Clou…
      logging                 = ""     # string | optional | Option to specify the logging mode, which determines if and …
      machine_type            = ""     # string | optional | Compute Engine machine type on which to run the build.
      requested_verify_option = ""     # string | optional | Requested verifiability options. Possible values: ["NOT_VERI…
      secret_env              = []     # list(string) | optional | A list of global environment variables, which are encrypted …
      source_provenance_hash  = []     # list(string) | optional | Requested hash for SourceProvenance. Possible values: ["NONE…
      substitution_option     = ""     # string | optional | Option to specify behavior when there is an error in the sub…
      worker_pool             = ""     # string | optional | Option to specify a WorkerPool for the build. Format project…

      volumes { # list
        name = ""     # string | optional | Name of the volume to mount.  Volume names must be unique pe…
        path = ""     # string | optional | Path at which to mount the volume.  Paths must be absolute a…

      }

    }

    secret { # list
      kms_key_name = ""     # string | required | Cloud KMS key name to use to decrypt these envs.
      secret_env   = {}     # map(string) | optional | Map of environment variable name to its encrypted value. Sec…

    }

    source { # list [0..1]

      repo_source { # list [0..1]
        repo_name     = ""     # string | required | Name of the Cloud Source Repository.
        branch_name   = ""     # string | optional | Regex matching branches to build. Exactly one a of branch na…
        commit_sha    = ""     # string | optional | Explicit commit SHA to build. Exactly one a of branch name, …
        dir           = ""     # string | optional | Directory, relative to the source root, in which to run the …
        invert_regex  = false  # bool | optional | Only trigger a build if the revision regex does NOT match th…
        project_id    = ""     # string | optional | ID of the project that owns the Cloud Source Repository. If …
        substitutions = {}     # map(string) | optional | Substitutions to use in a triggered build. Should only be us…
        tag_name      = ""     # string | optional | Regex matching tags to build. Exactly one a of branch name, …

      }

      storage_source { # list [0..1]
        bucket     = ""     # string | required | Google Cloud Storage bucket containing the source.
        object     = ""     # string | required | Google Cloud Storage object containing the source. This obje…
        generation = ""     # string | optional | Google Cloud Storage generation for the object. If the gener…

      }

    }

    step { # list [1..*]
      name             = ""     # string | required | The name of the container image that will run this particula…
      allow_exit_codes = []     # list(number) | optional | Allow this build step to fail without failing the entire bui…
      allow_failure    = false  # bool | optional | Allow this build step to fail without failing the entire bui…
      args             = []     # list(string) | optional | A list of arguments that will be presented to the step when …
      dir              = ""     # string | optional | Working directory to use when running this step's container.…
      entrypoint       = ""     # string | optional | Entrypoint to be used instead of the build step image's defa…
      env              = []     # list(string) | optional | A list of environment variable definitions to be used when r…
      id               = ""     # string | optional | Unique identifier for this build step, used in 'wait_for' to…
      script           = ""     # string | optional | A shell script to be executed in the step. When script is pr…
      secret_env       = []     # list(string) | optional | A list of environment variables which are encrypted using a …
      timeout          = ""     # string | optional | Time limit for executing this build step. If not defined, th…
      timing           = ""     # string | optional | Output only. Stores timing information for executing this bu…
      wait_for         = []     # list(string) | optional | The ID(s) of the step(s) that this build step depends on.  T…

      volumes { # list
        name = ""     # string | required | Name of the volume to mount.  Volume names must be unique pe…
        path = ""     # string | required | Path at which to mount the volume.  Paths must be absolute a…

      }

    }

  }

  git_file_source { # list [0..1]
    path                     = ""     # string | required | The path of the file, with the repo root as the root of the …
    repo_type                = ""     # string | required | The type of the repo, since it may not be explicit from the …
    bitbucket_server_config  = ""     # string | optional | The full resource name of the bitbucket server config. Forma…
    github_enterprise_config = ""     # string | optional | The full resource name of the github enterprise config. Form…
    repository               = ""     # string | optional | The fully qualified resource name of the Repo API repository…
    revision                 = ""     # string | optional | The branch, tag, arbitrary ref, or SHA version of the repo t…
    uri                      = ""     # string | optional | The URI of the repo (optional). If unspecified, the repo fro…

  }

  github { # list [0..1]
    enterprise_config_resource_name = ""     # string | optional | The resource name of the github enterprise config that shoul…
    name                            = ""     # string | optional | Name of the repository. For example: The name for https://gi…
    owner                           = ""     # string | optional | Owner of the repository. For example: The owner for https://…

    pull_request { # list [0..1]
      branch          = ""     # string | required | Regex of branches to match.
      comment_control = ""     # string | optional | Whether to block builds on a "/gcbrun" comment from a reposi…
      invert_regex    = false  # bool | optional | If true, branches that do NOT match the git_ref will trigger…

    }

    push { # list [0..1]
      branch       = ""     # string | optional | Regex of branches to match.  Specify only one of branch or t…
      invert_regex = false  # bool | optional | When true, only trigger a build if the revision regex does N…
      tag          = ""     # string | optional | Regex of tags to match.  Specify only one of branch or tag.

    }

  }

  pubsub_config { # list [0..1]
    topic                 = ""     # string | required | The name of the topic from which this subscription is receiv…
    service_account_email = ""     # string | optional | Service account that will make the push request.

    # state                 = ""     # string | computed | Potential issues with the underlying Pub/Sub subscription co…
    # subscription          = ""     # string | computed | Output only. Name of the subscription.

  }

  repository_event_config { # list [0..1]
    repository = ""     # string | optional | The resource name of the Repo API resource.

    pull_request { # list [0..1]
      branch          = ""     # string | optional | Regex of branches to match.  The syntax of the regular expre…
      comment_control = ""     # string | optional | Configure builds to run whether a repository owner or collab…
      invert_regex    = false  # bool | optional | If true, branches that do NOT match the git_ref will trigger…

    }

    push { # list [0..1]
      branch       = ""     # string | optional | Regex of branches to match.  The syntax of the regular expre…
      invert_regex = false  # bool | optional | If true, only trigger a build if the revision regex does NOT…
      tag          = ""     # string | optional | Regex of tags to match.  The syntax of the regular expressio…

    }

  }

  source_to_build { # list [0..1]
    ref                      = ""     # string | required | The branch or tag to use. Must start with "refs/" (required)…
    repo_type                = ""     # string | required | The type of the repo, since it may not be explicit from the …
    bitbucket_server_config  = ""     # string | optional | The full resource name of the bitbucket server config. Forma…
    github_enterprise_config = ""     # string | optional | The full resource name of the github enterprise config. Form…
    repository               = ""     # string | optional | The qualified resource name of the Repo API repository. Eith…
    uri                      = ""     # string | optional | The URI of the repo.

  }

  timeouts { # single
    create = ""     # string | optional
    delete = ""     # string | optional
    update = ""     # string | optional

  }

  trigger_template { # list [0..1]
    branch_name  = ""     # string | optional | Name of the branch to build. Exactly one a of branch name, t…
    commit_sha   = ""     # string | optional | Explicit commit SHA to build. Exactly one of a branch name, …
    dir          = ""     # string | optional | Directory, relative to the source root, in which to run the …
    invert_regex = false  # bool | optional | Only trigger a build if the revision regex does NOT match th…
    project_id   = ""     # string | optional+computed | ID of the project that owns the Cloud Source Repository. If …
    repo_name    = ""     # string | optional | Name of the Cloud Source Repository. If omitted, the name "d…
    tag_name     = ""     # string | optional | Name of the tag to build. Exactly one of a branch name, tag,…

  }

  webhook_config { # list [0..1]
    secret = ""     # string | required | Resource name for the secret required as a URL parameter.

    # state  = ""     # string | computed | Potential issues with the underlying Pub/Sub subscription co…

  }

}

