# ┌──────────────────────────────────────────────────────────────┐
# │  resource: google_project                                      │
# └──────────────────────────────────────────────────────────────┘
resource "google_project" "this" {

  name                = ""     # string | required | The display name of the project.
  project_id          = ""     # string | required | The project ID. Changing this forces a new project to be cre…
  auto_create_network = false  # bool | optional | Create the 'default' network automatically.  Default true. I…
  billing_account     = ""     # string | optional | The alphanumeric ID of the billing account this project belo…
  deletion_policy     = ""     # string | optional | The deletion policy for the Project. Setting PREVENT will pr…
  folder_id           = ""     # string | optional | The numeric ID of the folder this project should be created …
  id                  = ""     # string | optional+computed
  labels              = {}     # map(string) | optional | A set of key/value label pairs to assign to the project. 			…
  org_id              = ""     # string | optional | The numeric ID of the organization this project belongs to. …
  skip_delete         = false  # bool | optional+computed+DEPRECATED | If true, the Terraform resource can be deleted without delet…

  # effective_labels    = {}     # map(string) | computed | All of labels (key/value pairs) present on the resource in G…
  # number              = ""     # string | computed | The numeric identifier of the project.
  # terraform_labels    = {}     # map(string) | computed | (ReadOnly) The combination of labels configured directly on …

  timeouts { # single
    create = ""     # string | optional
    delete = ""     # string | optional
    read   = ""     # string | optional
    update = ""     # string | optional

  }

}

