# ┌──────────────────────────────────────────────────────────────┐
# │  resource: google_dataflow_job                                 │
# └──────────────────────────────────────────────────────────────┘
resource "google_dataflow_job" "this" {

  name                         = ""     # string | required | A unique name for the resource, required by Dataflow.
  temp_gcs_location            = ""     # string | required | A writeable location on Google Cloud Storage for the Dataflo…
  template_gcs_path            = ""     # string | required | The Google Cloud Storage path to the Dataflow job template.
  additional_experiments       = []     # set(string) | optional+computed | List of experiments that should be used by the job. An examp…
  enable_streaming_engine      = false  # bool | optional | Indicates if the job should use the streaming engine feature…
  id                           = ""     # string | optional+computed
  ip_configuration             = ""     # string | optional | The configuration for VM IPs. Options are "WORKER_IP_PUBLIC"…
  kms_key_name                 = ""     # string | optional | The name for the Cloud KMS key for the job. Key format is: p…
  labels                       = {}     # map(string) | optional | User labels to be specified for the job. Keys and values sho…
  machine_type                 = ""     # string | optional | The machine type to use for the job.
  max_workers                  = 0      # number | optional | The number of workers permitted to work on the job. More wor…
  network                      = ""     # string | optional | The network to which VMs will be assigned. If it is not prov…
  on_delete                    = ""     # string | optional | One of "drain" or "cancel". Specifies behavior of deletion d…
  parameters                   = {}     # map(string) | optional | Key/Value pairs to be passed to the Dataflow job (as used in…
  project                      = ""     # string | optional+computed | The project in which the resource belongs.
  region                       = ""     # string | optional | The region in which the created job should run.
  service_account_email        = ""     # string | optional | The Service Account email used to create the job.
  skip_wait_on_job_termination = false  # bool | optional | If true, treat DRAINING and CANCELLING as terminal job state…
  subnetwork                   = ""     # string | optional | The subnetwork to which VMs will be assigned. Should be of t…
  transform_name_mapping       = {}     # map(string) | optional | Only applicable when updating a pipeline. Map of transform n…
  zone                         = ""     # string | optional | The zone in which the created job should run. If it is not p…

  # effective_labels             = {}     # map(string) | computed | All of labels (key/value pairs) present on the resource in G…
  # job_id                       = ""     # string | computed | The unique ID of this job.
  # state                        = ""     # string | computed | The current state of the resource, selected from the JobStat…
  # terraform_labels             = {}     # map(string) | computed | The combination of labels configured directly on the resourc…
  # type                         = ""     # string | computed | The type of this job, selected from the JobType enum.

  timeouts { # single
    update = ""     # string | optional

  }

}

