# ┌──────────────────────────────────────────────────────────────┐
# │  resource: google_cloud_quotas_quota_preference                │
# └──────────────────────────────────────────────────────────────┘
resource "google_cloud_quotas_quota_preference" "this" {

  contact_email        = ""     # string | optional | An email address that can be used for quota related communic…
  dimensions           = {}     # map(string) | optional+computed | The dimensions that this quota preference applies to. The ke…
  id                   = ""     # string | optional+computed
  ignore_safety_checks = ""     # string | optional | The list of quota safety checks to be ignored. Default value…
  justification        = ""     # string | optional | The reason / justification for this quota preference.
  name                 = ""     # string | optional+computed | The resource name of the quota preference. Required except i…
  parent               = ""     # string | optional+computed | The parent of the quota preference. Allowed parents are "pro…
  quota_id             = ""     # string | optional+computed | The id of the quota to which the quota preference is applied…
  service              = ""     # string | optional+computed | The name of the service to which the quota preference is app…

  # create_time          = ""     # string | computed | Create time stamp. A timestamp in RFC3339 UTC "Zulu" format,…
  # etag                 = ""     # string | computed | The current etag of the quota preference. If an etag is prov…
  # reconciling          = false  # bool | computed | Is the quota preference pending Google Cloud approval and fu…
  # update_time          = ""     # string | computed | Update time stamp. A timestamp in RFC3339 UTC "Zulu" format,…

  quota_config { # list [1..1]
    preferred_value = ""     # string | required | The preferred value. Must be greater than or equal to -1. If…
    annotations     = {}     # map(string) | optional | The annotations map for clients to store small amounts of ar…

    # granted_value   = ""     # string | computed | Granted quota value.
    # request_origin  = ""     # string | computed | The origin of the quota preference request.
    # state_detail    = ""     # string | computed | Optional details about the state of this quota preference.
    # trace_id        = ""     # string | computed | The trace id that the Google Cloud uses to provision the req…

  }

  timeouts { # single
    create = ""     # string | optional
    delete = ""     # string | optional
    update = ""     # string | optional

  }

}

