# ┌──────────────────────────────────────────────────────────────┐
# │  resource: google_dialogflow_agent                             │
# └──────────────────────────────────────────────────────────────┘
resource "google_dialogflow_agent" "this" {

  default_language_code    = ""     # string | required | The default language of the agent as a language tag. [See La…
  display_name             = ""     # string | required | The name of this agent.
  time_zone                = ""     # string | required | The time zone of this agent from the [time zone database](ht…
  api_version              = ""     # string | optional+computed | API version displayed in Dialogflow console. If not specifie…
  avatar_uri               = ""     # string | optional | The URI of the agent's avatar, which are used throughout the…
  classification_threshold = 0      # number | optional | To filter out false positive results and still get variety i…
  description              = ""     # string | optional | The description of this agent. The maximum length is 500 cha…
  enable_logging           = false  # bool | optional | Determines whether this agent should log conversation querie…
  id                       = ""     # string | optional+computed
  match_mode               = ""     # string | optional+computed | Determines how intents are detected from user queries. * MAT…
  project                  = ""     # string | optional+computed
  supported_language_codes = []     # list(string) | optional | The list of all languages supported by this agent (except fo…
  tier                     = ""     # string | optional | The agent tier. If not specified, TIER_STANDARD is assumed. …

  # avatar_uri_backend       = ""     # string | computed | The URI of the agent's avatar as returned from the API. Outp…

  timeouts { # single
    create = ""     # string | optional
    delete = ""     # string | optional
    update = ""     # string | optional

  }

}

