# ┌──────────────────────────────────────────────────────────────┐
# │  resource: google_netapp_storage_pool                          │
# └──────────────────────────────────────────────────────────────┘
resource "google_netapp_storage_pool" "this" {

  capacity_gib        = ""     # string | required | Capacity of the storage pool (in GiB).
  location            = ""     # string | required | Name of the location. For zonal Flex pools specify a zone na…
  name                = ""     # string | required | The resource name of the storage pool. Needs to be unique pe…
  network             = ""     # string | required | VPC network name with format: 'projects/{{project}}/global/n…
  service_level       = ""     # string | required | Service level of the storage pool. Possible values: ["PREMIU…
  active_directory    = ""     # string | optional | Specifies the Active Directory policy to be used. Format: 'p…
  description         = ""     # string | optional | An optional description of this resource.
  id                  = ""     # string | optional+computed
  kms_config          = ""     # string | optional | Specifies the CMEK policy to be used for volume encryption. …
  labels              = {}     # map(string) | optional | Labels as key value pairs. Example: '{ "owner": "Bob", "depa…
  ldap_enabled        = false  # bool | optional | When enabled, the volumes uses Active Directory as LDAP name…
  project             = ""     # string | optional+computed

  # effective_labels    = {}     # map(string) | computed | All of labels (key/value pairs) present on the resource in G…
  # encryption_type     = ""     # string | computed | Reports if volumes in the pool are encrypted using a Google-…
  # terraform_labels    = {}     # map(string) | computed | The combination of labels configured directly on the resourc…
  # volume_capacity_gib = ""     # string | computed | Size allocated to volumes in the storage pool (in GiB).
  # volume_count        = 0      # number | computed | Number of volume in the storage pool.

  timeouts { # single
    create = ""     # string | optional
    delete = ""     # string | optional
    update = ""     # string | optional

  }

}

