# ┌──────────────────────────────────────────────────────────────┐
# │  resource: google_cloudfunctions2_function                     │
# └──────────────────────────────────────────────────────────────┘
resource "google_cloudfunctions2_function" "this" {

  location         = ""     # string | required | The location of this cloud function.
  name             = ""     # string | required | A user-defined name of the function. Function names must be …
  description      = ""     # string | optional | User-provided description of a function.
  id               = ""     # string | optional+computed
  kms_key_name     = ""     # string | optional | Resource name of a KMS crypto key (managed by the user) used…
  labels           = {}     # map(string) | optional | A set of key/value label pairs associated with this Cloud Fu…
  project          = ""     # string | optional+computed

  # effective_labels = {}     # map(string) | computed | All of labels (key/value pairs) present on the resource in G…
  # environment      = ""     # string | computed | The environment the function is hosted on.
  # state            = ""     # string | computed | Describes the current state of the function.
  # terraform_labels = {}     # map(string) | computed | The combination of labels configured directly on the resourc…
  # update_time      = ""     # string | computed | The last update timestamp of a Cloud Function.
  # url              = ""     # string | computed | Output only. The deployed url for the function.

  build_config { # list [0..1]
    docker_repository     = ""     # string | optional+computed | User managed repository created in Artifact Registry optiona…
    entry_point           = ""     # string | optional | The name of the function (as defined in source code) that wi…
    environment_variables = {}     # map(string) | optional+computed | User-provided build-time environment variables for the funct…
    runtime               = ""     # string | optional | The runtime in which to run the function. Required when depl…
    service_account       = ""     # string | optional+computed | The fully-qualified name of the service account to be used f…
    worker_pool           = ""     # string | optional | Name of the Cloud Build Custom Worker Pool that should be us…

    # build                 = ""     # string | computed | The Cloud Build name of the latest successful deployment of …

    automatic_update_policy {} # list [0..1]

    on_deploy_update_policy { # list [0..1]

      # runtime_version = ""     # string | computed | The runtime version which was used during latest function de…

    }

    source { # list [0..1]

      repo_source { # list [0..1]
        branch_name  = ""     # string | optional | Regex matching branches to build.
        commit_sha   = ""     # string | optional | Regex matching tags to build.
        dir          = ""     # string | optional | Directory, relative to the source root, in which to run the …
        invert_regex = false  # bool | optional | Only trigger a build if the revision regex does NOT match th…
        project_id   = ""     # string | optional | ID of the project that owns the Cloud Source Repository. If …
        repo_name    = ""     # string | optional | Name of the Cloud Source Repository.
        tag_name     = ""     # string | optional | Regex matching tags to build.

      }

      storage_source { # list [0..1]
        bucket     = ""     # string | optional | Google Cloud Storage bucket containing the source
        generation = 0      # number | optional+computed | Google Cloud Storage generation for the object. If the gener…
        object     = ""     # string | optional | Google Cloud Storage object containing the source.

      }

    }

  }

  event_trigger { # list [0..1]
    event_type            = ""     # string | optional | Required. The type of event to observe.
    pubsub_topic          = ""     # string | optional+computed | The name of a Pub/Sub topic in the same project that will be…
    retry_policy          = ""     # string | optional | Describes the retry policy in case of function's execution f…
    service_account_email = ""     # string | optional+computed | Optional. The email of the trigger's service account. The se…
    trigger_region        = ""     # string | optional+computed | The region that the trigger will be in. The trigger will onl…

    # trigger               = ""     # string | computed | Output only. The resource name of the Eventarc trigger.

    event_filters { # set
      attribute = ""     # string | required | 'Required. The name of a CloudEvents attribute. Currently, o…
      value     = ""     # string | required | Required. The value for the attribute. If the operator field…
      operator  = ""     # string | optional | Optional. The operator used for matching the events with the…

    }

  }

  service_config { # list [0..1]
    all_traffic_on_latest_revision   = false  # bool | optional | Whether 100% of traffic is routed to the latest revision. De…
    available_cpu                    = ""     # string | optional+computed | The number of CPUs used in a single container instance. Defa…
    available_memory                 = ""     # string | optional+computed | The amount of memory available for a function. Defaults to 2…
    environment_variables            = {}     # map(string) | optional+computed | Environment variables that shall be available during functio…
    ingress_settings                 = ""     # string | optional | Available ingress settings. Defaults to "ALLOW_ALL" if unspe…
    max_instance_count               = 0      # number | optional+computed | The limit on the maximum number of function instances that m…
    max_instance_request_concurrency = 0      # number | optional+computed | Sets the maximum number of concurrent requests that each ins…
    min_instance_count               = 0      # number | optional | The limit on the minimum number of function instances that m…
    service                          = ""     # string | optional+computed | Name of the service associated with a Function.
    service_account_email            = ""     # string | optional+computed | The email of the service account for this function.
    timeout_seconds                  = 0      # number | optional+computed | The function execution timeout. Execution is considered fail…
    vpc_connector                    = ""     # string | optional | The Serverless VPC Access connector that this cloud function…
    vpc_connector_egress_settings    = ""     # string | optional | Available egress settings. Possible values: ["VPC_CONNECTOR_…

    # gcf_uri                          = ""     # string | computed | URIs of the Service deployed
    # uri                              = ""     # string | computed | URI of the Service deployed.

    secret_environment_variables { # list
      key        = ""     # string | required | Name of the environment variable.
      project_id = ""     # string | required | Project identifier (preferrably project number but can also …
      secret     = ""     # string | required | Name of the secret in secret manager (not the full resource …
      version    = ""     # string | required | Version of the secret (version number or the string 'latest'…

    }

    secret_volumes { # list
      mount_path = ""     # string | required | The path within the container to mount the secret volume. Fo…
      project_id = ""     # string | required | Project identifier (preferrably project number but can also …
      secret     = ""     # string | required | Name of the secret in secret manager (not the full resource …

      versions { # list
        path    = ""     # string | required | Relative path of the file under the mount path where the sec…
        version = ""     # string | required | Version of the secret (version number or the string 'latest'…

      }

    }

  }

  timeouts { # single
    create = ""     # string | optional
    delete = ""     # string | optional
    update = ""     # string | optional

  }

}

