# ┌──────────────────────────────────────────────────────────────┐
# │  resource: google_compute_target_https_proxy                   │
# └──────────────────────────────────────────────────────────────┘
resource "google_compute_target_https_proxy" "this" {

  name                             = ""     # string | required | Name of the resource. Provided by the client when the resour…
  url_map                          = ""     # string | required | A reference to the UrlMap resource that defines the mapping …
  certificate_manager_certificates = []     # list(string) | optional | URLs to certificate manager certificate resources that are u…
  certificate_map                  = ""     # string | optional | A reference to the CertificateMap resource uri that identifi…
  description                      = ""     # string | optional | An optional description of this resource.
  http_keep_alive_timeout_sec      = 0      # number | optional | Specifies how long to keep a connection open, after completi…
  id                               = ""     # string | optional+computed
  project                          = ""     # string | optional+computed
  proxy_bind                       = false  # bool | optional+computed | This field only applies when the forwarding rule that refere…
  quic_override                    = ""     # string | optional | Specifies the QUIC override policy for this resource. This d…
  server_tls_policy                = ""     # string | optional | A URL referring to a networksecurity.ServerTlsPolicy resourc…
  ssl_certificates                 = []     # list(string) | optional | URLs to SslCertificate resources that are used to authentica…
  ssl_policy                       = ""     # string | optional | A reference to the SslPolicy resource that will be associate…
  tls_early_data                   = ""     # string | optional+computed | Specifies whether TLS 1.3 0-RTT Data (“Early Data”) should b…

  # creation_timestamp               = ""     # string | computed | Creation timestamp in RFC3339 text format.
  # proxy_id                         = 0      # number | computed | The unique identifier for the resource.
  # self_link                        = ""     # string | computed

  timeouts { # single
    create = ""     # string | optional
    delete = ""     # string | optional
    update = ""     # string | optional

  }

}

