# ┌──────────────────────────────────────────────────────────────┐
# │  resource: google_dialogflow_cx_intent                         │
# └──────────────────────────────────────────────────────────────┘
resource "google_dialogflow_cx_intent" "this" {

  display_name               = ""     # string | required | The human-readable name of the intent, unique within the age…
  description                = ""     # string | optional | Human readable description for better understanding an inten…
  id                         = ""     # string | optional+computed
  is_default_negative_intent = false  # bool | optional | Marks this as the [Default Negative Intent](https://cloud.go…
  is_default_welcome_intent  = false  # bool | optional | Marks this as the [Default Welcome Intent](https://cloud.goo…
  is_fallback                = false  # bool | optional | Indicates whether this is a fallback intent. Currently only …
  labels                     = {}     # map(string) | optional | The key/value metadata to label an intent. Labels can contai…
  language_code              = ""     # string | optional | The language of the following fields in intent: Intent.train…
  parent                     = ""     # string | optional | The agent to create an intent for. Format: projects/<Project…
  priority                   = 0      # number | optional | The priority of this intent. Higher numbers represent higher…

  # effective_labels           = {}     # map(string) | computed | All of labels (key/value pairs) present on the resource in G…
  # name                       = ""     # string | computed | The unique identifier of the intent. Format: projects/<Proje…
  # terraform_labels           = {}     # map(string) | computed | The combination of labels configured directly on the resourc…

  parameters { # list
    entity_type = ""     # string | required | The entity type of the parameter. Format: projects/-/locatio…
    id          = ""     # string | required | The unique identifier of the parameter. This field is used b…
    is_list     = false  # bool | optional | Indicates whether the parameter represents a list of values.
    redact      = false  # bool | optional | Indicates whether the parameter content should be redacted i…

  }

  timeouts { # single
    create = ""     # string | optional
    delete = ""     # string | optional
    update = ""     # string | optional

  }

  training_phrases { # list
    repeat_count = 0      # number | optional | Indicates how many times this example was added to the inten…

    # id           = ""     # string | computed | The unique identifier of the training phrase.

    parts { # list [1..*]
      text         = ""     # string | required | The text for this part.
      parameter_id = ""     # string | optional | The parameter used to annotate this part of the training phr…

    }

  }

}

