# ┌──────────────────────────────────────────────────────────────┐
# │  resource: google_netapp_volume                                │
# └──────────────────────────────────────────────────────────────┘
resource "google_netapp_volume" "this" {

  capacity_gib       = ""     # string | required | Capacity of the volume (in GiB).
  location           = ""     # string | required | Name of the pool location. Usually a region name, expect for…
  name               = ""     # string | required | The name of the volume. Needs to be unique per location.
  protocols          = []     # list(string) | required | The protocol of the volume. Allowed combinations are '['NFSV…
  share_name         = ""     # string | required | Share name (SMB) or export path (NFS) of the volume. Needs t…
  storage_pool       = ""     # string | required | Name of the storage pool to create the volume in. Pool needs…
  deletion_policy    = ""     # string | optional | Policy to determine if the volume should be deleted forceful…
  description        = ""     # string | optional | An optional description of this resource.
  id                 = ""     # string | optional+computed
  kerberos_enabled   = false  # bool | optional | Flag indicating if the volume is a kerberos volume or not, e…
  labels             = {}     # map(string) | optional | Labels as key value pairs. Example: '{ "owner": "Bob", "depa…
  project            = ""     # string | optional+computed
  restricted_actions = []     # list(string) | optional | List of actions that are restricted on this volume. Possible…
  security_style     = ""     # string | optional+computed | Security Style of the Volume. Use UNIX to use UNIX or NFSV4 …
  smb_settings       = []     # list(string) | optional+computed | Settings for volumes with SMB access. Possible values: ["ENC…
  snapshot_directory = false  # bool | optional | If enabled, a NFS volume will contain a read-only .snapshot …
  unix_permissions   = ""     # string | optional+computed | Unix permission the mount point will be created with. Defaul…

  # active_directory   = ""     # string | computed | Reports the resource name of the Active Directory policy bei…
  # create_time        = ""     # string | computed | Create time of the volume. A timestamp in RFC3339 UTC "Zulu"…
  # effective_labels   = {}     # map(string) | computed | All of labels (key/value pairs) present on the resource in G…
  # encryption_type    = ""     # string | computed | Reports the data-at-rest encryption type of the volume. Inhe…
  # has_replication    = false  # bool | computed | Indicates whether the volume is part of a volume replication…
  # kms_config         = ""     # string | computed | Reports the CMEK policy resurce name being used for volume e…
  # ldap_enabled       = false  # bool | computed | Flag indicating if the volume is NFS LDAP enabled or not. In…
  # mount_options = [  # list(object)
  #   {
  #     export = ""
  #     export_full = ""
  #     instructions = ""
  #     protocol = ""
  #   }
  # ]
  # network            = ""     # string | computed | VPC network name with format: 'projects/{{project}}/global/n…
  # psa_range          = ""     # string | computed | Name of the Private Service Access allocated range. Inherite…
  # service_level      = ""     # string | computed | Service level of the volume. Inherited from storage pool. Su…
  # state              = ""     # string | computed | State of the volume.
  # state_details      = ""     # string | computed | State details of the volume.
  # terraform_labels   = {}     # map(string) | computed | The combination of labels configured directly on the resourc…
  # used_gib           = ""     # string | computed | Used capacity of the volume (in GiB). This is computed perio…

  backup_config { # list [0..1]
    backup_policies          = []     # list(string) | optional | Specify a single backup policy ID for scheduled backups. For…
    backup_vault             = ""     # string | optional | ID of the backup vault to use. A backup vault is reqired to …
    scheduled_backup_enabled = false  # bool | optional | When set to true, scheduled backup is enabled on the volume.…

  }

  export_policy { # list [0..1]

    rules { # list [1..*]
      access_type           = ""     # string | optional | Defines the access type for clients matching the 'allowedCli…
      allowed_clients       = ""     # string | optional | Defines the client ingress specification (allowed clients) a…
      has_root_access       = ""     # string | optional | If enabled, the root user (UID = 0) of the specified clients…
      kerberos5_read_only   = false  # bool | optional | If enabled (true) the rule defines a read only access for cl…
      kerberos5_read_write  = false  # bool | optional | If enabled (true) the rule defines read and write access for…
      kerberos5i_read_only  = false  # bool | optional | If enabled (true) the rule defines a read only access for cl…
      kerberos5i_read_write = false  # bool | optional | If enabled (true) the rule defines read and write access for…
      kerberos5p_read_only  = false  # bool | optional | If enabled (true) the rule defines a read only access for cl…
      kerberos5p_read_write = false  # bool | optional | If enabled (true) the rule defines read and write access for…
      nfsv3                 = false  # bool | optional | Enable to apply the export rule to NFSV3 clients.
      nfsv4                 = false  # bool | optional | Enable to apply the export rule to NFSV4.1 clients.

    }

  }

  restore_parameters { # list [0..1]
    source_backup   = ""     # string | optional | Full name of the snapshot to use for creating this volume. '…
    source_snapshot = ""     # string | optional | Full name of the snapshot to use for creating this volume. '…

  }

  snapshot_policy { # list [0..1]
    enabled = false  # bool | optional | Enables automated snapshot creation according to defined sch…

    daily_schedule { # list [0..1]
      snapshots_to_keep = 0      # number | required | The maximum number of snapshots to keep for the daily schedu…
      hour              = 0      # number | optional | Set the hour to create the snapshot (0-23), defaults to midn…
      minute            = 0      # number | optional | Set the minute of the hour to create the snapshot (0-59), de…

    }

    hourly_schedule { # list [0..1]
      snapshots_to_keep = 0      # number | required | The maximum number of snapshots to keep for the hourly sched…
      minute            = 0      # number | optional | Set the minute of the hour to create the snapshot (0-59), de…

    }

    monthly_schedule { # list [0..1]
      snapshots_to_keep = 0      # number | required | The maximum number of snapshots to keep for the monthly sche…
      days_of_month     = ""     # string | optional | Set the day or days of the month to make a snapshot (1-31). …
      hour              = 0      # number | optional | Set the hour to create the snapshot (0-23), defaults to midn…
      minute            = 0      # number | optional | Set the minute of the hour to create the snapshot (0-59), de…

    }

    weekly_schedule { # list [0..1]
      snapshots_to_keep = 0      # number | required | The maximum number of snapshots to keep for the weekly sched…
      day               = ""     # string | optional | Set the day or days of the week to make a snapshot. Accepts …
      hour              = 0      # number | optional | Set the hour to create the snapshot (0-23), defaults to midn…
      minute            = 0      # number | optional | Set the minute of the hour to create the snapshot (0-59), de…

    }

  }

  timeouts { # single
    create = ""     # string | optional
    delete = ""     # string | optional
    update = ""     # string | optional

  }

}

