# ┌──────────────────────────────────────────────────────────────┐
# │  resource: google_compute_router_interface                     │
# └──────────────────────────────────────────────────────────────┘
resource "google_compute_router_interface" "this" {

  name                    = ""     # string | required | A unique name for the interface, required by GCE. Changing t…
  router                  = ""     # string | required | The name of the router this interface will be attached to. C…
  id                      = ""     # string | optional+computed
  interconnect_attachment = ""     # string | optional | The name or resource link to the VLAN interconnect for this …
  ip_range                = ""     # string | optional+computed | The IP address and range of the interface. The IP range must…
  ip_version              = ""     # string | optional+computed | IP version of this interface.
  private_ip_address      = ""     # string | optional | The regional private internal IP address that is used to est…
  project                 = ""     # string | optional+computed | The ID of the project in which this interface's router belon…
  redundant_interface     = ""     # string | optional+computed | The name of the interface that is redundant to this interfac…
  region                  = ""     # string | optional+computed | The region this interface's router sits in. If not specified…
  subnetwork              = ""     # string | optional | The URI of the subnetwork resource that this interface belon…
  vpn_tunnel              = ""     # string | optional | The name or resource link to the VPN tunnel this interface w…

  timeouts { # single
    create = ""     # string | optional
    delete = ""     # string | optional

  }

}

