# ┌──────────────────────────────────────────────────────────────┐
# │  resource: google_compute_region_disk                          │
# └──────────────────────────────────────────────────────────────┘
resource "google_compute_region_disk" "this" {

  name                      = ""     # string | required | Name of the resource. Provided by the client when the resour…
  replica_zones             = []     # list(string) | required | URLs of the zones where the disk should be replicated to.
  description               = ""     # string | optional | An optional description of this resource. Provide this prope…
  id                        = ""     # string | optional+computed
  labels                    = {}     # map(string) | optional | Labels to apply to this disk.  A list of key->value pairs.  …
  licenses                  = []     # list(string) | optional+computed | Any applicable license URI.
  physical_block_size_bytes = 0      # number | optional+computed | Physical block size of the persistent disk, in bytes. If not…
  project                   = ""     # string | optional+computed
  region                    = ""     # string | optional+computed | A reference to the region where the disk resides.
  size                      = 0      # number | optional+computed | Size of the persistent disk, specified in GB. You can specif…
  snapshot                  = ""     # string | optional | The source snapshot used to create this disk. You can provid…
  source_disk               = ""     # string | optional | The source disk used to create this disk. You can provide th…
  type                      = ""     # string | optional | URL of the disk type resource describing which disk type to …

  # creation_timestamp        = ""     # string | computed | Creation timestamp in RFC3339 text format.
  # effective_labels          = {}     # map(string) | computed | All of labels (key/value pairs) present on the resource in G…
  # label_fingerprint         = ""     # string | computed | The fingerprint used for optimistic locking of this resource…
  # last_attach_timestamp     = ""     # string | computed | Last attach timestamp in RFC3339 text format.
  # last_detach_timestamp     = ""     # string | computed | Last detach timestamp in RFC3339 text format.
  # self_link                 = ""     # string | computed
  # source_disk_id            = ""     # string | computed | The ID value of the disk used to create this image. This val…
  # source_snapshot_id        = ""     # string | computed | The unique ID of the snapshot used to create this disk. This…
  # terraform_labels          = {}     # map(string) | computed | The combination of labels configured directly on the resourc…
  # users                     = []     # list(string) | computed | Links to the users of the disk (attached instances) in form:…

  async_primary_disk { # list [0..1]
    disk = ""     # string | required | Primary disk for asynchronous disk replication.

  }

  disk_encryption_key { # list [0..1]
    kms_key_name = ""     # string | optional | The name of the encryption key that is stored in Google Clou…
    raw_key      = ""     # string | optional+sensitive | Specifies a 256-bit customer-supplied encryption key, encode…

    # sha256       = ""     # string | computed | The RFC 4648 base64 encoded SHA-256 hash of the customer-sup…

  }

  guest_os_features { # set
    type = ""     # string | required | The type of supported feature. Read [Enabling guest operatin…

  }

  source_snapshot_encryption_key { # list [0..1]
    raw_key = ""     # string | optional | Specifies a 256-bit customer-supplied encryption key, encode…

    # sha256  = ""     # string | computed | The RFC 4648 base64 encoded SHA-256 hash of the customer-sup…

  }

  timeouts { # single
    create = ""     # string | optional
    delete = ""     # string | optional
    update = ""     # string | optional

  }

}

