# ┌──────────────────────────────────────────────────────────────┐
# │  resource: google_healthcare_fhir_store                        │
# └──────────────────────────────────────────────────────────────┘
resource "google_healthcare_fhir_store" "this" {

  dataset                             = ""     # string | required | Identifies the dataset addressed by this request. Must be in…
  name                                = ""     # string | required | The resource name for the FhirStore.  ** Changing this prope…
  version                             = ""     # string | required | The FHIR specification version. Possible values: ["DSTU2", "…
  complex_data_type_reference_parsing = ""     # string | optional+computed | Enable parsing of references within complex FHIR data types …
  default_search_handling_strict      = false  # bool | optional | If true, overrides the default search behavior for this FHIR…
  disable_referential_integrity       = false  # bool | optional | Whether to disable referential integrity in this FHIR store.…
  disable_resource_versioning         = false  # bool | optional | Whether to disable resource versioning for this FHIR store. …
  enable_history_import               = false  # bool | optional | Whether to allow the bulk import API to accept history bundl…
  enable_update_create                = false  # bool | optional | Whether this FHIR store has the updateCreate capability. Thi…
  id                                  = ""     # string | optional+computed
  labels                              = {}     # map(string) | optional | User-supplied key-value pairs used to organize FHIR stores. …

  # effective_labels                    = {}     # map(string) | computed | All of labels (key/value pairs) present on the resource in G…
  # self_link                           = ""     # string | computed | The fully qualified name of this dataset
  # terraform_labels                    = {}     # map(string) | computed | The combination of labels configured directly on the resourc…

  notification_config { # list [0..1] DEPRECATED
    pubsub_topic = ""     # string | required | The Cloud Pub/Sub topic that notifications of changes are pu…

  }

  notification_configs { # list
    pubsub_topic                     = ""     # string | required | The Cloud Pub/Sub topic that notifications of changes are pu…
    send_full_resource               = false  # bool | optional | Whether to send full FHIR resource to this Pub/Sub topic for…
    send_previous_resource_on_delete = false  # bool | optional | Whether to send full FHIR resource to this Pub/Sub topic for…

  }

  stream_configs { # list
    resource_types = []     # list(string) | optional | Supply a FHIR resource type (such as "Patient" or "Observati…

    bigquery_destination { # list [1..1]
      dataset_uri = ""     # string | required | BigQuery URI to a dataset, up to 2000 characters long, in th…

      schema_config { # list [1..1]
        recursive_structure_depth = 0      # number | required | The depth for all recursive structures in the output analyti…
        schema_type               = ""     # string | optional | Specifies the output schema type.  * ANALYTICS: Analytics sc…

        last_updated_partition_config { # list [0..1]
          type          = ""     # string | required | Type of partitioning. Possible values: ["PARTITION_TYPE_UNSP…
          expiration_ms = ""     # string | optional | Number of milliseconds for which to keep the storage for a p…

        }

      }

    }

  }

  timeouts { # single
    create = ""     # string | optional
    delete = ""     # string | optional
    update = ""     # string | optional

  }

}

