# ┌──────────────────────────────────────────────────────────────┐
# │  resource: google_compute_disk                                 │
# └──────────────────────────────────────────────────────────────┘
resource "google_compute_disk" "this" {

  name                        = ""     # string | required | Name of the resource. Provided by the client when the resour…
  access_mode                 = ""     # string | optional+computed | The accessMode of the disk. For example: * READ_WRITE_SINGLE…
  description                 = ""     # string | optional | An optional description of this resource. Provide this prope…
  enable_confidential_compute = false  # bool | optional+computed | Whether this disk is using confidential compute mode. Note: …
  id                          = ""     # string | optional+computed
  image                       = ""     # string | optional | The image from which to initialize this disk. This can be on…
  labels                      = {}     # map(string) | optional | Labels to apply to this disk.  A list of key->value pairs.  …
  licenses                    = []     # list(string) | optional+computed | Any applicable license URI.
  physical_block_size_bytes   = 0      # number | optional+computed | Physical block size of the persistent disk, in bytes. If not…
  project                     = ""     # string | optional+computed
  provisioned_iops            = 0      # number | optional+computed | Indicates how many IOPS must be provisioned for the disk. No…
  provisioned_throughput      = 0      # number | optional+computed | Indicates how much Throughput must be provisioned for the di…
  size                        = 0      # number | optional+computed | Size of the persistent disk, specified in GB. You can specif…
  snapshot                    = ""     # string | optional | The source snapshot used to create this disk. You can provid…
  source_disk                 = ""     # string | optional | The source disk used to create this disk. You can provide th…
  storage_pool                = ""     # string | optional | The URL of the storage pool in which the new disk is created…
  type                        = ""     # string | optional | URL of the disk type resource describing which disk type to …
  zone                        = ""     # string | optional+computed | A reference to the zone where the disk resides.

  # creation_timestamp          = ""     # string | computed | Creation timestamp in RFC3339 text format.
  # disk_id                     = ""     # string | computed | The unique identifier for the resource. This identifier is d…
  # effective_labels            = {}     # map(string) | computed | All of labels (key/value pairs) present on the resource in G…
  # label_fingerprint           = ""     # string | computed | The fingerprint used for optimistic locking of this resource…
  # last_attach_timestamp       = ""     # string | computed | Last attach timestamp in RFC3339 text format.
  # last_detach_timestamp       = ""     # string | computed | Last detach timestamp in RFC3339 text format.
  # self_link                   = ""     # string | computed
  # source_disk_id              = ""     # string | computed | The ID value of the disk used to create this image. This val…
  # source_image_id             = ""     # string | computed | The ID value of the image used to create this disk. This val…
  # source_snapshot_id          = ""     # string | computed | The unique ID of the snapshot used to create this disk. This…
  # terraform_labels            = {}     # map(string) | computed | The combination of labels configured directly on the resourc…
  # users                       = []     # list(string) | computed | Links to the users of the disk (attached instances) in form:…

  async_primary_disk { # list [0..1]
    disk = ""     # string | required | Primary disk for asynchronous disk replication.

  }

  disk_encryption_key { # list [0..1]
    kms_key_self_link       = ""     # string | optional | The self link of the encryption key used to encrypt the disk…
    kms_key_service_account = ""     # string | optional | The service account used for the encryption request for the …
    raw_key                 = ""     # string | optional+sensitive | Specifies a 256-bit customer-supplied encryption key, encode…
    rsa_encrypted_key       = ""     # string | optional+sensitive | Specifies an RFC 4648 base64 encoded, RSA-wrapped 2048-bit c…

    # sha256                  = ""     # string | computed | The RFC 4648 base64 encoded SHA-256 hash of the customer-sup…

  }

  guest_os_features { # set
    type = ""     # string | required | The type of supported feature. Read [Enabling guest operatin…

  }

  source_image_encryption_key { # list [0..1]
    kms_key_self_link       = ""     # string | optional | The self link of the encryption key used to encrypt the disk…
    kms_key_service_account = ""     # string | optional | The service account used for the encryption request for the …
    raw_key                 = ""     # string | optional | Specifies a 256-bit customer-supplied encryption key, encode…

    # sha256                  = ""     # string | computed | The RFC 4648 base64 encoded SHA-256 hash of the customer-sup…

  }

  source_snapshot_encryption_key { # list [0..1]
    kms_key_self_link       = ""     # string | optional | The self link of the encryption key used to encrypt the disk…
    kms_key_service_account = ""     # string | optional | The service account used for the encryption request for the …
    raw_key                 = ""     # string | optional | Specifies a 256-bit customer-supplied encryption key, encode…

    # sha256                  = ""     # string | computed | The RFC 4648 base64 encoded SHA-256 hash of the customer-sup…

  }

  timeouts { # single
    create = ""     # string | optional
    delete = ""     # string | optional
    update = ""     # string | optional

  }

}

