# ┌──────────────────────────────────────────────────────────────┐
# │  resource: google_cloud_run_domain_mapping                     │
# └──────────────────────────────────────────────────────────────┘
resource "google_cloud_run_domain_mapping" "this" {

  location = ""     # string | required | The location of the cloud run instance. eg us-central1
  name     = ""     # string | required | Name should be a [verified](https://support.google.com/webma…
  id       = ""     # string | optional+computed
  project  = ""     # string | optional+computed

  # status = [  # list(object)
  #   {
  #     conditions = [  # list(object)
  #       {
  #         message = ""
  #         reason = ""
  #         status = ""
  #         type = ""
  #       }
  #     ]
  #     mapped_route_name = ""
  #     observed_generation = 0
  #     resource_records = [  # list(object)
  #       {
  #         name = ""
  #         rrdata = ""
  #         type = ""
  #       }
  #     ]
  #   }
  # ]

  metadata { # list [0..1]
    namespace             = ""     # string | required | In Cloud Run the namespace must be equal to either the proje…
    annotations           = {}     # map(string) | optional | Annotations is a key value map stored with a resource that m…
    labels                = {}     # map(string) | optional | Map of string keys and values that can be used to organize a…

    # effective_annotations = {}     # map(string) | computed | All of annotations (key/value pairs) present on the resource…
    # effective_labels      = {}     # map(string) | computed | All of labels (key/value pairs) present on the resource in G…
    # generation            = 0      # number | computed | A sequence number representing a specific generation of the …
    # resource_version      = ""     # string | computed | An opaque value that represents the internal version of this…
    # self_link             = ""     # string | computed | SelfLink is a URL representing this object.
    # terraform_labels      = {}     # map(string) | computed | The combination of labels configured directly on the resourc…
    # uid                   = ""     # string | computed | UID is a unique id generated by the server on successful cre…

  }

  spec { # list [1..1]
    route_name       = ""     # string | required | The name of the Cloud Run Service that this DomainMapping ap…
    certificate_mode = ""     # string | optional | The mode of the certificate. Default value: "AUTOMATIC" Poss…
    force_override   = false  # bool | optional | If set, the mapping will override any mapping set before thi…

  }

  timeouts { # single
    create = ""     # string | optional
    delete = ""     # string | optional

  }

}

