# ┌──────────────────────────────────────────────────────────────┐
# │  resource: google_active_directory_domain                      │
# └──────────────────────────────────────────────────────────────┘
resource "google_active_directory_domain" "this" {

  domain_name         = ""     # string | required | The fully qualified domain name. e.g. mydomain.myorganizatio…
  locations           = []     # list(string) | required | Locations where domain needs to be provisioned. [regions][co…
  reserved_ip_range   = ""     # string | required | The CIDR range of internal addresses that are reserved for t…
  admin               = ""     # string | optional | The name of delegated administrator account used to perform …
  authorized_networks = []     # set(string) | optional | The full names of the Google Compute Engine networks the dom…
  id                  = ""     # string | optional+computed
  labels              = {}     # map(string) | optional | Resource labels that can contain user-provided metadata  **N…
  project             = ""     # string | optional+computed

  # effective_labels    = {}     # map(string) | computed | All of labels (key/value pairs) present on the resource in G…
  # fqdn                = ""     # string | computed | The fully-qualified domain name of the exposed domain used b…
  # name                = ""     # string | computed | The unique name of the domain using the format: 'projects/{p…
  # terraform_labels    = {}     # map(string) | computed | The combination of labels configured directly on the resourc…

  timeouts { # single
    create = ""     # string | optional
    delete = ""     # string | optional
    update = ""     # string | optional

  }

}

