# ┌──────────────────────────────────────────────────────────────┐
# │  resource: google_compute_interconnect_attachment              │
# └──────────────────────────────────────────────────────────────┘
resource "google_compute_interconnect_attachment" "this" {

  name                         = ""     # string | required | Name of the resource. Provided by the client when the resour…
  router                       = ""     # string | required | URL of the cloud router to be used for dynamic routing. This…
  admin_enabled                = false  # bool | optional | Whether the VLAN attachment is enabled or disabled.  When us…
  bandwidth                    = ""     # string | optional+computed | Provisioned bandwidth capacity for the interconnect attachme…
  candidate_subnets            = []     # list(string) | optional | Up to 16 candidate prefixes that can be used to restrict the…
  description                  = ""     # string | optional | An optional description of this resource.
  edge_availability_domain     = ""     # string | optional+computed | Desired availability domain for the attachment. Only availab…
  encryption                   = ""     # string | optional | Indicates the user-supplied encryption option of this interc…
  id                           = ""     # string | optional+computed
  interconnect                 = ""     # string | optional | URL of the underlying Interconnect object that this attachme…
  ipsec_internal_addresses     = []     # list(string) | optional | URL of addresses that have been reserved for the interconnec…
  mtu                          = ""     # string | optional+computed | Maximum Transmission Unit (MTU), in bytes, of packets passin…
  project                      = ""     # string | optional+computed
  region                       = ""     # string | optional+computed | Region where the regional interconnect attachment resides.
  stack_type                   = ""     # string | optional+computed | The stack type for this interconnect attachment to identify …
  subnet_length                = 0      # number | optional | Length of the IPv4 subnet mask. Allowed values: 29 (default)…
  type                         = ""     # string | optional+computed | The type of InterconnectAttachment you wish to create. Defau…
  vlan_tag8021q                = 0      # number | optional+computed | The IEEE 802.1Q VLAN tag for this attachment, in the range 2…

  # cloud_router_ip_address      = ""     # string | computed | IPv4 address + prefix length to be configured on Cloud Route…
  # cloud_router_ipv6_address    = ""     # string | computed | IPv6 address + prefix length to be configured on Cloud Route…
  # creation_timestamp           = ""     # string | computed | Creation timestamp in RFC3339 text format.
  # customer_router_ip_address   = ""     # string | computed | IPv4 address + prefix length to be configured on the custome…
  # customer_router_ipv6_address = ""     # string | computed | IPv6 address + prefix length to be configured on the custome…
  # google_reference_id          = ""     # string | computed | Google reference ID, to be used when raising support tickets…
  # pairing_key                  = ""     # string | computed | [Output only for type PARTNER. Not present for DEDICATED]. T…
  # partner_asn                  = ""     # string | computed | [Output only for type PARTNER. Not present for DEDICATED]. O…
  # private_interconnect_info = [  # list(object)
  #   {
  #     tag8021q = 0
  #   }
  # ]
  # self_link                    = ""     # string | computed
  # state                        = ""     # string | computed | [Output Only] The current state of this attachment's functio…

  timeouts { # single
    create = ""     # string | optional
    delete = ""     # string | optional
    update = ""     # string | optional

  }

}

