# ┌──────────────────────────────────────────────────────────────┐
# │  resource: google_cloud_run_service                            │
# └──────────────────────────────────────────────────────────────┘
resource "google_cloud_run_service" "this" {

  location                   = ""     # string | required | The location of the cloud run instance. eg us-central1
  name                       = ""     # string | required | Name must be unique within a Google Cloud project and region…
  autogenerate_revision_name = false  # bool | optional | If set to 'true', the revision name (template.metadata.name)…
  id                         = ""     # string | optional+computed
  project                    = ""     # string | optional+computed

  # status = [  # list(object)
  #   {
  #     conditions = [  # list(object)
  #       {
  #         message = ""
  #         reason = ""
  #         status = ""
  #         type = ""
  #       }
  #     ]
  #     latest_created_revision_name = ""
  #     latest_ready_revision_name = ""
  #     observed_generation = 0
  #     traffic = [  # list(object)
  #       {
  #         latest_revision = false
  #         percent = 0
  #         revision_name = ""
  #         tag = ""
  #         url = ""
  #       }
  #     ]
  #     url = ""
  #   }
  # ]

  metadata { # list [0..1]
    annotations           = {}     # map(string) | optional | Annotations is a key value map stored with a resource that m…
    labels                = {}     # map(string) | optional | Map of string keys and values that can be used to organize a…
    namespace             = ""     # string | optional+computed | In Cloud Run the namespace must be equal to either the proje…

    # effective_annotations = {}     # map(string) | computed | All of annotations (key/value pairs) present on the resource…
    # effective_labels      = {}     # map(string) | computed | All of labels (key/value pairs) present on the resource in G…
    # generation            = 0      # number | computed | A sequence number representing a specific generation of the …
    # resource_version      = ""     # string | computed | An opaque value that represents the internal version of this…
    # self_link             = ""     # string | computed | SelfLink is a URL representing this object.
    # terraform_labels      = {}     # map(string) | computed | The combination of labels configured directly on the resourc…
    # uid                   = ""     # string | computed | UID is a unique id generated by the server on successful cre…

  }

  template { # list [0..1]

    metadata { # list [0..1]
      annotations      = {}     # map(string) | optional+computed | Annotations is a key value map stored with a resource that m…
      labels           = {}     # map(string) | optional+computed | Map of string keys and values that can be used to organize a…
      name             = ""     # string | optional+computed | Name must be unique within a Google Cloud project and region…
      namespace        = ""     # string | optional+computed | In Cloud Run the namespace must be equal to either the proje…

      # generation       = 0      # number | computed | A sequence number representing a specific generation of the …
      # resource_version = ""     # string | computed | An opaque value that represents the internal version of this…
      # self_link        = ""     # string | computed | SelfLink is a URL representing this object.
      # uid              = ""     # string | computed | UID is a unique id generated by the server on successful cre…

    }

    spec { # list [0..1]
      container_concurrency = 0      # number | optional+computed | ContainerConcurrency specifies the maximum allowed in-flight…
      service_account_name  = ""     # string | optional+computed | Email address of the IAM service account associated with the…
      timeout_seconds       = 0      # number | optional+computed | TimeoutSeconds holds the max duration the instance is allowe…

      # serving_state         = ""     # string | computed+DEPRECATED | ServingState holds a value describing the state the resource…

      containers { # list
        image       = ""     # string | required | Docker image name. This is most often a reference to a conta…
        args        = []     # list(string) | optional | Arguments to the entrypoint. The docker image's CMD is used …
        command     = []     # list(string) | optional | Entrypoint array. Not executed within a shell. The docker im…
        name        = ""     # string | optional+computed | Name of the container
        working_dir = ""     # string | optional+DEPRECATED | Container's working directory. If not specified, the contain…

        env { # set
          name  = ""     # string | optional | Name of the environment variable.
          value = ""     # string | optional | Defaults to "".

          value_from { # list [0..1]

            secret_key_ref { # list [1..1]
              key  = ""     # string | required | A Cloud Secret Manager secret version. Must be 'latest' for …
              name = ""     # string | required | The name of the secret in Cloud Secret Manager. By default, …

            }

          }

        }

        env_from { # list DEPRECATED
          prefix = ""     # string | optional | An optional identifier to prepend to each key in the ConfigM…

          config_map_ref { # list [0..1]
            optional = false  # bool | optional | Specify whether the ConfigMap must be defined

            local_object_reference { # list [0..1]
              name = ""     # string | required | Name of the referent.

            }

          }

          secret_ref { # list [0..1]
            optional = false  # bool | optional | Specify whether the Secret must be defined

            local_object_reference { # list [0..1]
              name = ""     # string | required | Name of the referent.

            }

          }

        }

        liveness_probe { # list [0..1]
          failure_threshold     = 0      # number | optional | Minimum consecutive failures for the probe to be considered …
          initial_delay_seconds = 0      # number | optional | Number of seconds after the container has started before the…
          period_seconds        = 0      # number | optional | How often (in seconds) to perform the probe. Default to 10 s…
          timeout_seconds       = 0      # number | optional | Number of seconds after which the probe times out. Defaults …

          grpc { # list [0..1]
            port    = 0      # number | optional+computed | Port number to access on the container. Number must be in th…
            service = ""     # string | optional | The name of the service to place in the gRPC HealthCheckRequ…

          }

          http_get { # list [0..1]
            path = ""     # string | optional | Path to access on the HTTP server. If set, it should not be …
            port = 0      # number | optional+computed | Port number to access on the container. Number must be in th…

            http_headers { # list
              name  = ""     # string | required | The header field name.
              value = ""     # string | optional | The header field value.

            }

          }

        }

        ports { # list
          container_port = 0      # number | optional | Port number the container listens on. This must be a valid p…
          name           = ""     # string | optional+computed | If specified, used to specify which protocol to use. Allowed…
          protocol       = ""     # string | optional | Protocol for port. Must be "TCP". Defaults to "TCP".

        }

        resources { # list [0..1]
          limits   = {}     # map(string) | optional+computed | Limits describes the maximum amount of compute resources all…
          requests = {}     # map(string) | optional | Requests describes the minimum amount of compute resources r…

        }

        startup_probe { # list [0..1]
          failure_threshold     = 0      # number | optional | Minimum consecutive failures for the probe to be considered …
          initial_delay_seconds = 0      # number | optional | Number of seconds after the container has started before the…
          period_seconds        = 0      # number | optional | How often (in seconds) to perform the probe. Default to 10 s…
          timeout_seconds       = 0      # number | optional | Number of seconds after which the probe times out. Defaults …

          grpc { # list [0..1]
            port    = 0      # number | optional+computed | Port number to access on the container. Number must be in th…
            service = ""     # string | optional | The name of the service to place in the gRPC HealthCheckRequ…

          }

          http_get { # list [0..1]
            path = ""     # string | optional | Path to access on the HTTP server. If set, it should not be …
            port = 0      # number | optional+computed | Port number to access on the container. Number must be in th…

            http_headers { # list
              name  = ""     # string | required | The header field name.
              value = ""     # string | optional | The header field value.

            }

          }

          tcp_socket { # list [0..1]
            port = 0      # number | optional+computed | Port number to access on the container. Number must be in th…

          }

        }

        volume_mounts { # list
          mount_path = ""     # string | required | Path within the container at which the volume should be moun…
          name       = ""     # string | required | This must match the Name of a Volume.

        }

      }

      volumes { # list
        name = ""     # string | required | Volume's name.

        secret { # list [0..1]
          secret_name  = ""     # string | required | The name of the secret in Cloud Secret Manager. By default, …
          default_mode = 0      # number | optional | Mode bits to use on created files by default. Must be a valu…

          items { # list
            key  = ""     # string | required | The Cloud Secret Manager secret version. Can be 'latest' for…
            path = ""     # string | required | The relative path of the file to map the key to. May not be …
            mode = 0      # number | optional | Mode bits to use on this file, must be a value between 0000 …

          }

        }

      }

    }

  }

  timeouts { # single
    create = ""     # string | optional
    delete = ""     # string | optional
    update = ""     # string | optional

  }

  traffic { # list
    percent         = 0      # number | required | Percent specifies percent of the traffic to this Revision or…
    latest_revision = false  # bool | optional | LatestRevision may be optionally provided to indicate that t…
    revision_name   = ""     # string | optional | RevisionName of a specific revision to which to send this po…
    tag             = ""     # string | optional | Tag is optionally used to expose a dedicated url for referen…

    # url             = ""     # string | computed | URL displays the URL for accessing tagged traffic targets. U…

  }

}

