# ┌──────────────────────────────────────────────────────────────┐
# │  resource: google_netapp_active_directory                      │
# └──────────────────────────────────────────────────────────────┘
resource "google_netapp_active_directory" "this" {

  dns                    = ""     # string | required | Comma separated list of DNS server IP addresses for the Acti…
  domain                 = ""     # string | required | Fully qualified domain name for the Active Directory domain.
  location               = ""     # string | required | Name of the region for the policy to apply to.
  name                   = ""     # string | required | The resource name of the Active Directory pool. Needs to be …
  net_bios_prefix        = ""     # string | required | NetBIOS name prefix of the server to be created. A five-char…
  password               = ""     # string | required+sensitive | Password for specified username. Note - Manual changes done …
  username               = ""     # string | required | Username for the Active Directory account with permissions t…
  administrators         = []     # list(string) | optional | Domain user accounts to be added to the local Administrators…
  aes_encryption         = false  # bool | optional | Enables AES-128 and AES-256 encryption for Kerberos-based co…
  backup_operators       = []     # list(string) | optional | Domain user/group accounts to be added to the Backup Operato…
  description            = ""     # string | optional | An optional description of this resource.
  encrypt_dc_connections = false  # bool | optional | If enabled, traffic between the SMB server to Domain Control…
  id                     = ""     # string | optional+computed
  kdc_hostname           = ""     # string | optional | Hostname of the Active Directory server used as Kerberos Key…
  kdc_ip                 = ""     # string | optional | IP address of the Active Directory server used as Kerberos K…
  labels                 = {}     # map(string) | optional | Labels as key value pairs. Example: '{ "owner": "Bob", "depa…
  ldap_signing           = false  # bool | optional | Specifies whether or not the LDAP traffic needs to be signed…
  nfs_users_with_ldap    = false  # bool | optional | Local UNIX users on clients without valid user information i…
  organizational_unit    = ""     # string | optional+computed | Name of the Organizational Unit where you intend to create t…
  project                = ""     # string | optional+computed
  security_operators     = []     # list(string) | optional | Domain accounts that require elevated privileges such as 'Se…
  site                   = ""     # string | optional | Specifies an Active Directory site to manage domain controll…

  # create_time            = ""     # string | computed | Create time of the active directory. A timestamp in RFC3339 …
  # effective_labels       = {}     # map(string) | computed | All of labels (key/value pairs) present on the resource in G…
  # state                  = ""     # string | computed | The state of the Active Directory policy (not the Active Dir…
  # state_details          = ""     # string | computed | The state details of the Active Directory.
  # terraform_labels       = {}     # map(string) | computed | The combination of labels configured directly on the resourc…

  timeouts { # single
    create = ""     # string | optional
    delete = ""     # string | optional
    update = ""     # string | optional

  }

}

