# ┌──────────────────────────────────────────────────────────────┐
# │  resource: google_compute_region_instance_template             │
# └──────────────────────────────────────────────────────────────┘
resource "google_compute_region_instance_template" "this" {

  machine_type            = ""     # string | required | The machine type to create. To create a machine with a custo…
  can_ip_forward          = false  # bool | optional | Whether to allow sending and receiving of packets with non-m…
  description             = ""     # string | optional | A brief description of this resource.
  id                      = ""     # string | optional+computed
  instance_description    = ""     # string | optional | A description of the instance.
  labels                  = {}     # map(string) | optional | A set of key/value label pairs to assign to instances create…
  metadata                = {}     # map(string) | optional | Metadata key/value pairs to make available from within insta…
  metadata_startup_script = ""     # string | optional | An alternative to using the startup-script metadata key, mos…
  min_cpu_platform        = ""     # string | optional | Specifies a minimum CPU platform. Applicable values are the …
  name                    = ""     # string | optional+computed | The name of the instance template. If you leave this blank, …
  name_prefix             = ""     # string | optional+computed | Creates a unique name beginning with the specified prefix. C…
  project                 = ""     # string | optional+computed | The ID of the project in which the resource belongs. If it i…
  region                  = ""     # string | optional+computed | The region in which the instance template is located. If it …
  resource_manager_tags   = {}     # map(string) | optional | A map of resource manager tags. 				Resource manager tag key…
  resource_policies       = []     # list(string) | optional | A list of self_links of resource policies to attach to the i…
  tags                    = []     # set(string) | optional | Tags to attach to the instance.

  # effective_labels        = {}     # map(string) | computed | All of labels (key/value pairs) present on the resource in G…
  # metadata_fingerprint    = ""     # string | computed | The unique fingerprint of the metadata.
  # self_link               = ""     # string | computed | The URI of the created resource.
  # tags_fingerprint        = ""     # string | computed | The unique fingerprint of the tags.
  # terraform_labels        = {}     # map(string) | computed | The combination of labels configured directly on the resourc…

  advanced_machine_features { # list [0..1]
    enable_nested_virtualization = false  # bool | optional | Whether to enable nested virtualization or not.
    threads_per_core             = 0      # number | optional | The number of threads per physical core. To disable simultan…
    visible_core_count           = 0      # number | optional | The number of physical cores to expose to an instance. Multi…

  }

  confidential_instance_config { # list [0..1]
    confidential_instance_type  = ""     # string | optional |  								Specifies which confidential computing technology t…
    enable_confidential_compute = false  # bool | optional | Defines whether the instance should have confidential comput…

  }

  disk { # list [1..*]
    auto_delete           = false  # bool | optional | Whether or not the disk should be auto-deleted. This default…
    boot                  = false  # bool | optional+computed | Indicates that this is a boot disk.
    device_name           = ""     # string | optional+computed | A unique device name that is reflected into the /dev/ tree o…
    disk_name             = ""     # string | optional | Name of the disk. When not provided, this defaults to the na…
    disk_size_gb          = 0      # number | optional+computed | The size of the image in gigabytes. If not specified, it wil…
    disk_type             = ""     # string | optional+computed | The Google Compute Engine disk type. Such as "pd-ssd", "loca…
    interface             = ""     # string | optional+computed | Specifies the disk interface to use for attaching this disk.
    labels                = {}     # map(string) | optional | A set of key/value label pairs to assign to disks,
    mode                  = ""     # string | optional+computed | The mode in which to attach this disk, either READ_WRITE or …
    provisioned_iops      = 0      # number | optional+computed | Indicates how many IOPS to provision for the disk. This sets…
    resource_manager_tags = {}     # map(string) | optional | A map of resource manager tags. Resource manager tag keys an…
    resource_policies     = []     # list(string) | optional | A list (short name or id) of resource policies to attach to …
    source                = ""     # string | optional | The name (not self_link) of the disk (such as those managed …
    source_image          = ""     # string | optional+computed | The image from which to initialize this disk. This can be on…
    source_snapshot       = ""     # string | optional | The source snapshot to create this disk. When creating a new…
    type                  = ""     # string | optional+computed | The type of Google Compute Engine disk, can be either "SCRAT…

    disk_encryption_key { # list [0..1]
      kms_key_self_link = ""     # string | required | The self link of the encryption key that is stored in Google…

    }

    source_image_encryption_key { # list [0..1]
      kms_key_self_link       = ""     # string | required | The self link of the encryption key that is stored in Google…
      kms_key_service_account = ""     # string | optional | The service account being used for the encryption request fo…

    }

    source_snapshot_encryption_key { # list [0..1]
      kms_key_self_link       = ""     # string | required | The self link of the encryption key that is stored in Google…
      kms_key_service_account = ""     # string | optional | The service account being used for the encryption request fo…

    }

  }

  guest_accelerator { # list
    count = 0      # number | required | The number of the guest accelerator cards exposed to this in…
    type  = ""     # string | required | The accelerator type resource to expose to this instance. E.…

  }

  network_interface { # list
    internal_ipv6_prefix_length = 0      # number | optional+computed | The prefix length of the primary internal IPv6 range.
    ipv6_address                = ""     # string | optional+computed | An IPv6 internal network address for this network interface.…
    network                     = ""     # string | optional+computed | The name or self_link of the network to attach this interfac…
    network_ip                  = ""     # string | optional | The private IP address to assign to the instance. If empty, …
    nic_type                    = ""     # string | optional | The type of vNIC to be used on this interface. Possible valu…
    queue_count                 = 0      # number | optional | The networking queue count that's specified by users for the…
    stack_type                  = ""     # string | optional+computed | The stack type for this network interface to identify whethe…
    subnetwork                  = ""     # string | optional+computed | The name of the subnetwork to attach this interface to. The …
    subnetwork_project          = ""     # string | optional+computed | The ID of the project in which the subnetwork belongs. If it…

    # ipv6_access_type            = ""     # string | computed | One of EXTERNAL, INTERNAL to indicate whether the IP can be …
    # name                        = ""     # string | computed | The name of the network_interface.

    access_config { # list
      nat_ip                 = ""     # string | optional+computed | The IP address that will be 1:1 mapped to the instance's net…
      network_tier           = ""     # string | optional+computed | The networking tier used for configuring this instance templ…

      # public_ptr_domain_name = ""     # string | computed | The DNS domain name for the public PTR record.The DNS domain…

    }

    alias_ip_range { # list
      ip_cidr_range         = ""     # string | required | The IP CIDR range represented by this alias IP range. This I…
      subnetwork_range_name = ""     # string | optional | The subnetwork secondary range name specifying the secondary…

    }

    ipv6_access_config { # list
      network_tier                = ""     # string | required | The service-level to be provided for IPv6 traffic when the s…

      # external_ipv6               = ""     # string | computed | The first IPv6 address of the external IPv6 range associated…
      # external_ipv6_prefix_length = ""     # string | computed | The prefix length of the external IPv6 range.
      # name                        = ""     # string | computed | The name of this access configuration.
      # public_ptr_domain_name      = ""     # string | computed | The domain name to be used when creating DNSv6 records for t…

    }

  }

  network_performance_config { # list [0..1]
    total_egress_bandwidth_tier = ""     # string | required | The egress bandwidth tier to enable. Possible values:TIER_1,…

  }

  reservation_affinity { # list [0..1]
    type = ""     # string | required | The type of reservation from which this instance can consume…

    specific_reservation { # list [0..1]
      key    = ""     # string | required | Corresponds to the label key of a reservation resource. To t…
      values = []     # list(string) | required | Corresponds to the label values of a reservation resource.

    }

  }

  scheduling { # list [0..1]
    automatic_restart           = false  # bool | optional | Specifies whether the instance should be automatically resta…
    instance_termination_action = ""     # string | optional | Specifies the action GCE should take when SPOT VM is preempt…
    min_node_cpus               = 0      # number | optional | Minimum number of cpus for the instance.
    on_host_maintenance         = ""     # string | optional+computed | Defines the maintenance behavior for this instance.
    preemptible                 = false  # bool | optional | Allows instance to be preempted. This defaults to false.
    provisioning_model          = ""     # string | optional+computed | Whether the instance is spot. If this is set as SPOT.

    local_ssd_recovery_timeout { # list
      seconds = 0      # number | required | Span of time at a resolution of a second. Must be from 0 to …
      nanos   = 0      # number | optional | Span of time that's a fraction of a second at nanosecond res…

    }

    max_run_duration { # list [0..1]
      seconds = 0      # number | required | Span of time at a resolution of a second. Must be from 0 to …
      nanos   = 0      # number | optional | Span of time that's a fraction of a second at nanosecond res…

    }

    node_affinities { # set
      key      = ""     # string | required
      operator = ""     # string | required
      values   = []     # set(string) | required

    }

    on_instance_stop_action { # list [0..1]
      discard_local_ssd = false  # bool | optional | If true, the contents of any attached Local SSD disks will b…

    }

  }

  service_account { # list [0..1]
    scopes = []     # set(string) | required | A list of service scopes. Both OAuth2 URLs and gcloud short …
    email  = ""     # string | optional+computed | The service account e-mail address. If not given, the defaul…

  }

  shielded_instance_config { # list [0..1]
    enable_integrity_monitoring = false  # bool | optional | Compare the most recent boot measurements to the integrity p…
    enable_secure_boot          = false  # bool | optional | Verify the digital signature of all boot components, and hal…
    enable_vtpm                 = false  # bool | optional | Use a virtualized trusted platform module, which is a specia…

  }

  timeouts { # single
    create = ""     # string | optional
    delete = ""     # string | optional

  }

}

