# ┌──────────────────────────────────────────────────────────────┐
# │  resource: google_redis_instance                               │
# └──────────────────────────────────────────────────────────────┘
resource "google_redis_instance" "this" {

  memory_size_gb           = 0      # number | required | Redis memory size in GiB.
  name                     = ""     # string | required | The ID of the instance or a fully qualified identifier for t…
  alternative_location_id  = ""     # string | optional+computed | Only applicable to STANDARD_HA tier which protects the insta…
  auth_enabled             = false  # bool | optional | Optional. Indicates whether OSS Redis AUTH is enabled for th…
  authorized_network       = ""     # string | optional+computed | The full name of the Google Compute Engine network to which …
  connect_mode             = ""     # string | optional | The connection mode of the Redis instance. Default value: "D…
  customer_managed_key     = ""     # string | optional | Optional. The KMS key reference that you want to use to encr…
  display_name             = ""     # string | optional | An arbitrary and optional user-provided name for the instanc…
  id                       = ""     # string | optional+computed
  labels                   = {}     # map(string) | optional | Resource labels to represent user provided metadata.  **Note…
  location_id              = ""     # string | optional+computed | The zone where the instance will be provisioned. If not prov…
  maintenance_version      = ""     # string | optional+computed | The self service update maintenance version.
  project                  = ""     # string | optional+computed
  read_replicas_mode       = ""     # string | optional+computed | Optional. Read replica mode. Can only be specified when tryi…
  redis_configs            = {}     # map(string) | optional | Redis configuration parameters, according to http://redis.io…
  redis_version            = ""     # string | optional+computed | The version of Redis software. If not provided, latest suppo…
  region                   = ""     # string | optional+computed | The name of the Redis region of the instance.
  replica_count            = 0      # number | optional+computed | Optional. The number of replica nodes. The valid range for t…
  reserved_ip_range        = ""     # string | optional+computed | The CIDR range of internal addresses that are reserved for t…
  secondary_ip_range       = ""     # string | optional+computed | Optional. Additional IP range for node placement. Required w…
  tier                     = ""     # string | optional | The service tier of the instance. Must be one of these value…
  transit_encryption_mode  = ""     # string | optional | The TLS mode of the Redis instance, If not provided, TLS is …

  # auth_string              = ""     # string | computed+sensitive | AUTH String set on the instance. This field will only be pop…
  # create_time              = ""     # string | computed | The time the instance was created in RFC3339 UTC "Zulu" form…
  # current_location_id      = ""     # string | computed | The current zone where the Redis endpoint is placed. For Bas…
  # effective_labels         = {}     # map(string) | computed | All of labels (key/value pairs) present on the resource in G…
  # host                     = ""     # string | computed | Hostname or IP address of the exposed Redis endpoint used by…
  # maintenance_schedule = [  # list(object)
  #   {
  #     end_time = ""
  #     schedule_deadline_time = ""
  #     start_time = ""
  #   }
  # ]
  # nodes = [  # list(object)
  #   {
  #     id = ""
  #     zone = ""
  #   }
  # ]
  # persistence_iam_identity = ""     # string | computed | Output only. Cloud IAM identity used by import / export oper…
  # port                     = 0      # number | computed | The port number of the exposed Redis endpoint.
  # read_endpoint            = ""     # string | computed | Output only. Hostname or IP address of the exposed readonly …
  # read_endpoint_port       = 0      # number | computed | Output only. The port number of the exposed readonly redis e…
  # server_ca_certs = [  # list(object)
  #   {
  #     cert = ""
  #     create_time = ""
  #     expire_time = ""
  #     serial_number = ""
  #     sha1_fingerprint = ""
  #   }
  # ]
  # terraform_labels         = {}     # map(string) | computed | The combination of labels configured directly on the resourc…

  maintenance_policy { # list [0..1]
    description = ""     # string | optional | Optional. Description of what this policy is for. Create/Upd…

    # create_time = ""     # string | computed | Output only. The time when the policy was created. A timesta…
    # update_time = ""     # string | computed | Output only. The time when the policy was last updated. A ti…

    weekly_maintenance_window { # list
      day      = ""     # string | required | Required. The day of week that maintenance updates occur.  -…

      # duration = ""     # string | computed | Output only. Duration of the maintenance window. The current…

      start_time { # list [1..1]
        hours   = 0      # number | optional | Hours of day in 24 hour format. Should be from 0 to 23. An A…
        minutes = 0      # number | optional | Minutes of hour of day. Must be from 0 to 59.
        nanos   = 0      # number | optional | Fractions of seconds in nanoseconds. Must be from 0 to 999,9…
        seconds = 0      # number | optional | Seconds of minutes of the time. Must normally be from 0 to 5…

      }

    }

  }

  persistence_config { # list [0..1]
    persistence_mode        = ""     # string | optional+computed | Optional. Controls whether Persistence features are enabled.…
    rdb_snapshot_period     = ""     # string | optional | Optional. Available snapshot periods for scheduling.  - ONE_…
    rdb_snapshot_start_time = ""     # string | optional+computed | Optional. Date and time that the first snapshot was/will be …

    # rdb_next_snapshot_time  = ""     # string | computed | Output only. The next time that a snapshot attempt is schedu…

  }

  timeouts { # single
    create = ""     # string | optional
    delete = ""     # string | optional
    update = ""     # string | optional

  }

}

