# ┌──────────────────────────────────────────────────────────────┐
# │  resource: google_clouddomains_registration                    │
# └──────────────────────────────────────────────────────────────┘
resource "google_clouddomains_registration" "this" {

  domain_name             = ""     # string | required | Required. The domain name. Unicode domain names must be expr…
  location                = ""     # string | required | The location for the resource
  contact_notices         = []     # list(string) | optional | The list of contact notices that the caller acknowledges. Po…
  domain_notices          = []     # list(string) | optional | The list of domain notices that you acknowledge. Possible va…
  id                      = ""     # string | optional+computed
  labels                  = {}     # map(string) | optional | Set of labels associated with the Registration.  **Note**: T…
  project                 = ""     # string | optional+computed

  # create_time             = ""     # string | computed | Output only. Time at which the automation was created.
  # effective_labels        = {}     # map(string) | computed | All of labels (key/value pairs) present on the resource in G…
  # expire_time             = ""     # string | computed | Output only. Time at which the automation was updated.
  # issues                  = []     # list(string) | computed | Output only. The set of issues with the Registration that re…
  # name                    = ""     # string | computed | Output only. Name of the Registration resource, in the forma…
  # register_failure_reason = ""     # string | computed | Output only. The reason the domain registration failed. Only…
  # state                   = ""     # string | computed | Output only. The current state of the Registration.
  # supported_privacy       = []     # list(string) | computed | Output only. Set of options for the contactSettings.privacy …
  # terraform_labels        = {}     # map(string) | computed | The combination of labels configured directly on the resourc…

  contact_settings { # list [1..1]
    privacy = ""     # string | required | Required. Privacy setting for the contacts associated with t…

    admin_contact { # list [1..1]
      email        = ""     # string | required | Required. Email address of the contact.
      phone_number = ""     # string | required | Required. Phone number of the contact in international forma…
      fax_number   = ""     # string | optional | Fax number of the contact in international format. For examp…

      postal_address { # list [1..1]
        region_code         = ""     # string | required | Required. CLDR region code of the country/region of the addr…
        address_lines       = []     # list(string) | optional | Unstructured address lines describing the lower levels of an…
        administrative_area = ""     # string | optional | Highest administrative subdivision which is used for postal …
        locality            = ""     # string | optional | Generally refers to the city/town portion of the address. Ex…
        organization        = ""     # string | optional | The name of the organization at the address.
        postal_code         = ""     # string | optional | Postal code of the address. Not all countries use or require…
        recipients          = []     # list(string) | optional | The recipient at the address. This field may, under certain …

      }

    }

    registrant_contact { # list [1..1]
      email        = ""     # string | required | Required. Email address of the contact.
      phone_number = ""     # string | required | Required. Phone number of the contact in international forma…
      fax_number   = ""     # string | optional | Fax number of the contact in international format. For examp…

      postal_address { # list [1..1]
        region_code         = ""     # string | required | Required. CLDR region code of the country/region of the addr…
        address_lines       = []     # list(string) | optional | Unstructured address lines describing the lower levels of an…
        administrative_area = ""     # string | optional | Highest administrative subdivision which is used for postal …
        locality            = ""     # string | optional | Generally refers to the city/town portion of the address. Ex…
        organization        = ""     # string | optional | The name of the organization at the address.
        postal_code         = ""     # string | optional | Postal code of the address. Not all countries use or require…
        recipients          = []     # list(string) | optional | The recipient at the address. This field may, under certain …

      }

    }

    technical_contact { # list [1..1]
      email        = ""     # string | required | Required. Email address of the contact.
      phone_number = ""     # string | required | Required. Phone number of the contact in international forma…
      fax_number   = ""     # string | optional | Fax number of the contact in international format. For examp…

      postal_address { # list [1..1]
        region_code         = ""     # string | required | Required. CLDR region code of the country/region of the addr…
        address_lines       = []     # list(string) | optional | Unstructured address lines describing the lower levels of an…
        administrative_area = ""     # string | optional | Highest administrative subdivision which is used for postal …
        locality            = ""     # string | optional | Generally refers to the city/town portion of the address. Ex…
        organization        = ""     # string | optional | The name of the organization at the address.
        postal_code         = ""     # string | optional | Postal code of the address. Not all countries use or require…
        recipients          = []     # list(string) | optional | The recipient at the address. This field may, under certain …

      }

    }

  }

  dns_settings { # list [0..1]

    custom_dns { # list [0..1]
      name_servers = []     # list(string) | required | Required. A list of name servers that store the DNS zone for…

      ds_records { # list
        algorithm   = ""     # string | optional | The algorithm used to generate the referenced DNSKEY.
        digest      = ""     # string | optional | The digest generated from the referenced DNSKEY.
        digest_type = ""     # string | optional | The hash function used to generate the digest of the referen…
        key_tag     = 0      # number | optional | The key tag of the record. Must be set in range 0 -- 65535.

      }

    }

    glue_records { # list
      host_name      = ""     # string | required | Required. Domain name of the host in Punycode format.
      ipv4_addresses = []     # list(string) | optional | List of IPv4 addresses corresponding to this host in the sta…
      ipv6_addresses = []     # list(string) | optional | List of IPv4 addresses corresponding to this host in the sta…

    }

  }

  management_settings { # list [0..1]
    preferred_renewal_method = ""     # string | optional+computed | The desired renewal method for this Registration. The actual…
    transfer_lock_state      = ""     # string | optional+computed | Controls whether the domain can be transferred to another re…

    # renewal_method           = ""     # string | computed | Output only. The actual renewal method for this Registration…

  }

  timeouts { # single
    create = ""     # string | optional
    delete = ""     # string | optional
    update = ""     # string | optional

  }

  yearly_price { # list [1..1]
    currency_code = ""     # string | optional | The three-letter currency code defined in ISO 4217.
    units         = ""     # string | optional | The whole units of the amount. For example if currencyCode i…

  }

}

