# ┌──────────────────────────────────────────────────────────────┐
# │  resource: google_netapp_backup                                │
# └──────────────────────────────────────────────────────────────┘
resource "google_netapp_backup" "this" {

  location            = ""     # string | required | Location of the backup.
  name                = ""     # string | required | The resource name of the backup. Needs to be unique per loca…
  vault_name          = ""     # string | required | Name of the backup vault to store the backup in.
  description         = ""     # string | optional | A description of the backup with 2048 characters or less. Re…
  id                  = ""     # string | optional+computed
  labels              = {}     # map(string) | optional | Labels as key value pairs. Example: '{ "owner": "Bob", "depa…
  project             = ""     # string | optional+computed
  source_snapshot     = ""     # string | optional | If specified, backup will be created from the given snapshot…
  source_volume       = ""     # string | optional | ID of volumes this backup belongs to. Format: 'projects/{{pr…

  # backup_type         = ""     # string | computed | Type of backup, manually created or created by a backup poli…
  # chain_storage_bytes = ""     # string | computed | Backups of a volume build incrementally on top of each other…
  # create_time         = ""     # string | computed | Create time of the backup. A timestamp in RFC3339 UTC "Zulu"…
  # effective_labels    = {}     # map(string) | computed | All of labels (key/value pairs) present on the resource in G…
  # state               = ""     # string | computed | The state of the Backup Vault. Possible Values : [STATE_UNSP…
  # terraform_labels    = {}     # map(string) | computed | The combination of labels configured directly on the resourc…
  # volume_usage_bytes  = ""     # string | computed | Size of the file system when the backup was created. When cr…

  timeouts { # single
    create = ""     # string | optional
    delete = ""     # string | optional
    update = ""     # string | optional

  }

}

