# ┌──────────────────────────────────────────────────────────────┐
# │  resource: google_compute_global_forwarding_rule               │
# └──────────────────────────────────────────────────────────────┘
resource "google_compute_global_forwarding_rule" "this" {

  name                  = ""     # string | required | Name of the resource; provided by the client when the resour…
  target                = ""     # string | required | The URL of the target resource to receive the matched traffi…
  description           = ""     # string | optional | An optional description of this resource. Provide this prope…
  id                    = ""     # string | optional+computed
  ip_address            = ""     # string | optional+computed | IP address for which this forwarding rule accepts traffic. W…
  ip_protocol           = ""     # string | optional+computed | The IP protocol to which this rule applies.  For protocol fo…
  ip_version            = ""     # string | optional | The IP Version that will be used by this global forwarding r…
  labels                = {}     # map(string) | optional | Labels to apply to this forwarding rule.  A list of key->val…
  load_balancing_scheme = ""     # string | optional | Specifies the forwarding rule type.  For more information ab…
  network               = ""     # string | optional+computed | This field is not used for external load balancing.  For Int…
  no_automate_dns_zone  = false  # bool | optional | This is used in PSC consumer ForwardingRule to control wheth…
  port_range            = ""     # string | optional | The 'portRange' field has the following limitations: * It re…
  project               = ""     # string | optional+computed
  source_ip_ranges      = []     # list(string) | optional | If not empty, this Forwarding Rule will only forward the tra…
  subnetwork            = ""     # string | optional+computed | This field identifies the subnetwork that the load balanced …

  # base_forwarding_rule  = ""     # string | computed | [Output Only] The URL for the corresponding base Forwarding …
  # effective_labels      = {}     # map(string) | computed | All of labels (key/value pairs) present on the resource in G…
  # label_fingerprint     = ""     # string | computed | The fingerprint used for optimistic locking of this resource…
  # psc_connection_id     = ""     # string | computed | The PSC connection id of the PSC Forwarding Rule.
  # psc_connection_status = ""     # string | computed | The PSC connection status of the PSC Forwarding Rule. Possib…
  # self_link             = ""     # string | computed
  # terraform_labels      = {}     # map(string) | computed | The combination of labels configured directly on the resourc…

  metadata_filters { # list
    filter_match_criteria = ""     # string | required | Specifies how individual filterLabel matches within the list…

    filter_labels { # list [1..64]
      name  = ""     # string | required | Name of the metadata label. The length must be between 1 and…
      value = ""     # string | required | The value that the label must match. The value has a maximum…

    }

  }

  service_directory_registrations { # list [0..1]
    namespace                = ""     # string | optional+computed | Service Directory namespace to register the forwarding rule …
    service_directory_region = ""     # string | optional | [Optional] Service Directory region to register this global …

  }

  timeouts { # single
    create = ""     # string | optional
    delete = ""     # string | optional
    update = ""     # string | optional

  }

}

