# ┌──────────────────────────────────────────────────────────────┐
# │  resource: google_identity_platform_tenant                     │
# └──────────────────────────────────────────────────────────────┘
resource "google_identity_platform_tenant" "this" {

  display_name             = ""     # string | required | Human friendly display name of the tenant.
  allow_password_signup    = false  # bool | optional | Whether to allow email/password user authentication.
  disable_auth             = false  # bool | optional | Whether authentication is disabled for the tenant. If true, …
  enable_email_link_signin = false  # bool | optional | Whether to enable email link user authentication.
  id                       = ""     # string | optional+computed
  project                  = ""     # string | optional+computed

  # name                     = ""     # string | computed | The name of the tenant that is generated by the server

  timeouts { # single
    create = ""     # string | optional
    delete = ""     # string | optional
    update = ""     # string | optional

  }

}

