# ┌──────────────────────────────────────────────────────────────┐
# │  resource: google_sql_source_representation_instance           │
# └──────────────────────────────────────────────────────────────┘
resource "google_sql_source_representation_instance" "this" {

  database_version   = ""     # string | required | The MySQL version running on your source database server. Po…
  host               = ""     # string | required | The IPv4 address and port for the external server, or the th…
  name               = ""     # string | required | The name of the source representation instance. Use any vali…
  ca_certificate     = ""     # string | optional | The CA certificate on the external server. Include only if S…
  client_certificate = ""     # string | optional | The client certificate on the external server. Required only…
  client_key         = ""     # string | optional | The private key file for the client certificate on the exter…
  dump_file_path     = ""     # string | optional | A file in the bucket that contains the data from the externa…
  id                 = ""     # string | optional+computed
  password           = ""     # string | optional+sensitive | The password for the replication user account.
  port               = 0      # number | optional | The externally accessible port for the source database serve…
  project            = ""     # string | optional+computed
  region             = ""     # string | optional+computed | The Region in which the created instance should reside. If i…
  username           = ""     # string | optional | The replication user account on the external server.

  timeouts { # single
    create = ""     # string | optional
    delete = ""     # string | optional

  }

}

