# ┌──────────────────────────────────────────────────────────────┐
# │  resource: google_netapp_volume_replication                    │
# └──────────────────────────────────────────────────────────────┘
resource "google_netapp_volume_replication" "this" {

  location                  = ""     # string | required | Name of region for this resource. The resource needs to be c…
  name                      = ""     # string | required | The name of the replication. Needs to be unique per location…
  replication_schedule      = ""     # string | required | Specifies the replication interval. Possible values: ["EVERY…
  volume_name               = ""     # string | required | The name of the existing source volume.
  delete_destination_volume = false  # bool | optional | A destination volume is created as part of replication creat…
  description               = ""     # string | optional | An description of this resource.
  force_stopping            = false  # bool | optional | Only replications with mirror_state=MIRRORED can be stopped.…
  id                        = ""     # string | optional+computed
  labels                    = {}     # map(string) | optional | Labels as key value pairs. Example: '{ "owner": "Bob", "depa…
  project                   = ""     # string | optional+computed
  replication_enabled       = false  # bool | optional | Set to false to stop/break the mirror. Stopping the mirror m…
  wait_for_mirror           = false  # bool | optional | Replication resource state is independent of mirror_state. W…

  # create_time               = ""     # string | computed | Create time of the active directory. A timestamp in RFC3339 …
  # destination_volume        = ""     # string | computed | Full resource name of destination volume with format: 'proje…
  # effective_labels          = {}     # map(string) | computed | All of labels (key/value pairs) present on the resource in G…
  # healthy                   = false  # bool | computed | Condition of the relationship. Can be one of the following: …
  # mirror_state              = ""     # string | computed | Indicates the state of the mirror between source and destina…
  # role                      = ""     # string | computed | Reverting a replication can swap source and destination volu…
  # source_volume             = ""     # string | computed | Full resource name of source volume with format: 'projects/{…
  # state                     = ""     # string | computed | Indicates the state of replication resource. State of the mi…
  # state_details             = ""     # string | computed | State details of the replication resource.
  # terraform_labels          = {}     # map(string) | computed | The combination of labels configured directly on the resourc…
  # transfer_stats = [  # list(object)
  #   {
  #     lag_duration = ""
  #     last_transfer_bytes = ""
  #     last_transfer_duration = ""
  #     last_transfer_end_time = ""
  #     last_transfer_error = ""
  #     total_transfer_duration = ""
  #     transfer_bytes = ""
  #     update_time = ""
  #   }
  # ]

  destination_volume_parameters { # list [0..1]
    storage_pool = ""     # string | required | Name of an existing storage pool for the destination volume …
    description  = ""     # string | optional | Description for the destination volume.
    share_name   = ""     # string | optional+computed | Share name for destination volume. If not specified, name of…
    volume_id    = ""     # string | optional+computed | Name for the destination volume to be created. If not specif…

  }

  timeouts { # single
    create = ""     # string | optional
    delete = ""     # string | optional
    update = ""     # string | optional

  }

}

