# ┌──────────────────────────────────────────────────────────────┐
# │  resource: google_monitoring_alert_policy                      │
# └──────────────────────────────────────────────────────────────┘
resource "google_monitoring_alert_policy" "this" {

  combiner              = ""     # string | required | How to combine the results of multiple conditions to determi…
  display_name          = ""     # string | required | A short name or phrase used to identify the policy in dashbo…
  enabled               = false  # bool | optional | Whether or not the policy is enabled. The default is true.
  id                    = ""     # string | optional+computed
  notification_channels = []     # list(string) | optional | Identifies the notification channels to which notifications …
  project               = ""     # string | optional+computed
  severity              = ""     # string | optional | The severity of an alert policy indicates how important inci…
  user_labels           = {}     # map(string) | optional | This field is intended to be used for organizing and identif…

  # creation_record = [  # list(object)
  #   {
  #     mutate_time = ""
  #     mutated_by = ""
  #   }
  # ]
  # name                  = ""     # string | computed | The unique resource name for this policy. Its syntax is: pro…

  alert_strategy { # list [0..1]
    auto_close = ""     # string | optional | If an alert policy that was active has no data for this long…

    notification_channel_strategy { # list
      notification_channel_names = []     # list(string) | optional | The notification channels that these settings apply to. Each…
      renotify_interval          = ""     # string | optional | The frequency at which to send reminder notifications for op…

    }

    notification_rate_limit { # list [0..1]
      period = ""     # string | optional | Not more than one notification per period. A duration in sec…

    }

  }

  conditions { # list [1..*]
    display_name = ""     # string | required | A short name or phrase used to identify the condition in das…

    # name         = ""     # string | computed | The unique resource name for this condition. Its syntax is: …

    condition_absent { # list [0..1]
      duration = ""     # string | required | The amount of time that a time series must fail to report ne…
      filter   = ""     # string | optional | A filter that identifies which time series should be compare…

      aggregations { # list
        alignment_period     = ""     # string | optional | The alignment period for per-time series alignment. If prese…
        cross_series_reducer = ""     # string | optional | The approach to be used to combine time series. Not all redu…
        group_by_fields      = []     # list(string) | optional | The set of fields to preserve when crossSeriesReducer is spe…
        per_series_aligner   = ""     # string | optional | The approach to be used to align individual time series. Not…

      }

      trigger { # list [0..1]
        count   = 0      # number | optional | The absolute number of time series that must fail the predic…
        percent = 0      # number | optional | The percentage of time series that must fail the predicate f…

      }

    }

    condition_matched_log { # list [0..1]
      filter           = ""     # string | required | A logs-based filter.
      label_extractors = {}     # map(string) | optional | A map from a label key to an extractor expression, which is …

    }

    condition_monitoring_query_language { # list [0..1]
      duration                = ""     # string | required | The amount of time that a time series must violate the thres…
      query                   = ""     # string | required | Monitoring Query Language query that outputs a boolean strea…
      evaluation_missing_data = ""     # string | optional | A condition control that determines how metric-threshold con…

      trigger { # list [0..1]
        count   = 0      # number | optional | The absolute number of time series that must fail the predic…
        percent = 0      # number | optional | The percentage of time series that must fail the predicate f…

      }

    }

    condition_prometheus_query_language { # list [0..1]
      query               = ""     # string | required | The PromQL expression to evaluate. Every evaluation cycle th…
      alert_rule          = ""     # string | optional | The alerting rule name of this alert in the corresponding Pr…
      duration            = ""     # string | optional | Alerts are considered firing once their PromQL expression ev…
      evaluation_interval = ""     # string | optional | How often this rule should be evaluated. Must be a positive …
      labels              = {}     # map(string) | optional | Labels to add to or overwrite in the PromQL query result. La…
      rule_group          = ""     # string | optional | The rule group name of this alert in the corresponding Prome…

    }

    condition_threshold { # list [0..1]
      comparison              = ""     # string | required | The comparison to apply between the time series (indicated b…
      duration                = ""     # string | required | The amount of time that a time series must violate the thres…
      denominator_filter      = ""     # string | optional | A filter that identifies a time series that should be used a…
      evaluation_missing_data = ""     # string | optional | A condition control that determines how metric-threshold con…
      filter                  = ""     # string | optional | A filter that identifies which time series should be compare…
      threshold_value         = 0      # number | optional | A value against which to compare the time series.

      aggregations { # list
        alignment_period     = ""     # string | optional | The alignment period for per-time series alignment. If prese…
        cross_series_reducer = ""     # string | optional | The approach to be used to combine time series. Not all redu…
        group_by_fields      = []     # list(string) | optional | The set of fields to preserve when crossSeriesReducer is spe…
        per_series_aligner   = ""     # string | optional | The approach to be used to align individual time series. Not…

      }

      denominator_aggregations { # list
        alignment_period     = ""     # string | optional | The alignment period for per-time series alignment. If prese…
        cross_series_reducer = ""     # string | optional | The approach to be used to combine time series. Not all redu…
        group_by_fields      = []     # list(string) | optional | The set of fields to preserve when crossSeriesReducer is spe…
        per_series_aligner   = ""     # string | optional | The approach to be used to align individual time series. Not…

      }

      forecast_options { # list [0..1]
        forecast_horizon = ""     # string | required | The length of time into the future to forecast whether a tim…

      }

      trigger { # list [0..1]
        count   = 0      # number | optional | The absolute number of time series that must fail the predic…
        percent = 0      # number | optional | The percentage of time series that must fail the predicate f…

      }

    }

  }

  documentation { # list [0..1]
    content   = ""     # string | optional | The text of the documentation, interpreted according to mime…
    mime_type = ""     # string | optional | The format of the content field. Presently, only the value "…
    subject   = ""     # string | optional | The subject line of the notification. The subject line may n…

    links { # list
      display_name = ""     # string | optional | A short display name for the link. The display name must not…
      url          = ""     # string | optional | The url of a webpage. A url can be templatized by using vari…

    }

  }

  timeouts { # single
    create = ""     # string | optional
    delete = ""     # string | optional
    update = ""     # string | optional

  }

}

