# ┌──────────────────────────────────────────────────────────────┐
# │  resource: google_spanner_instance                             │
# └──────────────────────────────────────────────────────────────┘
resource "google_spanner_instance" "this" {

  config                       = ""     # string | required | The name of the instance's configuration (similar but not qu…
  display_name                 = ""     # string | required | The descriptive name for this instance as it appears in UIs.…
  default_backup_schedule_type = ""     # string | optional+computed | Controls the default backup behavior for new databases withi…
  force_destroy                = false  # bool | optional | When deleting a spanner instance, this boolean option will d…
  id                           = ""     # string | optional+computed
  labels                       = {}     # map(string) | optional | An object containing a list of "key": value pairs. Example: …
  name                         = ""     # string | optional+computed | A unique identifier for the instance, which cannot be change…
  num_nodes                    = 0      # number | optional+computed | The number of nodes allocated to this instance. Exactly one …
  processing_units             = 0      # number | optional+computed | The number of processing units allocated to this instance. E…
  project                      = ""     # string | optional+computed

  # effective_labels             = {}     # map(string) | computed | All of labels (key/value pairs) present on the resource in G…
  # state                        = ""     # string | computed | Instance status: 'CREATING' or 'READY'.
  # terraform_labels             = {}     # map(string) | computed | The combination of labels configured directly on the resourc…

  autoscaling_config { # list [0..1]

    autoscaling_limits { # list [0..1]
      max_nodes            = 0      # number | optional | Specifies maximum number of nodes allocated to the instance.…
      max_processing_units = 0      # number | optional | Specifies maximum number of processing units allocated to th…
      min_nodes            = 0      # number | optional | Specifies number of nodes allocated to the instance. If set,…
      min_processing_units = 0      # number | optional | Specifies minimum number of processing units allocated to th…

    }

    autoscaling_targets { # list [0..1]
      high_priority_cpu_utilization_percent = 0      # number | optional | Specifies the target high priority cpu utilization percentag…
      storage_utilization_percent           = 0      # number | optional | Specifies the target storage utilization percentage that the…

    }

  }

  timeouts { # single
    create = ""     # string | optional
    delete = ""     # string | optional
    update = ""     # string | optional

  }

}

