# ┌──────────────────────────────────────────────────────────────┐
# │  resource: google_firestore_database                           │
# └──────────────────────────────────────────────────────────────┘
resource "google_firestore_database" "this" {

  location_id                       = ""     # string | required | The location of the database. Available locations are listed…
  name                              = ""     # string | required | The ID to use for the database, which will become the final …
  type                              = ""     # string | required | The type of the database. See https://cloud.google.com/datas…
  app_engine_integration_mode       = ""     # string | optional+computed | The App Engine integration mode to use for this database. Po…
  concurrency_mode                  = ""     # string | optional+computed | The concurrency control mode to use for this database. Possi…
  delete_protection_state           = ""     # string | optional+computed | State of delete protection for the database. When delete pro…
  deletion_policy                   = ""     # string | optional | Deletion behavior for this database. If the deletion policy …
  id                                = ""     # string | optional+computed
  point_in_time_recovery_enablement = ""     # string | optional | Whether to enable the PITR feature on this database. If 'POI…
  project                           = ""     # string | optional+computed

  # create_time                       = ""     # string | computed | Output only. The timestamp at which this database was create…
  # earliest_version_time             = ""     # string | computed | Output only. The earliest timestamp at which older versions …
  # etag                              = ""     # string | computed | Output only. This checksum is computed by the server based o…
  # key_prefix                        = ""     # string | computed | Output only. The keyPrefix for this database. This keyPrefix…
  # uid                               = ""     # string | computed | Output only. The system-generated UUID4 for this Database.
  # update_time                       = ""     # string | computed | Output only. The timestamp at which this database was most r…
  # version_retention_period          = ""     # string | computed | Output only. The period during which past versions of data a…

  cmek_config { # list [0..1]
    kms_key_name       = ""     # string | required | The resource ID of a Cloud KMS key. If set, the database cre…

    # active_key_version = []     # list(string) | computed | Currently in-use KMS key versions (https://cloud.google.com/…

  }

  timeouts { # single
    create = ""     # string | optional
    delete = ""     # string | optional
    update = ""     # string | optional

  }

}

