# ┌──────────────────────────────────────────────────────────────┐
# │  resource: google_kms_ekm_connection                           │
# └──────────────────────────────────────────────────────────────┘
resource "google_kms_ekm_connection" "this" {

  location            = ""     # string | required | The location for the EkmConnection. A full list of valid loc…
  name                = ""     # string | required | The resource name for the EkmConnection.
  crypto_space_path   = ""     # string | optional+computed | Optional. Identifies the EKM Crypto Space that this EkmConne…
  etag                = ""     # string | optional+computed | Optional. Etag of the currently stored EkmConnection.
  id                  = ""     # string | optional+computed
  key_management_mode = ""     # string | optional | Optional. Describes who can perform control plane operations…
  project             = ""     # string | optional+computed

  # create_time         = ""     # string | computed | Output only. The time at which the EkmConnection was created…

  service_resolvers { # list [1..*]
    hostname                  = ""     # string | required | Required. The hostname of the EKM replica used at TLS and HT…
    service_directory_service = ""     # string | required | Required. The resource name of the Service Directory service…
    endpoint_filter           = ""     # string | optional+computed | Optional. The filter applied to the endpoints of the resolve…

    server_certificates { # list [1..*]
      raw_der                       = ""     # string | required | Required. The raw certificate bytes in DER format. A base64-…
      subject_alternative_dns_names = []     # list(string) | optional+computed | Output only. The subject Alternative DNS names. Only present…

      # issuer                        = ""     # string | computed | Output only. The issuer distinguished name in RFC 2253 forma…
      # not_after_time                = ""     # string | computed | Output only. The certificate is not valid after this time. O…
      # not_before_time               = ""     # string | computed | Output only. The certificate is not valid before this time. …
      # parsed                        = false  # bool | computed | Output only. True if the certificate was parsed successfully…
      # serial_number                 = ""     # string | computed | Output only. The certificate serial number as a hex string. …
      # sha256_fingerprint            = ""     # string | computed | Output only. The SHA-256 certificate fingerprint as a hex st…
      # subject                       = ""     # string | computed | Output only. The subject distinguished name in RFC 2253 form…

    }

  }

  timeouts { # single
    create = ""     # string | optional
    delete = ""     # string | optional
    update = ""     # string | optional

  }

}

