# ┌──────────────────────────────────────────────────────────────┐
# │  resource: google_network_services_gateway                     │
# └──────────────────────────────────────────────────────────────┘
resource "google_network_services_gateway" "this" {

  name                                 = ""     # string | required | Short name of the Gateway resource to be created.
  ports                                = []     # list(number) | required | One or more port numbers (1-65535), on which the Gateway wil…
  type                                 = ""     # string | required | Immutable. The type of the customer-managed gateway. Possibl…
  addresses                            = []     # list(string) | optional+computed | Zero or one IPv4-address on which the Gateway will receive t…
  certificate_urls                     = []     # list(string) | optional | A fully-qualified Certificates URL reference. The proxy pres…
  delete_swg_autogen_router_on_destroy = false  # bool | optional | When deleting a gateway of type 'SECURE_WEB_GATEWAY', this b…
  description                          = ""     # string | optional | A free-text description of the resource. Max length 1024 cha…
  gateway_security_policy              = ""     # string | optional | A fully-qualified GatewaySecurityPolicy URL reference. Defin…
  id                                   = ""     # string | optional+computed
  labels                               = {}     # map(string) | optional | Set of label tags associated with the Gateway resource.  **N…
  location                             = ""     # string | optional | The location of the gateway. The default value is 'global'.
  network                              = ""     # string | optional | The relative resource name identifying the VPC network that …
  project                              = ""     # string | optional+computed
  scope                                = ""     # string | optional | Immutable. Scope determines how configuration across multipl…
  server_tls_policy                    = ""     # string | optional | A fully-qualified ServerTLSPolicy URL reference. Specifies h…
  subnetwork                           = ""     # string | optional | The relative resource name identifying the subnetwork in whi…

  # create_time                          = ""     # string | computed | Time the AccessPolicy was created in UTC.
  # effective_labels                     = {}     # map(string) | computed | All of labels (key/value pairs) present on the resource in G…
  # self_link                            = ""     # string | computed | Server-defined URL of this resource.
  # terraform_labels                     = {}     # map(string) | computed | The combination of labels configured directly on the resourc…
  # update_time                          = ""     # string | computed | Time the AccessPolicy was updated in UTC.

  timeouts { # single
    create = ""     # string | optional
    delete = ""     # string | optional
    update = ""     # string | optional

  }

}

