# ┌──────────────────────────────────────────────────────────────┐
# │  resource: google_compute_interconnect                         │
# └──────────────────────────────────────────────────────────────┘
resource "google_compute_interconnect" "this" {

  customer_name            = ""     # string | required | Customer name, to put in the Letter of Authorization as the …
  interconnect_type        = ""     # string | required | Type of interconnect. Note that a value IT_PRIVATE has been …
  link_type                = ""     # string | required | Type of link requested. Note that this field indicates the s…
  location                 = ""     # string | required | URL of the InterconnectLocation object that represents where…
  name                     = ""     # string | required | Name of the resource. Provided by the client when the resour…
  requested_link_count     = 0      # number | required | Target number of physical links in the link bundle, as reque…
  admin_enabled            = false  # bool | optional | Administrative status of the interconnect. When this is set …
  description              = ""     # string | optional | An optional description of this resource. Provide this prope…
  id                       = ""     # string | optional+computed
  labels                   = {}     # map(string) | optional | Labels for this resource. These can only be added or modifie…
  macsec_enabled           = false  # bool | optional | Enable or disable MACsec on this Interconnect connection. MA…
  noc_contact_email        = ""     # string | optional | Email address to contact the customer NOC for operations and…
  project                  = ""     # string | optional+computed
  remote_location          = ""     # string | optional | Indicates that this is a Cross-Cloud Interconnect. This fiel…
  requested_features       = []     # list(string) | optional | interconnects.list of features requested for this Interconne…

  # available_features       = []     # list(string) | computed | interconnects.list of features available for this Interconne…
  # circuit_infos = [  # list(object)
  #   {
  #     customer_demarc_id = ""
  #     google_circuit_id = ""
  #     google_demarc_id = ""
  #   }
  # ]
  # creation_timestamp       = ""     # string | computed | Creation timestamp in RFC3339 text format.
  # effective_labels         = {}     # map(string) | computed | All of labels (key/value pairs) present on the resource in G…
  # expected_outages = [  # list(object)
  #   {
  #     affected_circuits = []  # list(string)
  #     description = ""
  #     end_time = ""
  #     issue_type = ""
  #     name = ""
  #     source = ""
  #     start_time = ""
  #     state = ""
  #   }
  # ]
  # google_ip_address        = ""     # string | computed | IP address configured on the Google side of the Interconnect…
  # google_reference_id      = ""     # string | computed | Google reference ID to be used when raising support tickets …
  # interconnect_attachments = []     # list(string) | computed | A list of the URLs of all InterconnectAttachments configured…
  # label_fingerprint        = ""     # string | computed | A fingerprint for the labels being applied to this Interconn…
  # operational_status       = ""     # string | computed | The current status of this Interconnect's functionality, whi…
  # peer_ip_address          = ""     # string | computed | IP address configured on the customer side of the Interconne…
  # provisioned_link_count   = 0      # number | computed | Number of links actually provisioned in this interconnect.
  # satisfies_pzs            = false  # bool | computed | Reserved for future use.
  # state                    = ""     # string | computed | The current state of Interconnect functionality, which can t…
  # terraform_labels         = {}     # map(string) | computed | The combination of labels configured directly on the resourc…

  macsec { # list [0..1]

    pre_shared_keys { # list [1..*]
      name       = ""     # string | required | A name for this pre-shared key. The name must be 1-63 charac…
      fail_open  = false  # bool | optional | If set to true, the Interconnect connection is configured wi…
      start_time = ""     # string | optional | A RFC3339 timestamp on or after which the key is valid. star…

    }

  }

  timeouts { # single
    create = ""     # string | optional
    delete = ""     # string | optional
    update = ""     # string | optional

  }

}

