# ┌──────────────────────────────────────────────────────────────┐
# │  resource: google_bigquery_job                                 │
# └──────────────────────────────────────────────────────────────┘
resource "google_bigquery_job" "this" {

  job_id           = ""     # string | required | The ID of the job. The ID must contain only letters (a-z, A-…
  id               = ""     # string | optional+computed
  job_timeout_ms   = ""     # string | optional | Job timeout in milliseconds. If this time limit is exceeded,…
  labels           = {}     # map(string) | optional | The labels associated with this job. You can use these to or…
  location         = ""     # string | optional | The geographic location of the job. The default value is US.
  project          = ""     # string | optional+computed

  # effective_labels = {}     # map(string) | computed | All of labels (key/value pairs) present on the resource in G…
  # job_type         = ""     # string | computed | The type of the job.
  # status = [  # list(object)
  #   {
  #     error_result = [  # list(object)
  #       {
  #         location = ""
  #         message = ""
  #         reason = ""
  #       }
  #     ]
  #     errors = [  # list(object)
  #       {
  #         location = ""
  #         message = ""
  #         reason = ""
  #       }
  #     ]
  #     state = ""
  #   }
  # ]
  # terraform_labels = {}     # map(string) | computed | The combination of labels configured directly on the resourc…
  # user_email       = ""     # string | computed | Email address of the user who ran the job.

  copy { # list [0..1]
    create_disposition = ""     # string | optional | Specifies whether the job is allowed to create new tables. T…
    write_disposition  = ""     # string | optional | Specifies the action that occurs if the destination table al…

    destination_encryption_configuration { # list [0..1]
      kms_key_name    = ""     # string | required | Describes the Cloud KMS encryption key that will be used to …

      # kms_key_version = ""     # string | computed | Describes the Cloud KMS encryption key version used to prote…

    }

    destination_table { # list [0..1]
      table_id   = ""     # string | required | The table. Can be specified '{{table_id}}' if 'project_id' a…
      dataset_id = ""     # string | optional+computed | The ID of the dataset containing this table.
      project_id = ""     # string | optional+computed | The ID of the project containing this table.

    }

    source_tables { # list [1..*]
      table_id   = ""     # string | required | The table. Can be specified '{{table_id}}' if 'project_id' a…
      dataset_id = ""     # string | optional+computed | The ID of the dataset containing this table.
      project_id = ""     # string | optional+computed | The ID of the project containing this table.

    }

  }

  extract { # list [0..1]
    destination_uris       = []     # list(string) | required | A list of fully-qualified Google Cloud Storage URIs where th…
    compression            = ""     # string | optional | The compression type to use for exported files. Possible val…
    destination_format     = ""     # string | optional+computed | The exported file format. Possible values include CSV, NEWLI…
    field_delimiter        = ""     # string | optional+computed | When extracting data in CSV format, this defines the delimit…
    print_header           = false  # bool | optional | Whether to print out a header row in the results. Default is…
    use_avro_logical_types = false  # bool | optional | Whether to use logical types when extracting to AVRO format.

    source_model { # list [0..1]
      dataset_id = ""     # string | required | The ID of the dataset containing this model.
      model_id   = ""     # string | required | The ID of the model.
      project_id = ""     # string | required | The ID of the project containing this model.

    }

    source_table { # list [0..1]
      table_id   = ""     # string | required | The table. Can be specified '{{table_id}}' if 'project_id' a…
      dataset_id = ""     # string | optional+computed | The ID of the dataset containing this table.
      project_id = ""     # string | optional+computed | The ID of the project containing this table.

    }

  }

  load { # list [0..1]
    source_uris           = []     # list(string) | required | The fully-qualified URIs that point to your data in Google C…
    allow_jagged_rows     = false  # bool | optional | Accept rows that are missing trailing optional columns. The …
    allow_quoted_newlines = false  # bool | optional | Indicates if BigQuery should allow quoted data sections that…
    autodetect            = false  # bool | optional | Indicates if we should automatically infer the options and s…
    create_disposition    = ""     # string | optional | Specifies whether the job is allowed to create new tables. T…
    encoding              = ""     # string | optional | The character encoding of the data. The supported values are…
    field_delimiter       = ""     # string | optional+computed | The separator for fields in a CSV file. The separator can be…
    ignore_unknown_values = false  # bool | optional | Indicates if BigQuery should allow extra values that are not…
    json_extension        = ""     # string | optional | If sourceFormat is set to newline-delimited JSON, indicates …
    max_bad_records       = 0      # number | optional | The maximum number of bad records that BigQuery can ignore w…
    null_marker           = ""     # string | optional | Specifies a string that represents a null value in a CSV fil…
    projection_fields     = []     # list(string) | optional | If sourceFormat is set to "DATASTORE_BACKUP", indicates whic…
    quote                 = ""     # string | optional+computed | The value that is used to quote data sections in a CSV file.…
    schema_update_options = []     # list(string) | optional | Allows the schema of the destination table to be updated as …
    skip_leading_rows     = 0      # number | optional | The number of rows at the top of a CSV file that BigQuery wi…
    source_format         = ""     # string | optional | The format of the data files. For CSV files, specify "CSV". …
    write_disposition     = ""     # string | optional | Specifies the action that occurs if the destination table al…

    destination_encryption_configuration { # list [0..1]
      kms_key_name    = ""     # string | required | Describes the Cloud KMS encryption key that will be used to …

      # kms_key_version = ""     # string | computed | Describes the Cloud KMS encryption key version used to prote…

    }

    destination_table { # list [1..1]
      table_id   = ""     # string | required | The table. Can be specified '{{table_id}}' if 'project_id' a…
      dataset_id = ""     # string | optional+computed | The ID of the dataset containing this table.
      project_id = ""     # string | optional+computed | The ID of the project containing this table.

    }

    parquet_options { # list [0..1]
      enable_list_inference = false  # bool | optional | If sourceFormat is set to PARQUET, indicates whether to use …
      enum_as_string        = false  # bool | optional | If sourceFormat is set to PARQUET, indicates whether to infe…

    }

    time_partitioning { # list [0..1]
      type          = ""     # string | required | The only type supported is DAY, which will generate one part…
      expiration_ms = ""     # string | optional | Number of milliseconds for which to keep the storage for a p…
      field         = ""     # string | optional | If not set, the table is partitioned by pseudo column '_PART…

    }

  }

  query { # list [0..1]
    query                 = ""     # string | required | SQL query text to execute. The useLegacySql field can be use…
    allow_large_results   = false  # bool | optional | If true and query uses legacy SQL dialect, allows the query …
    create_disposition    = ""     # string | optional | Specifies whether the job is allowed to create new tables. T…
    flatten_results       = false  # bool | optional | If true and query uses legacy SQL dialect, flattens all nest…
    maximum_billing_tier  = 0      # number | optional | Limits the billing tier for this job. Queries that have reso…
    maximum_bytes_billed  = ""     # string | optional | Limits the bytes billed for this job. Queries that will have…
    parameter_mode        = ""     # string | optional | Standard SQL only. Set to POSITIONAL to use positional (?) q…
    priority              = ""     # string | optional | Specifies a priority for the query. Default value: "INTERACT…
    schema_update_options = []     # list(string) | optional | Allows the schema of the destination table to be updated as …
    use_legacy_sql        = false  # bool | optional | Specifies whether to use BigQuery's legacy SQL dialect for t…
    use_query_cache       = false  # bool | optional | Whether to look for the result in the query cache. The query…
    write_disposition     = ""     # string | optional | Specifies the action that occurs if the destination table al…

    default_dataset { # list [0..1]
      dataset_id = ""     # string | required | The dataset. Can be specified '{{dataset_id}}' if 'project_i…
      project_id = ""     # string | optional+computed | The ID of the project containing this table.

    }

    destination_encryption_configuration { # list [0..1]
      kms_key_name    = ""     # string | required | Describes the Cloud KMS encryption key that will be used to …

      # kms_key_version = ""     # string | computed | Describes the Cloud KMS encryption key version used to prote…

    }

    destination_table { # list [0..1]
      table_id   = ""     # string | required | The table. Can be specified '{{table_id}}' if 'project_id' a…
      dataset_id = ""     # string | optional+computed | The ID of the dataset containing this table.
      project_id = ""     # string | optional+computed | The ID of the project containing this table.

    }

    script_options { # list [0..1]
      key_result_statement  = ""     # string | optional | Determines which statement in the script represents the "key…
      statement_byte_budget = ""     # string | optional | Limit on the number of bytes billed per statement. Exceeding…
      statement_timeout_ms  = ""     # string | optional | Timeout period for each statement in a script.

    }

    user_defined_function_resources { # list
      inline_code  = ""     # string | optional | An inline resource that contains code for a user-defined fun…
      resource_uri = ""     # string | optional | A code resource to load from a Google Cloud Storage URI (gs:…

    }

  }

  timeouts { # single
    create = ""     # string | optional
    delete = ""     # string | optional
    update = ""     # string | optional

  }

}

