# ┌──────────────────────────────────────────────────────────────┐
# │  resource: google_filestore_backup                             │
# └──────────────────────────────────────────────────────────────┘
resource "google_filestore_backup" "this" {

  location             = ""     # string | required | The name of the location of the instance. This can be a regi…
  name                 = ""     # string | required | The resource name of the backup. The name must be unique wit…
  source_file_share    = ""     # string | required | Name of the file share in the source Cloud Filestore instanc…
  source_instance      = ""     # string | required | The resource name of the source Cloud Filestore instance, in…
  description          = ""     # string | optional | A description of the backup with 2048 characters or less. Re…
  id                   = ""     # string | optional+computed
  labels               = {}     # map(string) | optional | Resource labels to represent user-provided metadata.   **Not…
  project              = ""     # string | optional+computed

  # capacity_gb          = ""     # string | computed | The amount of bytes needed to allocate a full copy of the sn…
  # create_time          = ""     # string | computed | The time when the snapshot was created in RFC3339 text forma…
  # download_bytes       = ""     # string | computed | Amount of bytes that will be downloaded if the backup is res…
  # effective_labels     = {}     # map(string) | computed | All of labels (key/value pairs) present on the resource in G…
  # kms_key_name         = ""     # string | computed | KMS key name used for data encryption.
  # source_instance_tier = ""     # string | computed | The service tier of the source Cloud Filestore instance that…
  # state                = ""     # string | computed | The backup state.
  # storage_bytes        = ""     # string | computed | The size of the storage used by the backup. As backups share…
  # terraform_labels     = {}     # map(string) | computed | The combination of labels configured directly on the resourc…

  timeouts { # single
    create = ""     # string | optional
    delete = ""     # string | optional
    update = ""     # string | optional

  }

}

