# ┌──────────────────────────────────────────────────────────────┐
# │  resource: google_compute_vpn_tunnel                           │
# └──────────────────────────────────────────────────────────────┘
resource "google_compute_vpn_tunnel" "this" {

  name                            = ""     # string | required | Name of the resource. The name must be 1-63 characters long,…
  shared_secret                   = ""     # string | required+sensitive | Shared secret used to set the secure session between the Clo…
  description                     = ""     # string | optional | An optional description of this resource.
  id                              = ""     # string | optional+computed
  ike_version                     = 0      # number | optional | IKE protocol version to use when establishing the VPN tunnel…
  labels                          = {}     # map(string) | optional | Labels to apply to this VpnTunnel.  **Note**: This field is …
  local_traffic_selector          = []     # set(string) | optional+computed | Local traffic selector to use when establishing the VPN tunn…
  peer_external_gateway           = ""     # string | optional | URL of the peer side external VPN gateway to which this VPN …
  peer_external_gateway_interface = 0      # number | optional | The interface ID of the external VPN gateway to which this V…
  peer_gcp_gateway                = ""     # string | optional | URL of the peer side HA GCP VPN gateway to which this VPN tu…
  peer_ip                         = ""     # string | optional+computed | IP address of the peer VPN gateway. Only IPv4 is supported.
  project                         = ""     # string | optional+computed
  region                          = ""     # string | optional+computed | The region where the tunnel is located. If unset, is set to …
  remote_traffic_selector         = []     # set(string) | optional+computed | Remote traffic selector to use when establishing the VPN tun…
  router                          = ""     # string | optional | URL of router resource to be used for dynamic routing.
  target_vpn_gateway              = ""     # string | optional | URL of the Target VPN gateway with which this VPN tunnel is …
  vpn_gateway                     = ""     # string | optional | URL of the VPN gateway with which this VPN tunnel is associa…
  vpn_gateway_interface           = 0      # number | optional | The interface ID of the VPN gateway with which this VPN tunn…

  # creation_timestamp              = ""     # string | computed | Creation timestamp in RFC3339 text format.
  # detailed_status                 = ""     # string | computed | Detailed status message for the VPN tunnel.
  # effective_labels                = {}     # map(string) | computed | All of labels (key/value pairs) present on the resource in G…
  # label_fingerprint               = ""     # string | computed | The fingerprint used for optimistic locking of this resource…
  # self_link                       = ""     # string | computed
  # shared_secret_hash              = ""     # string | computed | Hash of the shared secret.
  # terraform_labels                = {}     # map(string) | computed | The combination of labels configured directly on the resourc…
  # tunnel_id                       = ""     # string | computed | The unique identifier for the resource. This identifier is d…

  timeouts { # single
    create = ""     # string | optional
    delete = ""     # string | optional
    update = ""     # string | optional

  }

}

