# ┌──────────────────────────────────────────────────────────────┐
# │  resource: google_certificate_manager_certificate_issuance_config  │
# └──────────────────────────────────────────────────────────────┘
resource "google_certificate_manager_certificate_issuance_config" "this" {

  key_algorithm              = ""     # string | required | Key algorithm to use when generating the private key. Possib…
  lifetime                   = ""     # string | required | Lifetime of issued certificates. A duration in seconds with …
  name                       = ""     # string | required | A user-defined name of the certificate issuance config. Cert…
  rotation_window_percentage = 0      # number | required | It specifies the percentage of elapsed time of the certifica…
  description                = ""     # string | optional | One or more paragraphs of text description of a CertificateI…
  id                         = ""     # string | optional+computed
  labels                     = {}     # map(string) | optional | 'Set of label tags associated with the CertificateIssuanceCo…
  location                   = ""     # string | optional | The Certificate Manager location. If not specified, "global"…
  project                    = ""     # string | optional+computed

  # create_time                = ""     # string | computed | The creation timestamp of a CertificateIssuanceConfig. Times…
  # effective_labels           = {}     # map(string) | computed | All of labels (key/value pairs) present on the resource in G…
  # terraform_labels           = {}     # map(string) | computed | The combination of labels configured directly on the resourc…
  # update_time                = ""     # string | computed | The last update timestamp of a CertificateIssuanceConfig. Ti…

  certificate_authority_config { # list [1..1]

    certificate_authority_service_config { # list [0..1]
      ca_pool = ""     # string | required | A CA pool resource used to issue a certificate. The CA pool …

    }

  }

  timeouts { # single
    create = ""     # string | optional
    delete = ""     # string | optional
    update = ""     # string | optional

  }

}

