# ┌──────────────────────────────────────────────────────────────┐
# │  resource: google_compute_router_peer                          │
# └──────────────────────────────────────────────────────────────┘
resource "google_compute_router_peer" "this" {

  interface                     = ""     # string | required | Name of the interface the BGP peer is associated with.
  name                          = ""     # string | required | Name of this BGP peer. The name must be 1-63 characters long…
  peer_asn                      = 0      # number | required | Peer BGP Autonomous System Number (ASN). Each BGP interface …
  router                        = ""     # string | required | The name of the Cloud Router in which this BgpPeer will be c…
  advertise_mode                = ""     # string | optional | User-specified flag to indicate which mode to use for advert…
  advertised_groups             = []     # list(string) | optional | User-specified list of prefix groups to advertise in custom …
  advertised_route_priority     = 0      # number | optional | The priority of routes advertised to this BGP peer. Where th…
  custom_learned_route_priority = 0      # number | optional | The user-defined custom learned route priority for a BGP ses…
  enable                        = false  # bool | optional | The status of the BGP peer connection. If set to false, any …
  enable_ipv4                   = false  # bool | optional+computed | Enable IPv4 traffic over BGP Peer. It is enabled by default …
  enable_ipv6                   = false  # bool | optional | Enable IPv6 traffic over BGP Peer. If not specified, it is d…
  id                            = ""     # string | optional+computed
  ip_address                    = ""     # string | optional+computed | IP address of the interface inside Google Cloud Platform. On…
  ipv4_nexthop_address          = ""     # string | optional+computed | IPv4 address of the interface inside Google Cloud Platform.
  ipv6_nexthop_address          = ""     # string | optional+computed | IPv6 address of the interface inside Google Cloud Platform. …
  peer_ip_address               = ""     # string | optional+computed | IP address of the BGP interface outside Google Cloud Platfor…
  peer_ipv4_nexthop_address     = ""     # string | optional+computed | IPv4 address of the BGP interface outside Google Cloud Platf…
  peer_ipv6_nexthop_address     = ""     # string | optional+computed | IPv6 address of the BGP interface outside Google Cloud Platf…
  project                       = ""     # string | optional+computed
  region                        = ""     # string | optional+computed | Region where the router and BgpPeer reside. If it is not pro…
  router_appliance_instance     = ""     # string | optional | The URI of the VM instance that is used as third-party route…

  # management_type               = ""     # string | computed | The resource that configures and manages this BGP peer.  * '…

  advertised_ip_ranges { # list
    range       = ""     # string | required | The IP range to advertise. The value must be a CIDR-formatte…
    description = ""     # string | optional | User-specified description for the IP range.

  }

  bfd { # list [0..1]
    session_initialization_mode = ""     # string | required | The BFD session initialization mode for this BGP peer. If se…
    min_receive_interval        = 0      # number | optional | The minimum interval, in milliseconds, between BFD control p…
    min_transmit_interval       = 0      # number | optional | The minimum interval, in milliseconds, between BFD control p…
    multiplier                  = 0      # number | optional | The number of consecutive BFD packets that must be missed be…

  }

  custom_learned_ip_ranges { # list
    range = ""     # string | required | The IP range to advertise. The value must be a CIDR-formatte…

  }

  md5_authentication_key { # list [0..1]
    key  = ""     # string | required+sensitive | Value of the key.
    name = ""     # string | required | [REQUIRED] Name used to identify the key. Must be unique wit…

  }

  timeouts { # single
    create = ""     # string | optional
    delete = ""     # string | optional
    update = ""     # string | optional

  }

}

