# ┌──────────────────────────────────────────────────────────────┐
# │  resource: google_notebooks_instance                           │
# └──────────────────────────────────────────────────────────────┘
# ⚠ DEPRECATED: this resource type is deprecated
resource "google_notebooks_instance" "this" {

  location               = ""     # string | required | A reference to the zone where the machine resides.
  machine_type           = ""     # string | required | A reference to a machine type which defines VM kind.
  name                   = ""     # string | required | The name specified for the Notebook instance.
  boot_disk_size_gb      = 0      # number | optional | The size of the boot disk in GB attached to this instance, u…
  boot_disk_type         = ""     # string | optional | Possible disk types for notebook instances. Possible values:…
  create_time            = ""     # string | optional+computed | Instance creation time
  custom_gpu_driver_path = ""     # string | optional | Specify a custom Cloud Storage path where the GPU driver is …
  data_disk_size_gb      = 0      # number | optional | The size of the data disk in GB attached to this instance, u…
  data_disk_type         = ""     # string | optional | Possible disk types for notebook instances. Possible values:…
  desired_state          = ""     # string | optional | Desired state of the Notebook Instance. Set this field to 'A…
  disk_encryption        = ""     # string | optional+computed | Disk encryption method used on the boot and data disks, defa…
  id                     = ""     # string | optional+computed
  install_gpu_driver     = false  # bool | optional | Whether the end user authorizes Google Cloud to install GPU …
  instance_owners        = []     # list(string) | optional | The list of owners of this instance after creation. Format: …
  kms_key                = ""     # string | optional | The KMS key used to encrypt the disks, only applicable if di…
  labels                 = {}     # map(string) | optional | Labels to apply to this instance. These can be later modifie…
  metadata               = {}     # map(string) | optional | Custom metadata to apply to this instance. An object contain…
  network                = ""     # string | optional+computed | The name of the VPC that this instance is in. Format: projec…
  nic_type               = ""     # string | optional | The type of vNIC driver. Possible values: ["UNSPECIFIED_NIC_…
  no_proxy_access        = false  # bool | optional | The notebook instance will not register with the proxy..
  no_public_ip           = false  # bool | optional | No public IP will be assigned to this instance.
  no_remove_data_disk    = false  # bool | optional | If true, the data disk will not be auto deleted when deletin…
  post_startup_script    = ""     # string | optional | Path to a Bash script that automatically runs after a notebo…
  project                = ""     # string | optional+computed
  service_account        = ""     # string | optional+computed | The service account on this instance, giving access to other…
  service_account_scopes = []     # list(string) | optional+computed | Optional. The URIs of service account scopes to be included …
  subnet                 = ""     # string | optional+computed | The name of the subnet that this instance is in. Format: pro…
  tags                   = []     # list(string) | optional+computed | The Compute Engine tags to add to instance.
  update_time            = ""     # string | optional+computed | Instance update time.

  # effective_labels       = {}     # map(string) | computed | All of labels (key/value pairs) present on the resource in G…
  # proxy_uri              = ""     # string | computed | The proxy endpoint that is used to access the Jupyter notebo…
  # state                  = ""     # string | computed | The state of this instance.
  # terraform_labels       = {}     # map(string) | computed | The combination of labels configured directly on the resourc…

  accelerator_config { # list [0..1]
    core_count = 0      # number | required | Count of cores of this accelerator.
    type       = ""     # string | required | Type of this accelerator. Possible values: ["ACCELERATOR_TYP…

  }

  container_image { # list [0..1]
    repository = ""     # string | required | The path to the container image repository. For example: gcr…
    tag        = ""     # string | optional | The tag of the container image. If not specified, this defau…

  }

  reservation_affinity { # list [0..1]
    consume_reservation_type = ""     # string | required | The type of Compute Reservation. Possible values: ["NO_RESER…
    key                      = ""     # string | optional | Corresponds to the label key of reservation resource.
    values                   = []     # list(string) | optional | Corresponds to the label values of reservation resource.

  }

  shielded_instance_config { # list [0..1]
    enable_integrity_monitoring = false  # bool | optional | Defines whether the instance has integrity monitoring enable…
    enable_secure_boot          = false  # bool | optional | Defines whether the instance has Secure Boot enabled. Secure…
    enable_vtpm                 = false  # bool | optional | Defines whether the instance has the vTPM enabled. Enabled b…

  }

  timeouts { # single
    create = ""     # string | optional
    delete = ""     # string | optional
    update = ""     # string | optional

  }

  vm_image { # list [0..1]
    project      = ""     # string | required | The name of the Google Cloud project that this VM image belo…
    image_family = ""     # string | optional | Use this VM image family to find the image; the newest image…
    image_name   = ""     # string | optional | Use VM image name to find the image.

  }

}

