# ┌──────────────────────────────────────────────────────────────┐
# │  resource: google_compute_region_network_endpoint_group        │
# └──────────────────────────────────────────────────────────────┘
resource "google_compute_region_network_endpoint_group" "this" {

  name                  = ""     # string | required | Name of the resource; provided by the client when the resour…
  region                = ""     # string | required | A reference to the region where the regional NEGs reside.
  description           = ""     # string | optional | An optional description of this resource. Provide this prope…
  id                    = ""     # string | optional+computed
  network               = ""     # string | optional | This field is only used for PSC and INTERNET NEGs.  The URL …
  network_endpoint_type = ""     # string | optional | Type of network endpoints in this network endpoint group. De…
  project               = ""     # string | optional+computed
  psc_target_service    = ""     # string | optional | This field is only used for PSC and INTERNET NEGs.  The targ…
  subnetwork            = ""     # string | optional | This field is only used for PSC NEGs.  Optional URL of the s…

  # self_link             = ""     # string | computed

  app_engine { # list [0..1]
    service  = ""     # string | optional | Optional serving service. The service name must be 1-63 char…
    url_mask = ""     # string | optional | A template to parse service and version fields from a reques…
    version  = ""     # string | optional | Optional serving version. The version must be 1-63 character…

  }

  cloud_function { # list [0..1]
    function = ""     # string | optional | A user-defined name of the Cloud Function. The function name…
    url_mask = ""     # string | optional | A template to parse function field from a request URL. URL m…

  }

  cloud_run { # list [0..1]
    service  = ""     # string | optional | Cloud Run service is the main resource of Cloud Run. The ser…
    tag      = ""     # string | optional | Cloud Run tag represents the "named-revision" to provide add…
    url_mask = ""     # string | optional | A template to parse service and tag fields from a request UR…

  }

  timeouts { # single
    create = ""     # string | optional
    delete = ""     # string | optional

  }

}

