# ┌──────────────────────────────────────────────────────────────┐
# │  resource: google_bigquery_routine                             │
# └──────────────────────────────────────────────────────────────┘
resource "google_bigquery_routine" "this" {

  dataset_id           = ""     # string | required | The ID of the dataset containing this routine
  definition_body      = ""     # string | required | The body of the routine. For functions, this is the expressi…
  routine_id           = ""     # string | required | The ID of the the routine. The ID must contain only letters …
  routine_type         = ""     # string | required | The type of routine. Possible values: ["SCALAR_FUNCTION", "P…
  data_governance_type = ""     # string | optional | If set to DATA_MASKING, the function is validated and made a…
  description          = ""     # string | optional | The description of the routine if defined.
  determinism_level    = ""     # string | optional | The determinism level of the JavaScript UDF if defined. Poss…
  id                   = ""     # string | optional+computed
  imported_libraries   = []     # list(string) | optional | Optional. If language = "JAVASCRIPT", this field stores the …
  language             = ""     # string | optional | The language of the routine. Possible values: ["SQL", "JAVAS…
  project              = ""     # string | optional+computed
  return_table_type    = ""     # string | optional | Optional. Can be set only if routineType = "TABLE_VALUED_FUN…
  return_type          = ""     # string | optional | A JSON schema for the return type. Optional if language = "S…

  # creation_time        = 0      # number | computed | The time when this routine was created, in milliseconds sinc…
  # last_modified_time   = 0      # number | computed | The time when this routine was modified, in milliseconds sin…

  arguments { # list
    argument_kind = ""     # string | optional | Defaults to FIXED_TYPE. Default value: "FIXED_TYPE" Possible…
    data_type     = ""     # string | optional | A JSON schema for the data type. Required unless argumentKin…
    mode          = ""     # string | optional | Specifies whether the argument is input or output. Can be se…
    name          = ""     # string | optional | The name of this argument. Can be absent for function return…

  }

  remote_function_options { # list [0..1]
    connection           = ""     # string | optional | Fully qualified name of the user-provided connection object …
    endpoint             = ""     # string | optional | Endpoint of the user-provided remote service, e.g. 'https://…
    max_batching_rows    = ""     # string | optional | Max number of rows in each batch sent to the remote service.…
    user_defined_context = {}     # map(string) | optional+computed | User-defined context as a set of key/value pairs, which will…

  }

  spark_options { # list [0..1]
    archive_uris    = []     # list(string) | optional+computed | Archive files to be extracted into the working directory of …
    connection      = ""     # string | optional | Fully qualified name of the user-provided Spark connection o…
    container_image = ""     # string | optional | Custom container image for the runtime environment.
    file_uris       = []     # list(string) | optional+computed | Files to be placed in the working directory of each executor…
    jar_uris        = []     # list(string) | optional+computed | JARs to include on the driver and executor CLASSPATH. For mo…
    main_class      = ""     # string | optional | The fully qualified name of a class in jarUris, for example,…
    main_file_uri   = ""     # string | optional | The main file/jar URI of the Spark application. Exactly one …
    properties      = {}     # map(string) | optional+computed | Configuration properties as a set of key/value pairs, which …
    py_file_uris    = []     # list(string) | optional+computed | Python files to be placed on the PYTHONPATH for PySpark appl…
    runtime_version = ""     # string | optional | Runtime version. If not specified, the default runtime versi…

  }

  timeouts { # single
    create = ""     # string | optional
    delete = ""     # string | optional
    update = ""     # string | optional

  }

}

