# ┌──────────────────────────────────────────────────────────────┐
# │  resource: google_compute_image                                │
# └──────────────────────────────────────────────────────────────┘
resource "google_compute_image" "this" {

  name               = ""     # string | required | Name of the resource; provided by the client when the resour…
  description        = ""     # string | optional | An optional description of this resource. Provide this prope…
  disk_size_gb       = 0      # number | optional+computed | Size of the image when restored onto a persistent disk (in G…
  family             = ""     # string | optional | The name of the image family to which this image belongs. Yo…
  id                 = ""     # string | optional+computed
  labels             = {}     # map(string) | optional | Labels to apply to this Image.  **Note**: This field is non-…
  licenses           = []     # list(string) | optional+computed | Any applicable license URI.
  project            = ""     # string | optional+computed
  source_disk        = ""     # string | optional | The source disk to create this image based on. You must prov…
  source_image       = ""     # string | optional | URL of the source image used to create this image. In order …
  source_snapshot    = ""     # string | optional | URL of the source snapshot used to create this image.  In or…
  storage_locations  = []     # list(string) | optional+computed | Cloud Storage bucket storage location of the image (regional…

  # archive_size_bytes = 0      # number | computed | Size of the image tar.gz archive stored in Google Cloud Stor…
  # creation_timestamp = ""     # string | computed | Creation timestamp in RFC3339 text format.
  # effective_labels   = {}     # map(string) | computed | All of labels (key/value pairs) present on the resource in G…
  # label_fingerprint  = ""     # string | computed | The fingerprint used for optimistic locking of this resource…
  # self_link          = ""     # string | computed
  # terraform_labels   = {}     # map(string) | computed | The combination of labels configured directly on the resourc…

  guest_os_features { # set
    type = ""     # string | required | The type of supported feature. Read [Enabling guest operatin…

  }

  image_encryption_key { # list [0..1]
    kms_key_self_link       = ""     # string | optional | The self link of the encryption key that is stored in Google…
    kms_key_service_account = ""     # string | optional | The service account being used for the encryption request fo…

  }

  raw_disk { # list [0..1]
    source         = ""     # string | required | The full Google Cloud Storage URL where disk storage is stor…
    container_type = ""     # string | optional | The format used to encode and transmit the block device, whi…
    sha1           = ""     # string | optional | An optional SHA1 checksum of the disk image before unpackagi…

  }

  timeouts { # single
    create = ""     # string | optional
    delete = ""     # string | optional
    update = ""     # string | optional

  }

}

