# ┌──────────────────────────────────────────────────────────────┐
# │  resource: google_notebooks_runtime                            │
# └──────────────────────────────────────────────────────────────┘
resource "google_notebooks_runtime" "this" {

  location         = ""     # string | required | A reference to the zone where the machine resides.
  name             = ""     # string | required | The name specified for the Notebook runtime.
  id               = ""     # string | optional+computed
  labels           = {}     # map(string) | optional | The labels to associate with this runtime. Label **keys** mu…
  project          = ""     # string | optional+computed

  # effective_labels = {}     # map(string) | computed | All of labels (key/value pairs) present on the resource in G…
  # health_state     = ""     # string | computed | The health state of this runtime. For a list of possible out…
  # metrics = [  # list(object)
  #   {
  #     system_metrics = {}  # map(string)
  #   }
  # ]
  # state            = ""     # string | computed | The state of this runtime.
  # terraform_labels = {}     # map(string) | computed | The combination of labels configured directly on the resourc…

  access_config { # list [0..1]
    access_type   = ""     # string | optional | The type of access mode this instance. For valid values, see…
    runtime_owner = ""     # string | optional | The owner of this runtime after creation. Format: 'alias@exa…

    # proxy_uri     = ""     # string | computed | The proxy endpoint that is used to access the runtime.

  }

  software_config { # list [0..1]
    custom_gpu_driver_path       = ""     # string | optional | Specify a custom Cloud Storage path where the GPU driver is …
    enable_health_monitoring     = false  # bool | optional | Verifies core internal services are running. Default: True.
    idle_shutdown                = false  # bool | optional | Runtime will automatically shutdown after idle_shutdown_time…
    idle_shutdown_timeout        = 0      # number | optional | Time in minutes to wait before shuting down runtime. Default…
    install_gpu_driver           = false  # bool | optional | Install Nvidia Driver automatically.
    notebook_upgrade_schedule    = ""     # string | optional | Cron expression in UTC timezone for schedule instance auto u…
    post_startup_script          = ""     # string | optional | Path to a Bash script that automatically runs after a notebo…
    post_startup_script_behavior = ""     # string | optional | Behavior for the post startup script. Possible values: ["POS…

    # upgradeable                  = false  # bool | computed | Bool indicating whether an newer image is available in an im…

    kernels { # list
      repository = ""     # string | required | The path to the container image repository. For example: gcr…
      tag        = ""     # string | optional | The tag of the container image. If not specified, this defau…

    }

  }

  timeouts { # single
    create = ""     # string | optional
    delete = ""     # string | optional
    update = ""     # string | optional

  }

  virtual_machine { # list [0..1]

    # instance_id   = ""     # string | computed | The unique identifier of the Managed Compute Engine instance…
    # instance_name = ""     # string | computed | The user-friendly name of the Managed Compute Engine instanc…

    virtual_machine_config { # list [0..1]
      machine_type      = ""     # string | required | The Compute Engine machine type used for runtimes.
      internal_ip_only  = false  # bool | optional | If true, runtime will only have internal IP addresses. By de…
      labels            = {}     # map(string) | optional+computed | The labels to associate with this runtime. Label **keys** mu…
      metadata          = {}     # map(string) | optional+computed | The Compute Engine metadata entries to add to virtual machin…
      network           = ""     # string | optional | The Compute Engine network to be used for machine communicat…
      nic_type          = ""     # string | optional | The type of vNIC to be used on this interface. This may be g…
      reserved_ip_range = ""     # string | optional | Reserved IP Range name is used for VPC Peering. The subnetwo…
      subnet            = ""     # string | optional | The Compute Engine subnetwork to be used for machine communi…
      tags              = []     # list(string) | optional+computed | The Compute Engine tags to add to runtime (see [Tagging inst…

      # guest_attributes  = {}     # map(string) | computed | The Compute Engine guest attributes. (see [Project and insta…
      # zone              = ""     # string | computed | The zone where the virtual machine is located.

      accelerator_config { # list [0..1]
        core_count = 0      # number | optional | Count of cores of this accelerator.
        type       = ""     # string | optional | Accelerator model. For valid values, see 'https://cloud.goog…

      }

      container_images { # list
        repository = ""     # string | required | The path to the container image repository. For example: gcr…
        tag        = ""     # string | optional | The tag of the container image. If not specified, this defau…

      }

      data_disk { # list [1..1]
        interface         = ""     # string | optional | "Specifies the disk interface to use for attaching this disk…
        mode              = ""     # string | optional | The mode in which to attach this disk, either READ_WRITE or …
        source            = ""     # string | optional | Specifies a valid partial or full URL to an existing Persist…
        type              = ""     # string | optional | Specifies the type of the disk, either SCRATCH or PERSISTENT…

        # auto_delete       = false  # bool | computed | Optional. Specifies whether the disk will be auto-deleted wh…
        # boot              = false  # bool | computed | Optional. Indicates that this is a boot disk. The virtual ma…
        # device_name       = ""     # string | computed | Optional. Specifies a unique device name of your choice that…
        # guest_os_features = []     # list(string) | computed | Indicates a list of features to enable on the guest operatin…
        # index             = 0      # number | computed | Output only. A zero-based index to this disk, where 0 is res…
        # kind              = ""     # string | computed | Type of the resource. Always compute#attachedDisk for attach…
        # licenses          = []     # list(string) | computed | Output only. Any valid publicly visible licenses.

        initialize_params { # list [0..1]
          description  = ""     # string | optional | Provide this property when creating the disk.
          disk_name    = ""     # string | optional | Specifies the disk name. If not specified, the default is to…
          disk_size_gb = 0      # number | optional | Specifies the size of the disk in base-2 GB. If not specifie…
          disk_type    = ""     # string | optional | The type of the boot disk attached to this runtime, defaults…
          labels       = {}     # map(string) | optional+computed | Labels to apply to this disk. These can be later modified by…

        }

      }

      encryption_config { # list [0..1]
        kms_key = ""     # string | optional | The Cloud KMS resource identifier of the customer-managed en…

      }

      shielded_instance_config { # list [0..1]
        enable_integrity_monitoring = false  # bool | optional | Defines whether the instance has integrity monitoring enable…
        enable_secure_boot          = false  # bool | optional | Defines whether the instance has Secure Boot enabled.Secure …
        enable_vtpm                 = false  # bool | optional | Defines whether the instance has the vTPM enabled. Enabled b…

      }

    }

  }

}

