# ┌──────────────────────────────────────────────────────────────┐
# │  resource: google_compute_region_url_map                       │
# └──────────────────────────────────────────────────────────────┘
resource "google_compute_region_url_map" "this" {

  name               = ""     # string | required | Name of the resource. Provided by the client when the resour…
  default_service    = ""     # string | optional | The full or partial URL of the defaultService resource to wh…
  description        = ""     # string | optional | An optional description of this resource. Provide this prope…
  id                 = ""     # string | optional+computed
  project            = ""     # string | optional+computed
  region             = ""     # string | optional+computed | The Region in which the url map should reside. If it is not …

  # creation_timestamp = ""     # string | computed | Creation timestamp in RFC3339 text format.
  # fingerprint        = ""     # string | computed | Fingerprint of this resource. This field is used internally …
  # map_id             = 0      # number | computed | The unique identifier for the resource.
  # self_link          = ""     # string | computed

  default_route_action { # list [0..1]

    cors_policy { # list [0..1]
      allow_credentials    = false  # bool | optional | In response to a preflight request, setting this to true ind…
      allow_headers        = []     # list(string) | optional | Specifies the content for the Access-Control-Allow-Headers h…
      allow_methods        = []     # list(string) | optional | Specifies the content for the Access-Control-Allow-Methods h…
      allow_origin_regexes = []     # list(string) | optional | Specifies the regualar expression patterns that match allowe…
      allow_origins        = []     # list(string) | optional | Specifies the list of origins that will be allowed to do COR…
      disabled             = false  # bool | optional | If true, the setting specifies the CORS policy is disabled. …
      expose_headers       = []     # list(string) | optional | Specifies the content for the Access-Control-Expose-Headers …
      max_age              = 0      # number | optional | Specifies how long results of a preflight request can be cac…

    }

    fault_injection_policy { # list [0..1]

      abort { # list [0..1]
        http_status = 0      # number | optional | The HTTP status code used to abort the request. The value mu…
        percentage  = 0      # number | optional | The percentage of traffic (connections/operations/requests) …

      }

      delay { # list [0..1]
        percentage = 0      # number | optional | The percentage of traffic (connections/operations/requests) …

        fixed_delay { # list [0..1]
          nanos   = 0      # number | optional | Span of time that's a fraction of a second at nanosecond res…
          seconds = ""     # string | optional | Span of time at a resolution of a second. Must be from 0 to …

        }

      }

    }

    request_mirror_policy { # list [0..1]
      backend_service = ""     # string | optional | The full or partial URL to the RegionBackendService resource…

    }

    retry_policy { # list [0..1]
      num_retries      = 0      # number | optional | Specifies the allowed number retries. This number must be > …
      retry_conditions = []     # list(string) | optional | Specifies one or more conditions when this retry policy appl…

      per_try_timeout { # list [0..1]
        nanos   = 0      # number | optional | Span of time that's a fraction of a second at nanosecond res…
        seconds = ""     # string | optional | Span of time at a resolution of a second. Must be from 0 to …

      }

    }

    timeout { # list [0..1]
      nanos   = 0      # number | optional | Span of time that's a fraction of a second at nanosecond res…
      seconds = ""     # string | optional | Span of time at a resolution of a second. Must be from 0 to …

    }

    url_rewrite { # list [0..1]
      host_rewrite        = ""     # string | optional | Before forwarding the request to the selected service, the r…
      path_prefix_rewrite = ""     # string | optional | Before forwarding the request to the selected backend servic…

    }

    weighted_backend_services { # list
      backend_service = ""     # string | optional | The full or partial URL to the default BackendService resour…
      weight          = 0      # number | optional | Specifies the fraction of traffic sent to a backend service,…

      header_action { # list [0..1]
        request_headers_to_remove  = []     # list(string) | optional | A list of header names for headers that need to be removed f…
        response_headers_to_remove = []     # list(string) | optional | A list of header names for headers that need to be removed f…

        request_headers_to_add { # list
          header_name  = ""     # string | optional | The name of the header.
          header_value = ""     # string | optional | The value of the header to add.
          replace      = false  # bool | optional | If false, headerValue is appended to any values that already…

        }

        response_headers_to_add { # list
          header_name  = ""     # string | optional | The name of the header.
          header_value = ""     # string | optional | The value of the header to add.
          replace      = false  # bool | optional | If false, headerValue is appended to any values that already…

        }

      }

    }

  }

  default_url_redirect { # list [0..1]
    strip_query            = false  # bool | required | If set to true, any accompanying query portion of the origin…
    host_redirect          = ""     # string | optional | The host that will be used in the redirect response instead …
    https_redirect         = false  # bool | optional | If set to true, the URL scheme in the redirected request is …
    path_redirect          = ""     # string | optional | The path that will be used in the redirect response instead …
    prefix_redirect        = ""     # string | optional | The prefix that replaces the prefixMatch specified in the Ht…
    redirect_response_code = ""     # string | optional | The HTTP Status code to use for this RedirectAction. Support…

  }

  host_rule { # set
    hosts        = []     # set(string) | required | The list of host patterns to match. They must be valid hostn…
    path_matcher = ""     # string | required | The name of the PathMatcher to use to match the path portion…
    description  = ""     # string | optional | An optional description of this HostRule. Provide this prope…

  }

  path_matcher { # list
    name            = ""     # string | required | The name to which this PathMatcher is referred by the HostRu…
    default_service = ""     # string | optional | A reference to a RegionBackendService resource. This will be…
    description     = ""     # string | optional | An optional description of this resource.

    default_url_redirect { # list [0..1]
      strip_query            = false  # bool | required | If set to true, any accompanying query portion of the origin…
      host_redirect          = ""     # string | optional | The host that will be used in the redirect response instead …
      https_redirect         = false  # bool | optional | If set to true, the URL scheme in the redirected request is …
      path_redirect          = ""     # string | optional | The path that will be used in the redirect response instead …
      prefix_redirect        = ""     # string | optional | The prefix that replaces the prefixMatch specified in the Ht…
      redirect_response_code = ""     # string | optional | The HTTP Status code to use for this RedirectAction. Support…

    }

    path_rule { # list
      paths   = []     # set(string) | required | The list of path patterns to match. Each must start with / a…
      service = ""     # string | optional | The region backend service resource to which traffic is dire…

      route_action { # list [0..1]

        cors_policy { # list [0..1]
          disabled             = false  # bool | required | If true, specifies the CORS policy is disabled.
          allow_credentials    = false  # bool | optional | In response to a preflight request, setting this to true ind…
          allow_headers        = []     # list(string) | optional | Specifies the content for the Access-Control-Allow-Headers h…
          allow_methods        = []     # list(string) | optional | Specifies the content for the Access-Control-Allow-Methods h…
          allow_origin_regexes = []     # list(string) | optional | Specifies the regular expression patterns that match allowed…
          allow_origins        = []     # list(string) | optional | Specifies the list of origins that will be allowed to do COR…
          expose_headers       = []     # list(string) | optional | Specifies the content for the Access-Control-Expose-Headers …
          max_age              = 0      # number | optional | Specifies how long the results of a preflight request can be…

        }

        fault_injection_policy { # list [0..1]

          abort { # list [0..1]
            http_status = 0      # number | required | The HTTP status code used to abort the request. The value mu…
            percentage  = 0      # number | required | The percentage of traffic (connections/operations/requests) …

          }

          delay { # list [0..1]
            percentage = 0      # number | required | The percentage of traffic (connections/operations/requests) …

            fixed_delay { # list [1..1]
              seconds = ""     # string | required | Span of time at a resolution of a second. Must be from 0 to …
              nanos   = 0      # number | optional | Span of time that's a fraction of a second at nanosecond res…

            }

          }

        }

        request_mirror_policy { # list [0..1]
          backend_service = ""     # string | required | The RegionBackendService resource being mirrored to.

        }

        retry_policy { # list [0..1]
          num_retries      = 0      # number | optional | Specifies the allowed number retries. This number must be > …
          retry_conditions = []     # list(string) | optional | Specifies one or more conditions when this retry rule applie…

          per_try_timeout { # list [0..1]
            seconds = ""     # string | required | Span of time at a resolution of a second. Must be from 0 to …
            nanos   = 0      # number | optional | Span of time that's a fraction of a second at nanosecond res…

          }

        }

        timeout { # list [0..1]
          seconds = ""     # string | required | Span of time at a resolution of a second. Must be from 0 to …
          nanos   = 0      # number | optional | Span of time that's a fraction of a second at nanosecond res…

        }

        url_rewrite { # list [0..1]
          host_rewrite        = ""     # string | optional | Prior to forwarding the request to the selected service, the…
          path_prefix_rewrite = ""     # string | optional | Prior to forwarding the request to the selected backend serv…

        }

        weighted_backend_services { # list
          backend_service = ""     # string | required | The default RegionBackendService resource. Before forwarding…
          weight          = 0      # number | required | Specifies the fraction of traffic sent to backendService, co…

          header_action { # list [0..1]
            request_headers_to_remove  = []     # list(string) | optional | A list of header names for headers that need to be removed f…
            response_headers_to_remove = []     # list(string) | optional | A list of header names for headers that need to be removed f…

            request_headers_to_add { # list
              header_name  = ""     # string | required | The name of the header.
              header_value = ""     # string | required | The value of the header to add.
              replace      = false  # bool | required | If false, headerValue is appended to any values that already…

            }

            response_headers_to_add { # list
              header_name  = ""     # string | required | The name of the header.
              header_value = ""     # string | required | The value of the header to add.
              replace      = false  # bool | required | If false, headerValue is appended to any values that already…

            }

          }

        }

      }

      url_redirect { # list [0..1]
        strip_query            = false  # bool | required | If set to true, any accompanying query portion of the origin…
        host_redirect          = ""     # string | optional | The host that will be used in the redirect response instead …
        https_redirect         = false  # bool | optional | If set to true, the URL scheme in the redirected request is …
        path_redirect          = ""     # string | optional | The path that will be used in the redirect response instead …
        prefix_redirect        = ""     # string | optional | The prefix that replaces the prefixMatch specified in the Ht…
        redirect_response_code = ""     # string | optional | The HTTP Status code to use for this RedirectAction. Support…

      }

    }

    route_rules { # list
      priority = 0      # number | required | For routeRules within a given pathMatcher, priority determin…
      service  = ""     # string | optional | The region backend service resource to which traffic is dire…

      header_action { # list [0..1]
        request_headers_to_remove  = []     # list(string) | optional | A list of header names for headers that need to be removed f…
        response_headers_to_remove = []     # list(string) | optional | A list of header names for headers that need to be removed f…

        request_headers_to_add { # list
          header_name  = ""     # string | required | The name of the header.
          header_value = ""     # string | required | The value of the header to add.
          replace      = false  # bool | required | If false, headerValue is appended to any values that already…

        }

        response_headers_to_add { # list
          header_name  = ""     # string | required | The name of the header.
          header_value = ""     # string | required | The value of the header to add.
          replace      = false  # bool | required | If false, headerValue is appended to any values that already…

        }

      }

      match_rules { # list
        full_path_match     = ""     # string | optional | For satisfying the matchRule condition, the path of the requ…
        ignore_case         = false  # bool | optional | Specifies that prefixMatch and fullPathMatch matches are cas…
        path_template_match = ""     # string | optional | For satisfying the matchRule condition, the path of the requ…
        prefix_match        = ""     # string | optional | For satisfying the matchRule condition, the request's path m…
        regex_match         = ""     # string | optional | For satisfying the matchRule condition, the path of the requ…

        header_matches { # list
          header_name   = ""     # string | required | The name of the HTTP header to match. For matching against t…
          exact_match   = ""     # string | optional | The value should exactly match contents of exactMatch. Only …
          invert_match  = false  # bool | optional | If set to false, the headerMatch is considered a match if th…
          prefix_match  = ""     # string | optional | The value of the header must start with the contents of pref…
          present_match = false  # bool | optional | A header with the contents of headerName must exist. The mat…
          regex_match   = ""     # string | optional | The value of the header must match the regular expression sp…
          suffix_match  = ""     # string | optional | The value of the header must end with the contents of suffix…

          range_match { # list [0..1]
            range_end   = 0      # number | required | The end of the range (exclusive).
            range_start = 0      # number | required | The start of the range (inclusive).

          }

        }

        metadata_filters { # list
          filter_match_criteria = ""     # string | required | Specifies how individual filterLabel matches within the list…

          filter_labels { # list [1..64]
            name  = ""     # string | required | Name of metadata label. The name can have a maximum length o…
            value = ""     # string | required | The value of the label must match the specified value. value…

          }

        }

        query_parameter_matches { # list
          name          = ""     # string | required | The name of the query parameter to match. The query paramete…
          exact_match   = ""     # string | optional | The queryParameterMatch matches if the value of the paramete…
          present_match = false  # bool | optional | Specifies that the queryParameterMatch matches if the reques…
          regex_match   = ""     # string | optional | The queryParameterMatch matches if the value of the paramete…

        }

      }

      route_action { # list [0..1]

        cors_policy { # list [0..1]
          allow_credentials    = false  # bool | optional | In response to a preflight request, setting this to true ind…
          allow_headers        = []     # list(string) | optional | Specifies the content for the Access-Control-Allow-Headers h…
          allow_methods        = []     # list(string) | optional | Specifies the content for the Access-Control-Allow-Methods h…
          allow_origin_regexes = []     # list(string) | optional | Specifies the regular expression patterns that match allowed…
          allow_origins        = []     # list(string) | optional | Specifies the list of origins that will be allowed to do COR…
          disabled             = false  # bool | optional | If true, specifies the CORS policy is disabled. which indica…
          expose_headers       = []     # list(string) | optional | Specifies the content for the Access-Control-Expose-Headers …
          max_age              = 0      # number | optional | Specifies how long the results of a preflight request can be…

        }

        fault_injection_policy { # list [0..1]

          abort { # list [0..1]
            http_status = 0      # number | optional | The HTTP status code used to abort the request. The value mu…
            percentage  = 0      # number | optional | The percentage of traffic (connections/operations/requests) …

          }

          delay { # list [0..1]
            percentage = 0      # number | optional | The percentage of traffic (connections/operations/requests) …

            fixed_delay { # list [0..1]
              seconds = ""     # string | required | Span of time at a resolution of a second. Must be from 0 to …
              nanos   = 0      # number | optional | Span of time that's a fraction of a second at nanosecond res…

            }

          }

        }

        request_mirror_policy { # list [0..1]
          backend_service = ""     # string | required | The RegionBackendService resource being mirrored to.

        }

        retry_policy { # list [0..1]
          num_retries      = 0      # number | required | Specifies the allowed number retries. This number must be > …
          retry_conditions = []     # list(string) | optional | Specifies one or more conditions when this retry rule applie…

          per_try_timeout { # list [0..1]
            seconds = ""     # string | required | Span of time at a resolution of a second. Must be from 0 to …
            nanos   = 0      # number | optional | Span of time that's a fraction of a second at nanosecond res…

          }

        }

        timeout { # list [0..1]
          seconds = ""     # string | required | Span of time at a resolution of a second. Must be from 0 to …
          nanos   = 0      # number | optional | Span of time that's a fraction of a second at nanosecond res…

        }

        url_rewrite { # list [0..1]
          host_rewrite          = ""     # string | optional | Prior to forwarding the request to the selected service, the…
          path_prefix_rewrite   = ""     # string | optional | Prior to forwarding the request to the selected backend serv…
          path_template_rewrite = ""     # string | optional | Prior to forwarding the request to the selected origin, if t…

        }

        weighted_backend_services { # list
          backend_service = ""     # string | required | The default RegionBackendService resource. Before forwarding…
          weight          = 0      # number | required | Specifies the fraction of traffic sent to backendService, co…

          header_action { # list [0..1]
            request_headers_to_remove  = []     # list(string) | optional | A list of header names for headers that need to be removed f…
            response_headers_to_remove = []     # list(string) | optional | A list of header names for headers that need to be removed f…

            request_headers_to_add { # list
              header_name  = ""     # string | required | The name of the header.
              header_value = ""     # string | required | The value of the header to add.
              replace      = false  # bool | required | If false, headerValue is appended to any values that already…

            }

            response_headers_to_add { # list
              header_name  = ""     # string | required | The name of the header.
              header_value = ""     # string | required | The value of the header to add.
              replace      = false  # bool | required | If false, headerValue is appended to any values that already…

            }

          }

        }

      }

      url_redirect { # list [0..1]
        host_redirect          = ""     # string | optional | The host that will be used in the redirect response instead …
        https_redirect         = false  # bool | optional | If set to true, the URL scheme in the redirected request is …
        path_redirect          = ""     # string | optional | The path that will be used in the redirect response instead …
        prefix_redirect        = ""     # string | optional | The prefix that replaces the prefixMatch specified in the Ht…
        redirect_response_code = ""     # string | optional | The HTTP Status code to use for this RedirectAction. Support…
        strip_query            = false  # bool | optional | If set to true, any accompanying query portion of the origin…

      }

    }

  }

  test { # list
    host        = ""     # string | required | Host portion of the URL.
    path        = ""     # string | required | Path portion of the URL.
    service     = ""     # string | required | A reference to expected RegionBackendService resource the gi…
    description = ""     # string | optional | Description of this test case.

  }

  timeouts { # single
    create = ""     # string | optional
    delete = ""     # string | optional
    update = ""     # string | optional

  }

}

