# ┌──────────────────────────────────────────────────────────────┐
# │  resource: google_compute_global_address                       │
# └──────────────────────────────────────────────────────────────┘
resource "google_compute_global_address" "this" {

  name               = ""     # string | required | Name of the resource. Provided by the client when the resour…
  address            = ""     # string | optional+computed | The IP address or beginning of the address range represented…
  address_type       = ""     # string | optional | The type of the address to reserve.  * EXTERNAL indicates pu…
  description        = ""     # string | optional | An optional description of this resource.
  id                 = ""     # string | optional+computed
  ip_version         = ""     # string | optional | The IP Version that will be used by this address. The defaul…
  labels             = {}     # map(string) | optional | Labels to apply to this address.  A list of key->value pairs…
  network            = ""     # string | optional | The URL of the network in which to reserve the IP range. The…
  prefix_length      = 0      # number | optional+computed | The prefix length of the IP range. If not present, it means …
  project            = ""     # string | optional+computed
  purpose            = ""     # string | optional | The purpose of the resource. Possible values include:  * VPC…

  # creation_timestamp = ""     # string | computed | Creation timestamp in RFC3339 text format.
  # effective_labels   = {}     # map(string) | computed | All of labels (key/value pairs) present on the resource in G…
  # label_fingerprint  = ""     # string | computed | The fingerprint used for optimistic locking of this resource…
  # self_link          = ""     # string | computed
  # terraform_labels   = {}     # map(string) | computed | The combination of labels configured directly on the resourc…

  timeouts { # single
    create = ""     # string | optional
    delete = ""     # string | optional
    update = ""     # string | optional

  }

}

