# ┌──────────────────────────────────────────────────────────────┐
# │  resource: google_compute_region_network_firewall_policy_rule  │
# └──────────────────────────────────────────────────────────────┘
resource "google_compute_region_network_firewall_policy_rule" "this" {

  action                  = ""     # string | required | The Action to perform when the client connection triggers th…
  direction               = ""     # string | required | The direction in which this rule applies. Possible values: I…
  firewall_policy         = ""     # string | required | The firewall policy of the resource.
  priority                = 0      # number | required | An integer indicating the priority of a rule in the list. Th…
  description             = ""     # string | optional | An optional description for this resource.
  disabled                = false  # bool | optional | Denotes whether the firewall policy rule is disabled. When s…
  enable_logging          = false  # bool | optional | Denotes whether to enable logging for a particular rule. If …
  id                      = ""     # string | optional+computed
  project                 = ""     # string | optional+computed | The project for the resource
  region                  = ""     # string | optional+computed | The location of this resource.
  rule_name               = ""     # string | optional | An optional name for the rule. This field is not a unique id…
  security_profile_group  = ""     # string | optional | A fully-qualified URL of a SecurityProfileGroup resource. Ex…
  target_service_accounts = []     # list(string) | optional | A list of service accounts indicating the sets of instances …
  tls_inspect             = false  # bool | optional | Boolean flag indicating if the traffic should be TLS decrypt…

  # kind                    = ""     # string | computed | Type of the resource. Always `compute#firewallPolicyRule` fo…
  # rule_tuple_count        = 0      # number | computed | Calculation of the complexity of a single firewall policy ru…

  match { # list [1..1]
    dest_address_groups       = []     # list(string) | optional | Address groups which should be matched against the traffic d…
    dest_fqdns                = []     # list(string) | optional | Domain names that will be used to match against the resolved…
    dest_ip_ranges            = []     # list(string) | optional | CIDR IP address range. Maximum number of destination CIDR IP…
    dest_region_codes         = []     # list(string) | optional | The Unicode country codes whose IP addresses will be used to…
    dest_threat_intelligences = []     # list(string) | optional | Name of the Google Cloud Threat Intelligence list.
    src_address_groups        = []     # list(string) | optional | Address groups which should be matched against the traffic s…
    src_fqdns                 = []     # list(string) | optional | Domain names that will be used to match against the resolved…
    src_ip_ranges             = []     # list(string) | optional | CIDR IP address range. Maximum number of source CIDR IP rang…
    src_region_codes          = []     # list(string) | optional | The Unicode country codes whose IP addresses will be used to…
    src_threat_intelligences  = []     # list(string) | optional | Name of the Google Cloud Threat Intelligence list.

    layer4_configs { # list [1..*]
      ip_protocol = ""     # string | required | The IP protocol to which this rule applies. The protocol typ…
      ports       = []     # list(string) | optional | An optional list of ports to which this rule applies. This f…

    }

    src_secure_tags { # list
      name  = ""     # string | required | Name of the secure tag, created with TagManager's TagValue A…

      # state = ""     # string | computed | [Output Only] State of the secure tag, either `EFFECTIVE` or…

    }

  }

  target_secure_tags { # list
    name  = ""     # string | required | Name of the secure tag, created with TagManager's TagValue A…

    # state = ""     # string | computed | [Output Only] State of the secure tag, either `EFFECTIVE` or…

  }

  timeouts { # single
    create = ""     # string | optional
    delete = ""     # string | optional
    update = ""     # string | optional

  }

}

