# ┌──────────────────────────────────────────────────────────────┐
# │  resource: google_monitoring_notification_channel              │
# └──────────────────────────────────────────────────────────────┘
resource "google_monitoring_notification_channel" "this" {

  type                = ""     # string | required | The type of the notification channel. This field matches the…
  description         = ""     # string | optional | An optional human-readable description of this notification …
  display_name        = ""     # string | optional | An optional human-readable name for this notification channe…
  enabled             = false  # bool | optional | Whether notifications are forwarded to the described channel…
  force_delete        = false  # bool | optional | If true, the notification channel will be deleted regardless…
  id                  = ""     # string | optional+computed
  labels              = {}     # map(string) | optional | Configuration fields that define the channel and its behavio…
  project             = ""     # string | optional+computed
  user_labels         = {}     # map(string) | optional | User-supplied key/value data that does not need to conform t…

  # name                = ""     # string | computed | The full REST resource name for this channel. The syntax is:…
  # verification_status = ""     # string | computed | Indicates whether this channel has been verified or not. On …

  sensitive_labels { # list [0..1]
    auth_token  = ""     # string | optional+sensitive | An authorization token for a notification channel. Channel t…
    password    = ""     # string | optional+sensitive | An password for a notification channel. Channel types that s…
    service_key = ""     # string | optional+sensitive | An servicekey token for a notification channel. Channel type…

  }

  timeouts { # single
    create = ""     # string | optional
    delete = ""     # string | optional
    update = ""     # string | optional

  }

}

