# ┌──────────────────────────────────────────────────────────────┐
# │  resource: google_cloud_scheduler_job                          │
# └──────────────────────────────────────────────────────────────┘
resource "google_cloud_scheduler_job" "this" {

  name             = ""     # string | required | The name of the job.
  attempt_deadline = ""     # string | optional | The deadline for job attempts. If the request handler does n…
  description      = ""     # string | optional | A human-readable description for the job. This string must n…
  id               = ""     # string | optional+computed
  paused           = false  # bool | optional+computed | Sets the job to a paused state. Jobs default to being enable…
  project          = ""     # string | optional+computed
  region           = ""     # string | optional+computed | Region where the scheduler job resides. If it is not provide…
  schedule         = ""     # string | optional | Describes the schedule on which the job will be executed.
  time_zone        = ""     # string | optional | Specifies the time zone to be used in interpreting schedule.…

  # state            = ""     # string | computed | State of the job.

  app_engine_http_target { # list [0..1]
    relative_uri = ""     # string | required | The relative URI. The relative URL must begin with "/" and m…
    body         = ""     # string | optional | HTTP request body. A request body is allowed only if the HTT…
    headers      = {}     # map(string) | optional | HTTP request headers. This map contains the header field nam…
    http_method  = ""     # string | optional | Which HTTP method to use for the request.

    app_engine_routing { # list [0..1]
      instance = ""     # string | optional | App instance. By default, the job is sent to an instance whi…
      service  = ""     # string | optional | App service. By default, the job is sent to the service whic…
      version  = ""     # string | optional | App version. By default, the job is sent to the version whic…

    }

  }

  http_target { # list [0..1]
    uri         = ""     # string | required | The full URI path that the request will be sent to.
    body        = ""     # string | optional | HTTP request body. A request body is allowed only if the HTT…
    headers     = {}     # map(string) | optional | This map contains the header field names and values. Repeate…
    http_method = ""     # string | optional | Which HTTP method to use for the request.

    oauth_token { # list [0..1]
      service_account_email = ""     # string | required | Service account email to be used for generating OAuth token.…
      scope                 = ""     # string | optional | OAuth scope to be used for generating OAuth access token. If…

    }

    oidc_token { # list [0..1]
      service_account_email = ""     # string | required | Service account email to be used for generating OAuth token.…
      audience              = ""     # string | optional | Audience to be used when generating OIDC token. If not speci…

    }

  }

  pubsub_target { # list [0..1]
    topic_name = ""     # string | required | The full resource name for the Cloud Pub/Sub topic to which …
    attributes = {}     # map(string) | optional | Attributes for PubsubMessage. Pubsub message must contain ei…
    data       = ""     # string | optional | The message payload for PubsubMessage. Pubsub message must c…

  }

  retry_config { # list [0..1]
    max_backoff_duration = ""     # string | optional+computed | The maximum amount of time to wait before retrying a job aft…
    max_doublings        = 0      # number | optional+computed | The time between retries will double maxDoublings times. A j…
    max_retry_duration   = ""     # string | optional+computed | The time limit for retrying a failed job, measured from time…
    min_backoff_duration = ""     # string | optional+computed | The minimum amount of time to wait before retrying a job aft…
    retry_count          = 0      # number | optional+computed | The number of attempts that the system will make to run a jo…

  }

  timeouts { # single
    create = ""     # string | optional
    delete = ""     # string | optional
    update = ""     # string | optional

  }

}

