# ┌──────────────────────────────────────────────────────────────┐
# │  resource: google_bigtable_instance                            │
# └──────────────────────────────────────────────────────────────┘
resource "google_bigtable_instance" "this" {

  name                = ""     # string | required | The name (also called Instance Id in the Cloud Console) of t…
  deletion_protection = false  # bool | optional |       When the field is set to true or unset in Terraform st…
  display_name        = ""     # string | optional+computed | The human-readable display name of the Bigtable instance. De…
  force_destroy       = false  # bool | optional | When deleting a BigTable instance, this boolean option will …
  id                  = ""     # string | optional+computed
  instance_type       = ""     # string | optional+DEPRECATED | The instance type to create. One of "DEVELOPMENT" or "PRODUC…
  labels              = {}     # map(string) | optional | A mapping of labels to assign to the resource. 				 				**No…
  project             = ""     # string | optional+computed | The ID of the project in which the resource belongs. If it i…

  # effective_labels    = {}     # map(string) | computed | All of labels (key/value pairs) present on the resource in G…
  # terraform_labels    = {}     # map(string) | computed | The combination of labels configured directly on the resourc…

  cluster { # list
    cluster_id   = ""     # string | required | The ID of the Cloud Bigtable cluster. Must be 6-30 character…
    kms_key_name = ""     # string | optional+computed | Describes the Cloud KMS encryption key that will be used to …
    num_nodes    = 0      # number | optional+computed | The number of nodes in the cluster. If no value is set, Clou…
    storage_type = ""     # string | optional | The storage type to use. One of "SSD" or "HDD". Defaults to …
    zone         = ""     # string | optional+computed | The zone to create the Cloud Bigtable cluster in. Each clust…

    # state        = ""     # string | computed | The state of the cluster

    autoscaling_config { # list [0..1]
      cpu_target     = 0      # number | required | The target CPU utilization for autoscaling. Value must be be…
      max_nodes      = 0      # number | required | The maximum number of nodes for autoscaling.
      min_nodes      = 0      # number | required | The minimum number of nodes for autoscaling.
      storage_target = 0      # number | optional+computed | The target storage utilization for autoscaling, in GB, for e…

    }

  }

  timeouts { # single
    create = ""     # string | optional
    read   = ""     # string | optional
    update = ""     # string | optional

  }

}

