# ┌──────────────────────────────────────────────────────────────┐
# │  resource: google_compute_forwarding_rule                      │
# └──────────────────────────────────────────────────────────────┘
resource "google_compute_forwarding_rule" "this" {

  name                    = ""     # string | required | Name of the resource; provided by the client when the resour…
  all_ports               = false  # bool | optional | The 'ports', 'portRange', and 'allPorts' fields are mutually…
  allow_global_access     = false  # bool | optional | This field is used along with the 'backend_service' field fo…
  allow_psc_global_access = false  # bool | optional | This is used in PSC consumer ForwardingRule to control wheth…
  backend_service         = ""     # string | optional | Identifies the backend service to which the forwarding rule …
  description             = ""     # string | optional | An optional description of this resource. Provide this prope…
  id                      = ""     # string | optional+computed
  ip_address              = ""     # string | optional+computed | IP address for which this forwarding rule accepts traffic. W…
  ip_protocol             = ""     # string | optional+computed | The IP protocol to which this rule applies.  For protocol fo…
  ip_version              = ""     # string | optional+computed | The IP address version that will be used by this forwarding …
  is_mirroring_collector  = false  # bool | optional | Indicates whether or not this load balancer can be used as a…
  labels                  = {}     # map(string) | optional | Labels to apply to this forwarding rule.  A list of key->val…
  load_balancing_scheme   = ""     # string | optional | Specifies the forwarding rule type.  For more information ab…
  network                 = ""     # string | optional+computed | This field is not used for external load balancing.  For Int…
  network_tier            = ""     # string | optional+computed | This signifies the networking tier used for configuring this…
  no_automate_dns_zone    = false  # bool | optional | This is used in PSC consumer ForwardingRule to control wheth…
  port_range              = ""     # string | optional+computed | The 'ports', 'portRange', and 'allPorts' fields are mutually…
  ports                   = []     # set(string) | optional | The 'ports', 'portRange', and 'allPorts' fields are mutually…
  project                 = ""     # string | optional+computed
  recreate_closed_psc     = false  # bool | optional | This is used in PSC consumer ForwardingRule to make terrafor…
  region                  = ""     # string | optional+computed | A reference to the region where the regional forwarding rule…
  service_label           = ""     # string | optional | An optional prefix to the service name for this Forwarding R…
  source_ip_ranges        = []     # list(string) | optional | If not empty, this Forwarding Rule will only forward the tra…
  subnetwork              = ""     # string | optional+computed | This field identifies the subnetwork that the load balanced …
  target                  = ""     # string | optional | The URL of the target resource to receive the matched traffi…

  # base_forwarding_rule    = ""     # string | computed | [Output Only] The URL for the corresponding base Forwarding …
  # creation_timestamp      = ""     # string | computed | Creation timestamp in RFC3339 text format.
  # effective_labels        = {}     # map(string) | computed | All of labels (key/value pairs) present on the resource in G…
  # forwarding_rule_id      = 0      # number | computed | The unique identifier number for the resource. This identifi…
  # label_fingerprint       = ""     # string | computed | The fingerprint used for optimistic locking of this resource…
  # psc_connection_id       = ""     # string | computed | The PSC connection id of the PSC Forwarding Rule.
  # psc_connection_status   = ""     # string | computed | The PSC connection status of the PSC Forwarding Rule. Possib…
  # self_link               = ""     # string | computed
  # service_name            = ""     # string | computed | The internal fully qualified service name for this Forwardin…
  # terraform_labels        = {}     # map(string) | computed | The combination of labels configured directly on the resourc…

  service_directory_registrations { # list [0..1]
    namespace = ""     # string | optional+computed | Service Directory namespace to register the forwarding rule …
    service   = ""     # string | optional | Service Directory service to register the forwarding rule un…

  }

  timeouts { # single
    create = ""     # string | optional
    delete = ""     # string | optional
    update = ""     # string | optional

  }

}

