# ┌──────────────────────────────────────────────────────────────┐
# │  resource: google_dataproc_cluster                             │
# └──────────────────────────────────────────────────────────────┘
resource "google_dataproc_cluster" "this" {

  name                          = ""     # string | required | The name of the cluster, unique within the project and zone.
  graceful_decommission_timeout = ""     # string | optional | The timeout duration which allows graceful decomissioning wh…
  id                            = ""     # string | optional+computed
  labels                        = {}     # map(string) | optional | The list of the labels (key/value pairs) configured on the r…
  project                       = ""     # string | optional+computed | The ID of the project in which the cluster will exist. If it…
  region                        = ""     # string | optional | The region in which the cluster and associated nodes will be…

  # effective_labels              = {}     # map(string) | computed | All of labels (key/value pairs) present on the resource in G…
  # terraform_labels              = {}     # map(string) | computed | The combination of labels configured directly on the resourc…

  cluster_config { # list [0..1]
    staging_bucket = ""     # string | optional | The Cloud Storage staging bucket used to stage files, such a…
    temp_bucket    = ""     # string | optional+computed | The Cloud Storage temp bucket used to store ephemeral cluste…

    # bucket         = ""     # string | computed |  The name of the cloud storage bucket ultimately used to hou…

    autoscaling_config { # list [0..1]
      policy_uri = ""     # string | required | The autoscaling policy used by the cluster.

    }

    auxiliary_node_groups { # list
      node_group_id = ""     # string | optional+computed | A node group ID. Generated if not specified. The ID must con…

      node_group { # list [1..*]
        roles = []     # list(string) | required | Node group roles.

        # name  = ""     # string | computed | The Node group resource name.

        node_group_config { # list [0..1]
          machine_type     = ""     # string | optional+computed | The name of a Google Compute Engine machine type to create f…
          min_cpu_platform = ""     # string | optional+computed | The name of a minimum generation of CPU family for the auxil…
          num_instances    = 0      # number | optional+computed | Specifies the number of auxiliary nodes to create. If not sp…

          # instance_names   = []     # list(string) | computed | List of auxiliary node group instance names which have been …

          accelerators { # set
            accelerator_count = 0      # number | required | The number of the accelerator cards of this type exposed to …
            accelerator_type  = ""     # string | required | The short name of the accelerator type to expose to this ins…

          }

          disk_config { # list [0..1]
            boot_disk_size_gb   = 0      # number | optional+computed | Size of the primary disk attached to each node, specified in…
            boot_disk_type      = ""     # string | optional | The disk type of the primary disk attached to each node. Suc…
            local_ssd_interface = ""     # string | optional | Interface type of local SSDs (default is "scsi"). Valid valu…
            num_local_ssds      = 0      # number | optional+computed | The amount of local SSD disks that will be attached to each …

          }

        }

      }

    }

    dataproc_metric_config { # list [0..1]

      metrics { # list [1..*]
        metric_source    = ""     # string | required | A source for the collection of Dataproc OSS metrics (see [av…
        metric_overrides = []     # set(string) | optional | Specify one or more [available OSS metrics] (https://cloud.g…

      }

    }

    encryption_config { # list [0..1]
      kms_key_name = ""     # string | required | The Cloud KMS key name to use for PD disk encryption for all…

    }

    endpoint_config { # list [0..1]
      enable_http_port_access = false  # bool | required | The flag to enable http access to specific ports on the clus…

      # http_ports              = {}     # map(string) | computed | The map of port descriptions to URLs. Will only be populated…

    }

    gce_cluster_config { # list [0..1]
      internal_ip_only       = false  # bool | optional | By default, clusters are not restricted to internal IP addre…
      metadata               = {}     # map(string) | optional | A map of the Compute Engine metadata entries to add to all i…
      network                = ""     # string | optional+computed | The name or self_link of the Google Compute Engine network t…
      service_account        = ""     # string | optional | The service account to be used by the Node VMs. If not speci…
      service_account_scopes = []     # set(string) | optional+computed | The set of Google API scopes to be made available on all of …
      subnetwork             = ""     # string | optional | The name or self_link of the Google Compute Engine subnetwor…
      tags                   = []     # set(string) | optional | The list of instance tags applied to instances in the cluste…
      zone                   = ""     # string | optional+computed | The GCP zone where your data is stored and used (i.e. where …

      node_group_affinity { # list [0..1]
        node_group_uri = ""     # string | required | The URI of a sole-tenant that the cluster will be created on…

      }

      reservation_affinity { # list [0..1]
        consume_reservation_type = ""     # string | optional | Type of reservation to consume.
        key                      = ""     # string | optional | Corresponds to the label key of reservation resource.
        values                   = []     # set(string) | optional | Corresponds to the label values of reservation resource.

      }

      shielded_instance_config { # list [0..1]
        enable_integrity_monitoring = false  # bool | optional | Defines whether instances have integrity monitoring enabled.
        enable_secure_boot          = false  # bool | optional | Defines whether instances have Secure Boot enabled.
        enable_vtpm                 = false  # bool | optional | Defines whether instances have the vTPM enabled.

      }

    }

    initialization_action { # list
      script      = ""     # string | required | The script to be executed during initialization of the clust…
      timeout_sec = 0      # number | optional | The maximum duration (in seconds) which script is allowed to…

    }

    lifecycle_config { # list [0..1]
      auto_delete_time = ""     # string | optional | The time when cluster will be auto-deleted. A timestamp in R…
      idle_delete_ttl  = ""     # string | optional | The duration to keep the cluster alive while idling (no jobs…

      # idle_start_time  = ""     # string | computed | Time when the cluster became idle (most recent job finished)…

    }

    master_config { # list [0..1]
      image_uri        = ""     # string | optional+computed | The URI for the image to use for this master
      machine_type     = ""     # string | optional+computed | The name of a Google Compute Engine machine type to create f…
      min_cpu_platform = ""     # string | optional+computed | The name of a minimum generation of CPU family for the maste…
      num_instances    = 0      # number | optional+computed | Specifies the number of master nodes to create. If not speci…

      # instance_names   = []     # list(string) | computed | List of master instance names which have been assigned to th…

      accelerators { # set
        accelerator_count = 0      # number | required | The number of the accelerator cards of this type exposed to …
        accelerator_type  = ""     # string | required | The short name of the accelerator type to expose to this ins…

      }

      disk_config { # list [0..1]
        boot_disk_size_gb   = 0      # number | optional+computed | Size of the primary disk attached to each node, specified in…
        boot_disk_type      = ""     # string | optional | The disk type of the primary disk attached to each node. Suc…
        local_ssd_interface = ""     # string | optional | Interface type of local SSDs (default is "scsi"). Valid valu…
        num_local_ssds      = 0      # number | optional+computed | The amount of local SSD disks that will be attached to each …

      }

    }

    metastore_config { # list [0..1]
      dataproc_metastore_service = ""     # string | required | Resource name of an existing Dataproc Metastore service.

    }

    preemptible_worker_config { # list [0..1]
      num_instances  = 0      # number | optional+computed | Specifies the number of preemptible nodes to create. Default…
      preemptibility = ""     # string | optional | Specifies the preemptibility of the secondary nodes. Default…

      # instance_names = []     # list(string) | computed | List of preemptible instance names which have been assigned …

      disk_config { # list [0..1]
        boot_disk_size_gb   = 0      # number | optional+computed | Size of the primary disk attached to each preemptible worker…
        boot_disk_type      = ""     # string | optional | The disk type of the primary disk attached to each preemptib…
        local_ssd_interface = ""     # string | optional | Interface type of local SSDs (default is "scsi"). Valid valu…
        num_local_ssds      = 0      # number | optional+computed | The amount of local SSD disks that will be attached to each …

      }

      instance_flexibility_policy { # list [0..1]

        # instance_selection_results = [  # list(object)
        #   {
        #     machine_type = ""
        #     vm_count = 0
        #   }
        # ]

        instance_selection_list { # list
          machine_types = []     # list(string) | optional+computed | Full machine-type names, e.g. "n1-standard-16".
          rank          = 0      # number | optional+computed | Preference of this instance selection. Lower number means hi…

        }

      }

    }

    security_config { # list [0..1]

      kerberos_config { # list [1..1]
        kms_key_uri                           = ""     # string | required | The uri of the KMS key used to encrypt various sensitive fil…
        root_principal_password_uri           = ""     # string | required | The cloud Storage URI of a KMS encrypted file containing the…
        cross_realm_trust_admin_server        = ""     # string | optional | The admin server (IP or hostname) for the remote trusted rea…
        cross_realm_trust_kdc                 = ""     # string | optional | The KDC (IP or hostname) for the remote trusted realm in a c…
        cross_realm_trust_realm               = ""     # string | optional | The remote realm the Dataproc on-cluster KDC will trust, sho…
        cross_realm_trust_shared_password_uri = ""     # string | optional | The Cloud Storage URI of a KMS encrypted file containing the…
        enable_kerberos                       = false  # bool | optional | Flag to indicate whether to Kerberize the cluster.
        kdc_db_key_uri                        = ""     # string | optional | The Cloud Storage URI of a KMS encrypted file containing the…
        key_password_uri                      = ""     # string | optional | The Cloud Storage URI of a KMS encrypted file containing the…
        keystore_password_uri                 = ""     # string | optional | The Cloud Storage URI of a KMS encrypted file containing the…
        keystore_uri                          = ""     # string | optional | The Cloud Storage URI of the keystore file used for SSL encr…
        realm                                 = ""     # string | optional | The name of the on-cluster Kerberos realm. If not specified,…
        tgt_lifetime_hours                    = 0      # number | optional | The lifetime of the ticket granting ticket, in hours.
        truststore_password_uri               = ""     # string | optional | The Cloud Storage URI of a KMS encrypted file containing the…
        truststore_uri                        = ""     # string | optional | The Cloud Storage URI of the truststore file used for SSL en…

      }

    }

    software_config { # list [0..1]
      image_version       = ""     # string | optional+computed | The Cloud Dataproc image version to use for the cluster - th…
      optional_components = []     # set(string) | optional | The set of optional components to activate on the cluster.
      override_properties = {}     # map(string) | optional | A list of override and additional properties (key/value pair…

      # properties          = {}     # map(string) | computed | A list of the properties used to set the daemon config files…

    }

    worker_config { # list [0..1]
      image_uri         = ""     # string | optional+computed | The URI for the image to use for this master/worker
      machine_type      = ""     # string | optional+computed | The name of a Google Compute Engine machine type to create f…
      min_cpu_platform  = ""     # string | optional+computed | The name of a minimum generation of CPU family for the maste…
      min_num_instances = 0      # number | optional+computed | The minimum number of primary worker instances to create.
      num_instances     = 0      # number | optional+computed | Specifies the number of worker nodes to create. If not speci…

      # instance_names    = []     # list(string) | computed | List of master/worker instance names which have been assigne…

      accelerators { # set
        accelerator_count = 0      # number | required | The number of the accelerator cards of this type exposed to …
        accelerator_type  = ""     # string | required | The short name of the accelerator type to expose to this ins…

      }

      disk_config { # list [0..1]
        boot_disk_size_gb   = 0      # number | optional+computed | Size of the primary disk attached to each node, specified in…
        boot_disk_type      = ""     # string | optional | The disk type of the primary disk attached to each node. Suc…
        local_ssd_interface = ""     # string | optional | Interface type of local SSDs (default is "scsi"). Valid valu…
        num_local_ssds      = 0      # number | optional+computed | The amount of local SSD disks that will be attached to each …

      }

    }

  }

  timeouts { # single
    create = ""     # string | optional
    delete = ""     # string | optional
    update = ""     # string | optional

  }

  virtual_cluster_config { # list [0..1]
    staging_bucket = ""     # string | optional | A Cloud Storage bucket used to stage job dependencies, confi…

    auxiliary_services_config { # list [0..1]

      metastore_config { # list [0..1]
        dataproc_metastore_service = ""     # string | optional | The Hive Metastore configuration for this workload.

      }

      spark_history_server_config { # list [0..1]
        dataproc_cluster = ""     # string | optional | Resource name of an existing Dataproc Cluster to act as a Sp…

      }

    }

    kubernetes_cluster_config { # list [0..1]
      kubernetes_namespace = ""     # string | optional | A namespace within the Kubernetes cluster to deploy into. If…

      gke_cluster_config { # list [1..1]
        gke_cluster_target = ""     # string | optional | A target GKE cluster to deploy to. It must be in the same pr…

        node_pool_target { # list
          node_pool = ""     # string | required | The target GKE node pool. Format: 'projects/{project}/locati…
          roles     = []     # set(string) | required | The roles associated with the GKE node pool.

          node_pool_config { # list [0..1]
            locations = []     # set(string) | required | The list of Compute Engine zones where node pool nodes assoc…

            autoscaling { # list [0..1]
              max_node_count = 0      # number | optional | The maximum number of nodes in the node pool. Must be >= min…
              min_node_count = 0      # number | optional | The minimum number of nodes in the node pool. Must be >= 0 a…

            }

            config { # list [0..1]
              local_ssd_count  = 0      # number | optional | The minimum number of nodes in the node pool. Must be >= 0 a…
              machine_type     = ""     # string | optional | The name of a Compute Engine machine type.
              min_cpu_platform = ""     # string | optional | Minimum CPU platform to be used by this instance. The instan…
              preemptible      = false  # bool | optional | Whether the nodes are created as preemptible VM instances. P…
              spot             = false  # bool | optional | Spot flag for enabling Spot VM, which is a rebrand of the ex…

            }

          }

        }

      }

      kubernetes_software_config { # list [1..1]
        component_version = {}     # map(string) | required | The components that should be installed in this Dataproc clu…
        properties        = {}     # map(string) | optional+computed | The properties to set on daemon config files. Property keys …

      }

    }

  }

}

