# ┌──────────────────────────────────────────────────────────────┐
# │  resource: google_endpoints_service                            │
# └──────────────────────────────────────────────────────────────┘
resource "google_endpoints_service" "this" {

  service_name         = ""     # string | required | The name of the service. Usually of the form $apiname.endpoi…
  grpc_config          = ""     # string | optional | The full text of the Service Config YAML file (Example locat…
  id                   = ""     # string | optional+computed
  openapi_config       = ""     # string | optional | The full text of the OpenAPI YAML configuration as described…
  project              = ""     # string | optional+computed | The project ID that the service belongs to. If not provided,…
  protoc_output_base64 = ""     # string | optional | The full contents of the Service Descriptor File generated b…

  # apis = [  # list(object)
  #   {
  #     methods = [  # list(object)
  #       {
  #         name = ""
  #         request_type = ""
  #         response_type = ""
  #         syntax = ""
  #       }
  #     ]
  #     name = ""
  #     syntax = ""
  #     version = ""
  #   }
  # ]
  # config_id            = ""     # string | computed | The autogenerated ID for the configuration that is rolled ou…
  # dns_address          = ""     # string | computed | The address at which the service can be found - usually the …
  # endpoints = [  # list(object)
  #   {
  #     address = ""
  #     name = ""
  #   }
  # ]

  timeouts { # single
    create = ""     # string | optional
    delete = ""     # string | optional
    update = ""     # string | optional

  }

}

