# ┌──────────────────────────────────────────────────────────────┐
# │  resource: google_network_connectivity_internal_range          │
# └──────────────────────────────────────────────────────────────┘
resource "google_network_connectivity_internal_range" "this" {

  name              = ""     # string | required | The name of the policy based route.
  network           = ""     # string | required | Fully-qualified URL of the network that this route applies t…
  peering           = ""     # string | required | The type of peering set for this internal range. Possible va…
  usage             = ""     # string | required | The type of usage set for this InternalRange. Possible value…
  description       = ""     # string | optional | An optional description of this resource.
  id                = ""     # string | optional+computed
  ip_cidr_range     = ""     # string | optional+computed | The IP range that this internal range defines.
  labels            = {}     # map(string) | optional | User-defined labels.   **Note**: This field is non-authorita…
  overlaps          = []     # list(string) | optional | Optional. Types of resources that are allowed to overlap wit…
  prefix_length     = 0      # number | optional | An alternate to ipCidrRange. Can be set when trying to creat…
  project           = ""     # string | optional+computed
  target_cidr_range = []     # list(string) | optional | Optional. Can be set to narrow down or pick a different addr…

  # effective_labels  = {}     # map(string) | computed | All of labels (key/value pairs) present on the resource in G…
  # terraform_labels  = {}     # map(string) | computed | The combination of labels configured directly on the resourc…
  # users             = []     # list(string) | computed | Output only. The list of resources that refer to this intern…

  timeouts { # single
    create = ""     # string | optional
    delete = ""     # string | optional
    update = ""     # string | optional

  }

}

