# ┌──────────────────────────────────────────────────────────────┐
# │  resource: google_vmwareengine_network_peering                 │
# └──────────────────────────────────────────────────────────────┘
resource "google_vmwareengine_network_peering" "this" {

  name                                = ""     # string | required | The ID of the Network Peering.
  peer_network                        = ""     # string | required | The relative resource name of the network to peer with a sta…
  peer_network_type                   = ""     # string | required | The type of the network to peer with the VMware Engine netwo…
  vmware_engine_network               = ""     # string | required | The relative resource name of the VMware Engine network. Spe…
  description                         = ""     # string | optional | User-provided description for this network peering.
  export_custom_routes                = false  # bool | optional | True if custom routes are exported to the peered network; fa…
  export_custom_routes_with_public_ip = false  # bool | optional | True if all subnet routes with a public IP address range are…
  id                                  = ""     # string | optional+computed
  import_custom_routes                = false  # bool | optional | True if custom routes are imported from the peered network; …
  import_custom_routes_with_public_ip = false  # bool | optional | True if custom routes are imported from the peered network; …
  project                             = ""     # string | optional+computed

  # create_time                         = ""     # string | computed | Creation time of this resource. A timestamp in RFC3339 UTC "…
  # state                               = ""     # string | computed | State of the network peering. This field has a value of 'ACT…
  # state_details                       = ""     # string | computed | Details about the current state of the network peering.
  # uid                                 = ""     # string | computed | System-generated unique identifier for the resource.
  # update_time                         = ""     # string | computed | Last updated time of this resource. A timestamp in RFC3339 U…
  # vmware_engine_network_canonical     = ""     # string | computed | The canonical name of the VMware Engine network in the form:…

  timeouts { # single
    create = ""     # string | optional
    delete = ""     # string | optional
    update = ""     # string | optional

  }

}

