# ┌──────────────────────────────────────────────────────────────┐
# │  resource: google_public_ca_external_account_key               │
# └──────────────────────────────────────────────────────────────┘
resource "google_public_ca_external_account_key" "this" {

  id          = ""     # string | optional+computed
  location    = ""     # string | optional | Location for the externalAccountKey. Currently only 'global'…
  project     = ""     # string | optional+computed

  # b64_mac_key = ""     # string | computed+sensitive | Base64-URL-encoded HS256 key. It is generated by the PublicC…
  # key_id      = ""     # string | computed+sensitive | It is generated by the PublicCertificateAuthorityService whe…
  # name        = ""     # string | computed | Resource name. projects/{project}/locations/{location}/exter…

  timeouts { # single
    create = ""     # string | optional
    delete = ""     # string | optional

  }

}

