# ┌──────────────────────────────────────────────────────────────┐
# │  resource: google_scc_v2_organization_scc_big_query_exports    │
# └──────────────────────────────────────────────────────────────┘
resource "google_scc_v2_organization_scc_big_query_exports" "this" {

  big_query_export_id = ""     # string | required | This must be unique within the organization.
  organization        = ""     # string | required | The organization whose Cloud Security Command Center the Big…
  dataset             = ""     # string | optional | The dataset to write findings' updates to. Its format is "pr…
  description         = ""     # string | optional | The description of the notification config (max of 1024 char…
  filter              = ""     # string | optional | Expression that defines the filter to apply across create/up…
  id                  = ""     # string | optional+computed
  location            = ""     # string | optional | location Id is provided by organization. If not provided, Us…
  name                = ""     # string | optional | The resource name of this export, in the format 'organizatio…

  # create_time         = ""     # string | computed | The time at which the BigQuery export was created. This fiel…
  # most_recent_editor  = ""     # string | computed | Email address of the user who last edited the BigQuery expor…
  # principal           = ""     # string | computed | The service account that needs permission to create table an…
  # update_time         = ""     # string | computed | The most recent time at which the BigQuery export was update…

  timeouts { # single
    create = ""     # string | optional
    delete = ""     # string | optional
    update = ""     # string | optional

  }

}

