# ┌──────────────────────────────────────────────────────────────┐
# │  resource: google_compute_router_nat                           │
# └──────────────────────────────────────────────────────────────┘
resource "google_compute_router_nat" "this" {

  name                                = ""     # string | required | Name of the NAT service. The name must be 1-63 characters lo…
  router                              = ""     # string | required | The name of the Cloud Router in which this NAT will be confi…
  source_subnetwork_ip_ranges_to_nat  = ""     # string | required | How NAT should be configured per Subnetwork. If 'ALL_SUBNETW…
  auto_network_tier                   = ""     # string | optional+computed | The network tier to use when automatically reserving NAT IP …
  drain_nat_ips                       = []     # set(string) | optional | A list of URLs of the IP resources to be drained. These IPs …
  enable_dynamic_port_allocation      = false  # bool | optional+computed | Enable Dynamic Port Allocation. If minPortsPerVm is set, min…
  enable_endpoint_independent_mapping = false  # bool | optional+computed | Enable endpoint independent mapping. For more information se…
  endpoint_types                      = []     # list(string) | optional+computed | Specifies the endpoint Types supported by the NAT Gateway. S…
  icmp_idle_timeout_sec               = 0      # number | optional | Timeout (in seconds) for ICMP connections. Defaults to 30s i…
  id                                  = ""     # string | optional+computed
  max_ports_per_vm                    = 0      # number | optional | Maximum number of ports allocated to a VM from this NAT. Thi…
  min_ports_per_vm                    = 0      # number | optional+computed | Minimum number of ports allocated to a VM from this NAT. Def…
  nat_ip_allocate_option              = ""     # string | optional | How external IPs should be allocated for this NAT. Valid val…
  nat_ips                             = []     # set(string) | optional | Self-links of NAT IPs. Only valid if natIpAllocateOption is …
  project                             = ""     # string | optional+computed
  region                              = ""     # string | optional+computed | Region where the router and NAT reside.
  tcp_established_idle_timeout_sec    = 0      # number | optional | Timeout (in seconds) for TCP established connections. Defaul…
  tcp_time_wait_timeout_sec           = 0      # number | optional | Timeout (in seconds) for TCP connections that are in TIME_WA…
  tcp_transitory_idle_timeout_sec     = 0      # number | optional | Timeout (in seconds) for TCP transitory connections. Default…
  udp_idle_timeout_sec                = 0      # number | optional | Timeout (in seconds) for UDP connections. Defaults to 30s if…

  log_config { # list [0..1]
    enable = false  # bool | required | Indicates whether or not to export logs.
    filter = ""     # string | required | Specifies the desired filtering of logs on this NAT. Possibl…

  }

  rules { # set
    match       = ""     # string | required | CEL expression that specifies the match condition that egres…
    rule_number = 0      # number | required | An integer uniquely identifying a rule in the list. The rule…
    description = ""     # string | optional | An optional description of this rule.

    action { # list [0..1]
      source_nat_active_ips = []     # set(string) | optional | A list of URLs of the IP resources used for this NAT rule. T…
      source_nat_drain_ips  = []     # set(string) | optional | A list of URLs of the IP resources to be drained. These IPs …

    }

  }

  subnetwork { # set
    name                     = ""     # string | required | Self-link of subnetwork to NAT
    source_ip_ranges_to_nat  = []     # set(string) | required | List of options for which source IPs in the subnetwork shoul…
    secondary_ip_range_names = []     # set(string) | optional | List of the secondary ranges of the subnetwork that are allo…

  }

  timeouts { # single
    create = ""     # string | optional
    delete = ""     # string | optional
    update = ""     # string | optional

  }

}

