# ┌──────────────────────────────────────────────────────────────┐
# │  resource: google_alloydb_backup                               │
# └──────────────────────────────────────────────────────────────┘
resource "google_alloydb_backup" "this" {

  backup_id             = ""     # string | required | The ID of the alloydb backup.
  cluster_name          = ""     # string | required | The full resource name of the backup source cluster (e.g., p…
  location              = ""     # string | required | The location where the alloydb backup should reside.
  annotations           = {}     # map(string) | optional | Annotations to allow client tools to store small amount of a…
  description           = ""     # string | optional | User-provided description of the backup.
  display_name          = ""     # string | optional | User-settable and human-readable display name for the Backup…
  id                    = ""     # string | optional+computed
  labels                = {}     # map(string) | optional | User-defined labels for the alloydb backup. An object contai…
  project               = ""     # string | optional+computed
  type                  = ""     # string | optional+computed | The backup type, which suggests the trigger for the backup. …

  # cluster_uid           = ""     # string | computed | Output only. The system-generated UID of the cluster which w…
  # create_time           = ""     # string | computed | Output only. Create time stamp. A timestamp in RFC3339 UTC "…
  # delete_time           = ""     # string | computed | Output only. Delete time stamp. A timestamp in RFC3339 UTC "…
  # effective_annotations = {}     # map(string) | computed | All of annotations (key/value pairs) present on the resource…
  # effective_labels      = {}     # map(string) | computed | All of labels (key/value pairs) present on the resource in G…
  # encryption_info = [  # list(object)
  #   {
  #     encryption_type = ""
  #     kms_key_versions = []  # list(string)
  #   }
  # ]
  # etag                  = ""     # string | computed | For Resource freshness validation (https://google.aip.dev/15…
  # expiry_quantity = [  # list(object)
  #   {
  #     retention_count = 0
  #     total_retention_count = 0
  #   }
  # ]
  # expiry_time           = ""     # string | computed | Output only. The time at which after the backup is eligible …
  # name                  = ""     # string | computed | Output only. The name of the backup resource with the format…
  # reconciling           = false  # bool | computed | Output only. Reconciling (https://google.aip.dev/128#reconci…
  # size_bytes            = ""     # string | computed | Output only. The size of the backup in bytes.
  # state                 = ""     # string | computed | Output only. The current state of the backup.
  # terraform_labels      = {}     # map(string) | computed | The combination of labels configured directly on the resourc…
  # uid                   = ""     # string | computed | Output only. The system-generated UID of the resource. The U…
  # update_time           = ""     # string | computed | Output only. Update time stamp. A timestamp in RFC3339 UTC "…

  encryption_config { # list [0..1]
    kms_key_name = ""     # string | optional | The fully-qualified resource name of the KMS key. Each Cloud…

  }

  timeouts { # single
    create = ""     # string | optional
    delete = ""     # string | optional
    update = ""     # string | optional

  }

}

