# ┌──────────────────────────────────────────────────────────────┐
# │  resource: google_service_account_key                          │
# └──────────────────────────────────────────────────────────────┘
resource "google_service_account_key" "this" {

  service_account_id = ""     # string | required | The ID of the parent service account of the key. This can be…
  id                 = ""     # string | optional+computed
  keepers            = {}     # map(string) | optional | Arbitrary map of values that, when changed, will trigger rec…
  key_algorithm      = ""     # string | optional | The algorithm used to generate the key, used only on create.…
  private_key_type   = ""     # string | optional
  public_key_data    = ""     # string | optional | A field that allows clients to upload their own public key. …
  public_key_type    = ""     # string | optional

  # name               = ""     # string | computed | The name used for this key pair
  # private_key        = ""     # string | computed+sensitive | The private key in JSON format, base64 encoded. This is what…
  # public_key         = ""     # string | computed | The public key, base64 encoded
  # valid_after        = ""     # string | computed | The key can be used after this timestamp. A timestamp in RFC…
  # valid_before       = ""     # string | computed | The key can be used before this timestamp. A timestamp in RF…

}

