# ┌──────────────────────────────────────────────────────────────┐
# │  resource: google_dialogflow_cx_security_settings              │
# └──────────────────────────────────────────────────────────────┘
resource "google_dialogflow_cx_security_settings" "this" {

  display_name          = ""     # string | required | The human-readable name of the security settings, unique wit…
  location              = ""     # string | required | The location these settings are located in. Settings can onl…
  deidentify_template   = ""     # string | optional | [DLP](https://cloud.google.com/dlp/docs) deidentify template…
  id                    = ""     # string | optional+computed
  inspect_template      = ""     # string | optional | [DLP](https://cloud.google.com/dlp/docs) inspect template na…
  project               = ""     # string | optional+computed
  purge_data_types      = []     # list(string) | optional | List of types of data to remove when retention settings trig…
  redaction_scope       = ""     # string | optional | Defines what types of data to redact. If not set, defaults t…
  redaction_strategy    = ""     # string | optional | Defines how we redact data. If not set, defaults to not reda…
  retention_strategy    = ""     # string | optional | Defines how long we retain persisted data that contains sens…
  retention_window_days = 0      # number | optional | Retains the data for the specified number of days. User must…

  # name                  = ""     # string | computed | The unique identifier of the settings. Format: projects/<Pro…

  audio_export_settings { # list [0..1]
    audio_export_pattern   = ""     # string | optional | Filename pattern for exported audio.
    audio_format           = ""     # string | optional | File format for exported audio file. Currently only in telep…
    enable_audio_redaction = false  # bool | optional | Enable audio redaction if it is true.
    gcs_bucket             = ""     # string | optional | Cloud Storage bucket to export audio record to. Setting this…

  }

  insights_export_settings { # list [0..1]
    enable_insights_export = false  # bool | required | If enabled, we will automatically exports conversations to I…

  }

  timeouts { # single
    create = ""     # string | optional
    delete = ""     # string | optional
    update = ""     # string | optional

  }

}

