# ┌──────────────────────────────────────────────────────────────┐
# │  data: google_monitoring_notification_channel                  │
# └──────────────────────────────────────────────────────────────┘
data "google_monitoring_notification_channel" "this" {

  display_name        = ""     # string | optional | An optional human-readable name for this notification channe…
  id                  = ""     # string | optional+computed
  labels              = {}     # map(string) | optional | Configuration fields that define the channel and its behavio…
  project             = ""     # string | optional
  type                = ""     # string | optional | The type of the notification channel. This field matches the…
  user_labels         = {}     # map(string) | optional | User-supplied key/value data that does not need to conform t…

  # description         = ""     # string | computed | An optional human-readable description of this notification …
  # enabled             = false  # bool | computed | Whether notifications are forwarded to the described channel…
  # force_delete        = false  # bool | computed | If true, the notification channel will be deleted regardless…
  # name                = ""     # string | computed | The full REST resource name for this channel. The syntax is:…
  # sensitive_labels = [  # list(object)
  #   {
  #     auth_token = ""
  #     password = ""
  #     service_key = ""
  #   }
  # ]
  # verification_status = ""     # string | computed | Indicates whether this channel has been verified or not. On …

}

