# ┌──────────────────────────────────────────────────────────────┐
# │  data: google_compute_router_nat                               │
# └──────────────────────────────────────────────────────────────┘
data "google_compute_router_nat" "this" {

  name                                = ""     # string | required | Name of the NAT service. The name must be 1-63 characters lo…
  router                              = ""     # string | required | The name of the Cloud Router in which this NAT will be confi…
  id                                  = ""     # string | optional+computed
  project                             = ""     # string | optional
  region                              = ""     # string | optional | Region where the router and NAT reside.

  # auto_network_tier                   = ""     # string | computed | The network tier to use when automatically reserving NAT IP …
  # drain_nat_ips                       = []     # set(string) | computed | A list of URLs of the IP resources to be drained. These IPs …
  # enable_dynamic_port_allocation      = false  # bool | computed | Enable Dynamic Port Allocation. If minPortsPerVm is set, min…
  # enable_endpoint_independent_mapping = false  # bool | computed | Enable endpoint independent mapping. For more information se…
  # endpoint_types                      = []     # list(string) | computed | Specifies the endpoint Types supported by the NAT Gateway. S…
  # icmp_idle_timeout_sec               = 0      # number | computed | Timeout (in seconds) for ICMP connections. Defaults to 30s i…
  # log_config = [  # list(object)
  #   {
  #     enable = false
  #     filter = ""
  #   }
  # ]
  # max_ports_per_vm                    = 0      # number | computed | Maximum number of ports allocated to a VM from this NAT. Thi…
  # min_ports_per_vm                    = 0      # number | computed | Minimum number of ports allocated to a VM from this NAT. Def…
  # nat_ip_allocate_option              = ""     # string | computed | How external IPs should be allocated for this NAT. Valid val…
  # nat_ips                             = []     # set(string) | computed | Self-links of NAT IPs. Only valid if natIpAllocateOption is …
  # rules = [  # set(object)
  #   {
  #     action = [  # list(object)
  #       {
  #         source_nat_active_ips = []  # set(string)
  #         source_nat_drain_ips = []  # set(string)
  #       }
  #     ]
  #     description = ""
  #     match = ""
  #     rule_number = 0
  #   }
  # ]
  # source_subnetwork_ip_ranges_to_nat  = ""     # string | computed | How NAT should be configured per Subnetwork. If 'ALL_SUBNETW…
  # subnetwork = [  # set(object)
  #   {
  #     name = ""
  #     secondary_ip_range_names = []  # set(string)
  #     source_ip_ranges_to_nat = []  # set(string)
  #   }
  # ]
  # tcp_established_idle_timeout_sec    = 0      # number | computed | Timeout (in seconds) for TCP established connections. Defaul…
  # tcp_time_wait_timeout_sec           = 0      # number | computed | Timeout (in seconds) for TCP connections that are in TIME_WA…
  # tcp_transitory_idle_timeout_sec     = 0      # number | computed | Timeout (in seconds) for TCP transitory connections. Default…
  # udp_idle_timeout_sec                = 0      # number | computed | Timeout (in seconds) for UDP connections. Defaults to 30s if…

}

