# ┌──────────────────────────────────────────────────────────────┐
# │  data: google_cloudfunctions_function                          │
# └──────────────────────────────────────────────────────────────┘
data "google_cloudfunctions_function" "this" {

  name                          = ""     # string | required | A user-defined name of the function. Function names must be …
  id                            = ""     # string | optional+computed
  project                       = ""     # string | optional | Project of the function. If it is not provided, the provider…
  region                        = ""     # string | optional | Region of function. If it is not provided, the provider regi…

  # available_memory_mb           = 0      # number | computed | Memory (in MB), available to the function. Default value is …
  # build_environment_variables   = {}     # map(string) | computed |  A set of key/value environment variable pairs available dur…
  # build_service_account         = ""     # string | computed | The fully-qualified name of the service account to be used f…
  # build_worker_pool             = ""     # string | computed | Name of the Cloud Build Custom Worker Pool that should be us…
  # description                   = ""     # string | computed | Description of the function.
  # docker_registry               = ""     # string | computed | Docker Registry to use for storing the function's Docker ima…
  # docker_repository             = ""     # string | computed | User managed repository created in Artifact Registry optiona…
  # effective_labels              = {}     # map(string) | computed | All of labels (key/value pairs) present on the resource in G…
  # entry_point                   = ""     # string | computed | Name of the function that will be executed when the Google C…
  # environment_variables         = {}     # map(string) | computed | A set of key/value environment variable pairs to assign to t…
  # event_trigger = [  # list(object)
  #   {
  #     event_type = ""
  #     failure_policy = [  # list(object)
  #       {
  #         retry = false
  #       }
  #     ]
  #     resource = ""
  #   }
  # ]
  # https_trigger_security_level  = ""     # string | computed | The security level for the function. Defaults to SECURE_OPTI…
  # https_trigger_url             = ""     # string | computed | URL which triggers function execution. Returned only if trig…
  # ingress_settings              = ""     # string | computed | String value that controls what traffic can reach the functi…
  # kms_key_name                  = ""     # string | computed | Resource name of a KMS crypto key (managed by the user) used…
  # labels                        = {}     # map(string) | computed | A set of key/value label pairs to assign to the function. La…
  # max_instances                 = 0      # number | computed | The limit on the maximum number of function instances that m…
  # min_instances                 = 0      # number | computed | The limit on the minimum number of function instances that m…
  # runtime                       = ""     # string | computed | The runtime in which the function is going to run. Eg. "node…
  # secret_environment_variables = [  # list(object)
  #   {
  #     key = ""
  #     project_id = ""
  #     secret = ""
  #     version = ""
  #   }
  # ]
  # secret_volumes = [  # list(object)
  #   {
  #     mount_path = ""
  #     project_id = ""
  #     secret = ""
  #     versions = [  # list(object)
  #       {
  #         path = ""
  #         version = ""
  #       }
  #     ]
  #   }
  # ]
  # service_account_email         = ""     # string | computed |  If provided, the self-provided service account to run the f…
  # source_archive_bucket         = ""     # string | computed | The GCS bucket containing the zip archive which contains the…
  # source_archive_object         = ""     # string | computed | The source archive object (file) in archive bucket.
  # source_repository = [  # list(object)
  #   {
  #     deployed_url = ""
  #     url = ""
  #   }
  # ]
  # status                        = ""     # string | computed | Describes the current stage of a deployment.
  # terraform_labels              = {}     # map(string) | computed | The combination of labels configured directly on the resourc…
  # timeout                       = 0      # number | computed | Timeout (in seconds) for the function. Default value is 60 s…
  # trigger_http                  = false  # bool | computed | Boolean variable. Any HTTP request (of a supported type) to …
  # version_id                    = ""     # string | computed | The version identifier of the Cloud Function. Each deploymen…
  # vpc_connector                 = ""     # string | computed | The VPC Network Connector that this cloud function can conne…
  # vpc_connector_egress_settings = ""     # string | computed | The egress settings for the connector, controlling what traf…

}

