# ┌──────────────────────────────────────────────────────────────┐
# │  data: google_compute_global_forwarding_rule                   │
# └──────────────────────────────────────────────────────────────┘
data "google_compute_global_forwarding_rule" "this" {

  name                            = ""     # string | required | Name of the resource; provided by the client when the resour…
  id                              = ""     # string | optional+computed
  project                         = ""     # string | optional

  # base_forwarding_rule            = ""     # string | computed | [Output Only] The URL for the corresponding base Forwarding …
  # description                     = ""     # string | computed | An optional description of this resource. Provide this prope…
  # effective_labels                = {}     # map(string) | computed | All of labels (key/value pairs) present on the resource in G…
  # ip_address                      = ""     # string | computed | IP address for which this forwarding rule accepts traffic. W…
  # ip_protocol                     = ""     # string | computed | The IP protocol to which this rule applies.  For protocol fo…
  # ip_version                      = ""     # string | computed | The IP Version that will be used by this global forwarding r…
  # label_fingerprint               = ""     # string | computed | The fingerprint used for optimistic locking of this resource…
  # labels                          = {}     # map(string) | computed | Labels to apply to this forwarding rule.  A list of key->val…
  # load_balancing_scheme           = ""     # string | computed | Specifies the forwarding rule type.  For more information ab…
  # metadata_filters = [  # list(object)
  #   {
  #     filter_labels = [  # list(object)
  #       {
  #         name = ""
  #         value = ""
  #       }
  #     ]
  #     filter_match_criteria = ""
  #   }
  # ]
  # network                         = ""     # string | computed | This field is not used for external load balancing.  For Int…
  # no_automate_dns_zone            = false  # bool | computed | This is used in PSC consumer ForwardingRule to control wheth…
  # port_range                      = ""     # string | computed | The 'portRange' field has the following limitations: * It re…
  # psc_connection_id               = ""     # string | computed | The PSC connection id of the PSC Forwarding Rule.
  # psc_connection_status           = ""     # string | computed | The PSC connection status of the PSC Forwarding Rule. Possib…
  # self_link                       = ""     # string | computed
  # service_directory_registrations = [  # list(object)
  #   {
  #     namespace = ""
  #     service_directory_region = ""
  #   }
  # ]
  # source_ip_ranges                = []     # list(string) | computed | If not empty, this Forwarding Rule will only forward the tra…
  # subnetwork                      = ""     # string | computed | This field identifies the subnetwork that the load balanced …
  # target                          = ""     # string | computed | The URL of the target resource to receive the matched traffi…
  # terraform_labels                = {}     # map(string) | computed | The combination of labels configured directly on the resourc…

}

