# ┌──────────────────────────────────────────────────────────────┐
# │  data: google_compute_forwarding_rule                          │
# └──────────────────────────────────────────────────────────────┘
data "google_compute_forwarding_rule" "this" {

  name                            = ""     # string | required | Name of the resource; provided by the client when the resour…
  id                              = ""     # string | optional+computed
  project                         = ""     # string | optional
  region                          = ""     # string | optional | A reference to the region where the regional forwarding rule…

  # all_ports                       = false  # bool | computed | The 'ports', 'portRange', and 'allPorts' fields are mutually…
  # allow_global_access             = false  # bool | computed | This field is used along with the 'backend_service' field fo…
  # allow_psc_global_access         = false  # bool | computed | This is used in PSC consumer ForwardingRule to control wheth…
  # backend_service                 = ""     # string | computed | Identifies the backend service to which the forwarding rule …
  # base_forwarding_rule            = ""     # string | computed | [Output Only] The URL for the corresponding base Forwarding …
  # creation_timestamp              = ""     # string | computed | Creation timestamp in RFC3339 text format.
  # description                     = ""     # string | computed | An optional description of this resource. Provide this prope…
  # effective_labels                = {}     # map(string) | computed | All of labels (key/value pairs) present on the resource in G…
  # forwarding_rule_id              = 0      # number | computed | The unique identifier number for the resource. This identifi…
  # ip_address                      = ""     # string | computed | IP address for which this forwarding rule accepts traffic. W…
  # ip_protocol                     = ""     # string | computed | The IP protocol to which this rule applies.  For protocol fo…
  # ip_version                      = ""     # string | computed | The IP address version that will be used by this forwarding …
  # is_mirroring_collector          = false  # bool | computed | Indicates whether or not this load balancer can be used as a…
  # label_fingerprint               = ""     # string | computed | The fingerprint used for optimistic locking of this resource…
  # labels                          = {}     # map(string) | computed | Labels to apply to this forwarding rule.  A list of key->val…
  # load_balancing_scheme           = ""     # string | computed | Specifies the forwarding rule type.  For more information ab…
  # network                         = ""     # string | computed | This field is not used for external load balancing.  For Int…
  # network_tier                    = ""     # string | computed | This signifies the networking tier used for configuring this…
  # no_automate_dns_zone            = false  # bool | computed | This is used in PSC consumer ForwardingRule to control wheth…
  # port_range                      = ""     # string | computed | The 'ports', 'portRange', and 'allPorts' fields are mutually…
  # ports                           = []     # set(string) | computed | The 'ports', 'portRange', and 'allPorts' fields are mutually…
  # psc_connection_id               = ""     # string | computed | The PSC connection id of the PSC Forwarding Rule.
  # psc_connection_status           = ""     # string | computed | The PSC connection status of the PSC Forwarding Rule. Possib…
  # recreate_closed_psc             = false  # bool | computed | This is used in PSC consumer ForwardingRule to make terrafor…
  # self_link                       = ""     # string | computed
  # service_directory_registrations = [  # list(object)
  #   {
  #     namespace = ""
  #     service = ""
  #   }
  # ]
  # service_label                   = ""     # string | computed | An optional prefix to the service name for this Forwarding R…
  # service_name                    = ""     # string | computed | The internal fully qualified service name for this Forwardin…
  # source_ip_ranges                = []     # list(string) | computed | If not empty, this Forwarding Rule will only forward the tra…
  # subnetwork                      = ""     # string | computed | This field identifies the subnetwork that the load balanced …
  # target                          = ""     # string | computed | The URL of the target resource to receive the matched traffi…
  # terraform_labels                = {}     # map(string) | computed | The combination of labels configured directly on the resourc…

}

