# ┌──────────────────────────────────────────────────────────────┐
# │  resource: google_storage_bucket                               │
# └──────────────────────────────────────────────────────────────┘
resource "google_storage_bucket" "this" {

  location                    = ""     # string | required | The Google Cloud Storage location
  name                        = ""     # string | required | The name of the bucket.
  default_event_based_hold    = false  # bool | optional | Whether or not to automatically apply an eventBasedHold to n…
  enable_object_retention     = false  # bool | optional | Enables each object in the bucket to have its own retention …
  force_destroy               = false  # bool | optional | When deleting a bucket, this boolean option will delete all …
  id                          = ""     # string | optional+computed
  labels                      = {}     # map(string) | optional | A set of key/value label pairs to assign to the bucket.
  project                     = ""     # string | optional+computed | The ID of the project in which the resource belongs. If it i…
  public_access_prevention    = ""     # string | optional+computed | Prevents public access to a bucket.
  requester_pays              = false  # bool | optional | Enables Requester Pays on a storage bucket.
  rpo                         = ""     # string | optional+computed | Specifies the RPO setting of bucket. If set 'ASYNC_TURBO', T…
  storage_class               = ""     # string | optional | The Storage Class of the new bucket. Supported values includ…
  uniform_bucket_level_access = false  # bool | optional+computed | Enables uniform bucket-level access on a bucket.

  # effective_labels            = {}     # map(string) | computed | All of labels (key/value pairs) present on the resource in G…
  # project_number              = 0      # number | computed | The project number of the project in which the resource belo…
  # self_link                   = ""     # string | computed | The URI of the created resource.
  # terraform_labels            = {}     # map(string) | computed | The combination of labels configured directly on the resourc…
  # url                         = ""     # string | computed | The base URL of the bucket, in the format gs://<bucket-name>…

  autoclass { # list [0..1]
    enabled                = false  # bool | required | While set to true, autoclass automatically transitions objec…
    terminal_storage_class = ""     # string | optional+computed | The storage class that objects in the bucket eventually tran…

  }

  cors { # list
    max_age_seconds = 0      # number | optional | The value, in seconds, to return in the Access-Control-Max-A…
    method          = []     # list(string) | optional | The list of HTTP methods on which to include CORS response h…
    origin          = []     # list(string) | optional | The list of Origins eligible to receive CORS response header…
    response_header = []     # list(string) | optional | The list of HTTP headers other than the simple response head…

  }

  custom_placement_config { # list [0..1]
    data_locations = []     # set(string) | required | The list of individual regions that comprise a dual-region b…

  }

  encryption { # list [0..1]
    default_kms_key_name = ""     # string | required | A Cloud KMS key that will be used to encrypt objects inserte…

  }

  lifecycle_rule { # list [0..100]

    action { # set [1..1]
      type          = ""     # string | required | The type of the action of this Lifecycle Rule. Supported val…
      storage_class = ""     # string | optional | The target Storage Class of objects affected by this Lifecyc…

    }

    condition { # set [1..1]
      age                                     = 0      # number | optional | Minimum age of an object in days to satisfy this condition.
      created_before                          = ""     # string | optional | Creation date of an object in RFC 3339 (e.g. 2017-06-13) to …
      custom_time_before                      = ""     # string | optional | Creation date of an object in RFC 3339 (e.g. 2017-06-13) to …
      days_since_custom_time                  = 0      # number | optional | Number of days elapsed since the user-specified timestamp se…
      days_since_noncurrent_time              = 0      # number | optional | Number of days elapsed since the noncurrent timestamp of an …
      matches_prefix                          = []     # list(string) | optional | One or more matching name prefixes to satisfy this condition…
      matches_storage_class                   = []     # list(string) | optional | Storage Class of objects to satisfy this condition. Supporte…
      matches_suffix                          = []     # list(string) | optional | One or more matching name suffixes to satisfy this condition…
      no_age                                  = false  # bool | optional+DEPRECATED | While set true, age value will be omitted.Required to set tr…
      noncurrent_time_before                  = ""     # string | optional | Creation date of an object in RFC 3339 (e.g. 2017-06-13) to …
      num_newer_versions                      = 0      # number | optional | Relevant only for versioned objects. The number of newer ver…
      send_age_if_zero                        = false  # bool | optional | While set true, age value will be sent in the request even f…
      send_days_since_custom_time_if_zero     = false  # bool | optional | While set true, days_since_custom_time value will be sent in…
      send_days_since_noncurrent_time_if_zero = false  # bool | optional | While set true, days_since_noncurrent_time value will be sen…
      send_num_newer_versions_if_zero         = false  # bool | optional | While set true, num_newer_versions value will be sent in the…
      with_state                              = ""     # string | optional+computed | Match to live and/or archived objects. Unversioned buckets h…

    }

  }

  logging { # list [0..1]
    log_bucket        = ""     # string | required | The bucket that will receive log objects.
    log_object_prefix = ""     # string | optional+computed | The object prefix for log objects. If it's not provided, by …

  }

  retention_policy { # list [0..1]
    retention_period = 0      # number | required | The period of time, in seconds, that objects in the bucket m…
    is_locked        = false  # bool | optional | If set to true, the bucket will be locked and permanently re…

  }

  soft_delete_policy { # list [0..1]
    retention_duration_seconds = 0      # number | optional | The duration in seconds that soft-deleted objects in the buc…

    # effective_time             = ""     # string | computed | Server-determined value that indicates the time from which t…

  }

  timeouts { # single
    create = ""     # string | optional
    read   = ""     # string | optional
    update = ""     # string | optional

  }

  versioning { # list [0..1]
    enabled = false  # bool | required | While set to true, versioning is fully enabled for this buck…

  }

  website { # list [0..1]
    main_page_suffix = ""     # string | optional | Behaves as the bucket's directory index where missing object…
    not_found_page   = ""     # string | optional | The custom object to return when a requested resource is not…

  }

}

