# ┌──────────────────────────────────────────────────────────────┐
# │  resource: google_compute_subnetwork                           │
# └──────────────────────────────────────────────────────────────┘
resource "google_compute_subnetwork" "this" {

  ip_cidr_range                    = ""     # string | required | The range of internal addresses that are owned by this subne…
  name                             = ""     # string | required | The name of the resource, provided by the client when initia…
  network                          = ""     # string | required | The network this subnet belongs to. Only networks that are i…
  description                      = ""     # string | optional | An optional description of this resource. Provide this prope…
  external_ipv6_prefix             = ""     # string | optional+computed | The range of external IPv6 addresses that are owned by this …
  id                               = ""     # string | optional+computed
  ipv6_access_type                 = ""     # string | optional | The access type of IPv6 address this subnet holds. It's immu…
  private_ip_google_access         = false  # bool | optional+computed | When enabled, VMs in this subnetwork without external IP add…
  private_ipv6_google_access       = ""     # string | optional+computed | The private IPv6 google access type for the VMs in this subn…
  project                          = ""     # string | optional+computed
  purpose                          = ""     # string | optional+computed | The purpose of the resource. This field can be either 'PRIVA…
  region                           = ""     # string | optional+computed | The GCP region for this subnetwork.
  role                             = ""     # string | optional | The role of subnetwork. Currently, this field is only used w…
  secondary_ip_range               = []     # list(object({ ip_cidr_range: string, range_name: string })) | optional+computed | An array of configurations for secondary IP ranges for VM in…
  send_secondary_ip_range_if_empty = false  # bool | optional | Controls the removal behavior of secondary_ip_range. When fa…
  stack_type                       = ""     # string | optional+computed | The stack type for this subnet to identify whether the IPv6 …

  # creation_timestamp               = ""     # string | computed | Creation timestamp in RFC3339 text format.
  # fingerprint                      = ""     # string | computed+DEPRECATED | Fingerprint of this resource. This field is used internally …
  # gateway_address                  = ""     # string | computed | The gateway address for default routes to reach destination …
  # internal_ipv6_prefix             = ""     # string | computed | The internal IPv6 address range that is assigned to this sub…
  # ipv6_cidr_range                  = ""     # string | computed | The range of internal IPv6 addresses that are owned by this …
  # self_link                        = ""     # string | computed

  log_config { # list [0..1]
    aggregation_interval = ""     # string | optional | Can only be specified if VPC flow logging for this subnetwor…
    filter_expr          = ""     # string | optional | Export filter used to define which VPC flow logs should be l…
    flow_sampling        = 0      # number | optional | Can only be specified if VPC flow logging for this subnetwor…
    metadata             = ""     # string | optional | Can only be specified if VPC flow logging for this subnetwor…
    metadata_fields      = []     # set(string) | optional | List of metadata fields that should be added to reported log…

  }

  timeouts { # single
    create = ""     # string | optional
    delete = ""     # string | optional
    update = ""     # string | optional

  }

}

