# ┌──────────────────────────────────────────────────────────────┐
# │  resource: google_compute_network                              │
# └──────────────────────────────────────────────────────────────┘
resource "google_compute_network" "this" {

  name                                      = ""     # string | required | Name of the resource. Provided by the client when the resour…
  auto_create_subnetworks                   = false  # bool | optional | When set to 'true', the network is created in "auto subnet m…
  delete_default_routes_on_create           = false  # bool | optional | If set to 'true', default routes ('0.0.0.0/0') will be delet…
  description                               = ""     # string | optional | An optional description of this resource. The resource must …
  enable_ula_internal_ipv6                  = false  # bool | optional | Enable ULA internal ipv6 on this network. Enabling this feat…
  id                                        = ""     # string | optional+computed
  internal_ipv6_range                       = ""     # string | optional+computed | When enabling ula internal ipv6, caller optionally can speci…
  mtu                                       = 0      # number | optional+computed | Maximum Transmission Unit in bytes. The default value is 146…
  network_firewall_policy_enforcement_order = ""     # string | optional | Set the order that Firewall Rules and Firewall Policies are …
  project                                   = ""     # string | optional+computed
  routing_mode                              = ""     # string | optional+computed | The network-wide routing mode to use. If set to 'REGIONAL', …

  # gateway_ipv4                              = ""     # string | computed | The gateway address for default routing out of the network. …
  # numeric_id                                = ""     # string | computed | The unique identifier for the resource. This identifier is d…
  # self_link                                 = ""     # string | computed

  timeouts { # single
    create = ""     # string | optional
    delete = ""     # string | optional
    update = ""     # string | optional

  }

}

