# ┌──────────────────────────────────────────────────────────────┐
# │  resource: google_bigquery_table                               │
# └──────────────────────────────────────────────────────────────┘
resource "google_bigquery_table" "this" {

  dataset_id                      = ""     # string | required | The dataset ID to create the table in. Changing this forces …
  table_id                        = ""     # string | required | A unique ID for the resource. Changing this forces a new res…
  allow_resource_tags_on_deletion = false  # bool | optional+DEPRECATED | **Deprecated** Whether or not to allow table deletion when t…
  clustering                      = []     # list(string) | optional | Specifies column names to use for data clustering. Up to fou…
  deletion_protection             = false  # bool | optional | Whether Terraform will be prevented from destroying the inst…
  description                     = ""     # string | optional | The field description.
  expiration_time                 = 0      # number | optional+computed | The time when this table expires, in milliseconds since the …
  friendly_name                   = ""     # string | optional | A descriptive name for the table.
  id                              = ""     # string | optional+computed
  labels                          = {}     # map(string) | optional | A mapping of labels to assign to the resource.  				**Note**…
  max_staleness                   = ""     # string | optional | The maximum staleness of data that could be returned when th…
  project                         = ""     # string | optional+computed | The ID of the project in which the resource belongs.
  require_partition_filter        = false  # bool | optional | If set to true, queries over this table require a partition …
  resource_tags                   = {}     # map(string) | optional | The tags attached to this table. Tag keys are globally uniqu…
  schema                          = ""     # string | optional+computed | A JSON schema for the table.

  # creation_time                   = 0      # number | computed | The time when this table was created, in milliseconds since …
  # effective_labels                = {}     # map(string) | computed | All of labels (key/value pairs) present on the resource in G…
  # etag                            = ""     # string | computed | A hash of the resource.
  # last_modified_time              = 0      # number | computed | The time when this table was last modified, in milliseconds …
  # location                        = ""     # string | computed | The geographic location where the table resides. This value …
  # num_bytes                       = 0      # number | computed | The geographic location where the table resides. This value …
  # num_long_term_bytes             = 0      # number | computed | The number of bytes in the table that are considered "long-t…
  # num_rows                        = 0      # number | computed | The number of rows of data in this table, excluding any data…
  # self_link                       = ""     # string | computed | The URI of the created resource.
  # terraform_labels                = {}     # map(string) | computed | The combination of labels configured directly on the resourc…
  # type                            = ""     # string | computed | Describes the table type.

  encryption_configuration { # list [0..1]
    kms_key_name    = ""     # string | required | The self link or full name of a key which should be used to …

    # kms_key_version = ""     # string | computed | The self link or full name of the kms key version used to en…

  }

  external_data_configuration { # list [0..1]
    autodetect                = false  # bool | required | Let BigQuery try to autodetect the schema and format of the …
    source_uris               = []     # list(string) | required | A list of the fully-qualified URIs that point to your data i…
    compression               = ""     # string | optional | The compression type of the data source. Valid values are "N…
    connection_id             = ""     # string | optional | The connection specifying the credentials to be used to read…
    file_set_spec_type        = ""     # string | optional | Specifies how source URIs are interpreted for constructing t…
    ignore_unknown_values     = false  # bool | optional | Indicates if BigQuery should allow extra values that are not…
    json_extension            = ""     # string | optional | Load option to be used together with sourceFormat newline-de…
    max_bad_records           = 0      # number | optional | The maximum number of bad records that BigQuery can ignore w…
    metadata_cache_mode       = ""     # string | optional | Metadata Cache Mode for the table. Set this to enable cachin…
    object_metadata           = ""     # string | optional | Object Metadata is used to create Object Tables. Object Tabl…
    reference_file_schema_uri = ""     # string | optional | When creating an external table, the user can provide a refe…
    schema                    = ""     # string | optional+computed | A JSON schema for the external table. Schema is required for…
    source_format             = ""     # string | optional | Please see sourceFormat under ExternalDataConfiguration in B…

    avro_options { # list [0..1]
      use_avro_logical_types = false  # bool | required | If sourceFormat is set to "AVRO", indicates whether to inter…

    }

    bigtable_options { # list [0..1]
      ignore_unspecified_column_families = false  # bool | optional | If field is true, then the column families that are not spec…
      output_column_families_as_json     = false  # bool | optional | If field is true, then each column family will be read as a …
      read_rowkey_as_string              = false  # bool | optional | If field is true, then the rowkey column families will be re…

      column_family { # list
        encoding         = ""     # string | optional | The encoding of the values when the type is not STRING. Acce…
        family_id        = ""     # string | optional | Identifier of the column family.
        only_read_latest = false  # bool | optional | If this is set only the latest version of value are exposed …
        type             = ""     # string | optional | The type to convert the value in cells of this column family…

        column { # list
          encoding          = ""     # string | optional | The encoding of the values when the type is not STRING. Acce…
          field_name        = ""     # string | optional | If the qualifier is not a valid BigQuery field identifier i.…
          only_read_latest  = false  # bool | optional | If this is set, only the latest version of value in this col…
          qualifier_encoded = ""     # string | optional | Qualifier of the column. Columns in the parent column family…
          qualifier_string  = ""     # string | optional | Qualifier string.
          type              = ""     # string | optional | The type to convert the value in cells of this column. The v…

        }

      }

    }

    csv_options { # list [0..1]
      quote                 = ""     # string | required | The value that is used to quote data sections in a CSV file.…
      allow_jagged_rows     = false  # bool | optional | Indicates if BigQuery should accept rows that are missing tr…
      allow_quoted_newlines = false  # bool | optional | Indicates if BigQuery should allow quoted data sections that…
      encoding              = ""     # string | optional | The character encoding of the data. The supported values are…
      field_delimiter       = ""     # string | optional | The separator for fields in a CSV file.
      skip_leading_rows     = 0      # number | optional | The number of rows at the top of a CSV file that BigQuery wi…

    }

    google_sheets_options { # list [0..1]
      range             = ""     # string | optional | Range of a sheet to query from. Only used when non-empty. At…
      skip_leading_rows = 0      # number | optional | The number of rows at the top of the sheet that BigQuery wil…

    }

    hive_partitioning_options { # list [0..1]
      mode                     = ""     # string | optional | When set, what mode of hive partitioning to use when reading…
      require_partition_filter = false  # bool | optional | If set to true, queries over this table require a partition …
      source_uri_prefix        = ""     # string | optional | When hive partition detection is requested, a common for all…

    }

    json_options { # list [0..1]
      encoding = ""     # string | optional | The character encoding of the data. The supported values are…

    }

    parquet_options { # list [0..1]
      enable_list_inference = false  # bool | optional | Indicates whether to use schema inference specifically for P…
      enum_as_string        = false  # bool | optional | Indicates whether to infer Parquet ENUM logical type as STRI…

    }

  }

  materialized_view { # list [0..1]
    query                            = ""     # string | required | A query whose result is persisted.
    allow_non_incremental_definition = false  # bool | optional | Allow non incremental materialized view definition. The defa…
    enable_refresh                   = false  # bool | optional | Specifies if BigQuery should automatically refresh materiali…
    refresh_interval_ms              = 0      # number | optional | Specifies maximum frequency at which this materialized view …

  }

  range_partitioning { # list [0..1]
    field = ""     # string | required | The field used to determine how to create a range-based part…

    range { # list [1..1]
      end      = 0      # number | required | End of the range partitioning, exclusive.
      interval = 0      # number | required | The width of each range within the partition.
      start    = 0      # number | required | Start of the range partitioning, inclusive.

    }

  }

  table_constraints { # list [0..1]

    foreign_keys { # list
      name = ""     # string | optional | Set only if the foreign key constraint is named.

      column_references { # list [1..1]
        referenced_column  = ""     # string | required | The column in the primary key that are referenced by the ref…
        referencing_column = ""     # string | required | The column that composes the foreign key.

      }

      referenced_table { # list [1..1]
        dataset_id = ""     # string | required | The ID of the dataset containing this table.
        project_id = ""     # string | required | The ID of the project containing this table.
        table_id   = ""     # string | required | The ID of the table. The ID must contain only letters (a-z, …

      }

    }

    primary_key { # list [0..1]
      columns = []     # list(string) | required | The columns that are composed of the primary key constraint.

    }

  }

  table_replication_info { # list [0..1]
    source_dataset_id       = ""     # string | required | The ID of the source dataset.
    source_project_id       = ""     # string | required | The ID of the source project.
    source_table_id         = ""     # string | required | The ID of the source materialized view.
    replication_interval_ms = 0      # number | optional | The interval at which the source materialized view is polled…

  }

  time_partitioning { # list [0..1]
    type                     = ""     # string | required | The supported types are DAY, HOUR, MONTH, and YEAR, which wi…
    expiration_ms            = 0      # number | optional+computed | Number of milliseconds for which to keep the storage for a p…
    field                    = ""     # string | optional | The field used to determine how to create a time-based parti…
    require_partition_filter = false  # bool | optional+DEPRECATED | If set to true, queries over this table require a partition …

  }

  view { # list [0..1]
    query          = ""     # string | required | A query that BigQuery executes when the view is referenced.
    use_legacy_sql = false  # bool | optional | Specifies whether to use BigQuery's legacy SQL for this view…

  }

}

