# ┌──────────────────────────────────────────────────────────────┐
# │  resource: google_compute_backend_service                      │
# └──────────────────────────────────────────────────────────────┘
resource "google_compute_backend_service" "this" {

  name                            = ""     # string | required | Name of the resource. Provided by the client when the resour…
  affinity_cookie_ttl_sec         = 0      # number | optional | Lifetime of cookies in seconds if session_affinity is GENERA…
  compression_mode                = ""     # string | optional | Compress text responses using Brotli or gzip compression, ba…
  connection_draining_timeout_sec = 0      # number | optional | Time for which instance will be drained (not accept new conn…
  custom_request_headers          = []     # set(string) | optional | Headers that the HTTP/S load balancer should add to proxied …
  custom_response_headers         = []     # set(string) | optional | Headers that the HTTP/S load balancer should add to proxied …
  description                     = ""     # string | optional | An optional description of this resource.
  edge_security_policy            = ""     # string | optional | The resource URL for the edge security policy associated wit…
  enable_cdn                      = false  # bool | optional | If true, enable Cloud CDN for this BackendService.
  health_checks                   = []     # set(string) | optional | The set of URLs to the HttpHealthCheck or HttpsHealthCheck r…
  id                              = ""     # string | optional+computed
  load_balancing_scheme           = ""     # string | optional | Indicates whether the backend service will be used with inte…
  locality_lb_policy              = ""     # string | optional | The load balancing algorithm used within the scope of the lo…
  port_name                       = ""     # string | optional+computed | Name of backend port. The same name should appear in the ins…
  project                         = ""     # string | optional+computed
  protocol                        = ""     # string | optional+computed | The protocol this BackendService uses to communicate with ba…
  security_policy                 = ""     # string | optional | The security policy associated with this backend service.
  service_lb_policy               = ""     # string | optional | URL to networkservices.ServiceLbPolicy resource. Can only be…
  session_affinity                = ""     # string | optional+computed | Type of session affinity to use. The default is NONE. Sessio…
  timeout_sec                     = 0      # number | optional+computed | The backend service timeout has a different meaning dependin…

  # creation_timestamp              = ""     # string | computed | Creation timestamp in RFC3339 text format.
  # fingerprint                     = ""     # string | computed | Fingerprint of this resource. A hash of the contents stored …
  # generated_id                    = 0      # number | computed | The unique identifier for the resource. This identifier is d…
  # self_link                       = ""     # string | computed

  backend { # set
    group                        = ""     # string | required | The fully-qualified URL of an Instance Group or Network Endp…
    balancing_mode               = ""     # string | optional | Specifies the balancing mode for this backend.  For global H…
    capacity_scaler              = 0      # number | optional | A multiplier applied to the group's maximum servicing capaci…
    description                  = ""     # string | optional | An optional description of this resource. Provide this prope…
    max_connections              = 0      # number | optional+computed | The max number of simultaneous connections for the group. Ca…
    max_connections_per_endpoint = 0      # number | optional+computed | The max number of simultaneous connections that a single bac…
    max_connections_per_instance = 0      # number | optional+computed | The max number of simultaneous connections that a single bac…
    max_rate                     = 0      # number | optional+computed | The max requests per second (RPS) of the group.  Can be used…
    max_rate_per_endpoint        = 0      # number | optional+computed | The max requests per second (RPS) that a single backend netw…
    max_rate_per_instance        = 0      # number | optional+computed | The max requests per second (RPS) that a single backend inst…
    max_utilization              = 0      # number | optional+computed | Used when balancingMode is UTILIZATION. This ratio defines t…

  }

  cdn_policy { # list [0..1]
    cache_mode                   = ""     # string | optional+computed | Specifies the cache setting for all responses from this back…
    client_ttl                   = 0      # number | optional+computed | Specifies the maximum allowed TTL for cached content served …
    default_ttl                  = 0      # number | optional+computed | Specifies the default TTL for cached content served by this …
    max_ttl                      = 0      # number | optional+computed | Specifies the maximum allowed TTL for cached content served …
    negative_caching             = false  # bool | optional+computed | Negative caching allows per-status code TTLs to be set, in o…
    serve_while_stale            = 0      # number | optional+computed | Serve existing content from the cache (if available) when re…
    signed_url_cache_max_age_sec = 0      # number | optional | Maximum number of seconds the response to a signed URL reque…

    bypass_cache_on_request_headers { # list
      header_name = ""     # string | required | The header field name to match on when bypassing cache. Valu…

    }

    cache_key_policy { # list [0..1]
      include_host           = false  # bool | optional | If true requests to different hosts will be cached separatel…
      include_http_headers   = []     # list(string) | optional | Allows HTTP request headers (by name) to be used in the cach…
      include_named_cookies  = []     # list(string) | optional | Names of cookies to include in cache keys.
      include_protocol       = false  # bool | optional | If true, http and https requests will be cached separately.
      include_query_string   = false  # bool | optional | If true, include query string parameters in the cache key ac…
      query_string_blacklist = []     # set(string) | optional | Names of query string parameters to exclude in cache keys.  …
      query_string_whitelist = []     # set(string) | optional | Names of query string parameters to include in cache keys.  …

    }

    negative_caching_policy { # list
      code = 0      # number | optional | The HTTP status code to define a TTL against. Only HTTP stat…
      ttl  = 0      # number | optional | The TTL (in seconds) for which to cache responses with the c…

    }

  }

  circuit_breakers { # list [0..1]
    max_connections             = 0      # number | optional | The maximum number of connections to the backend cluster. De…
    max_pending_requests        = 0      # number | optional | The maximum number of pending requests to the backend cluste…
    max_requests                = 0      # number | optional | The maximum number of parallel requests to the backend clust…
    max_requests_per_connection = 0      # number | optional | Maximum requests for a single backend connection. This param…
    max_retries                 = 0      # number | optional | The maximum number of parallel retries to the backend cluste…

  }

  consistent_hash { # list [0..1]
    http_header_name  = ""     # string | optional | The hash based on the value of the specified header field. T…
    minimum_ring_size = 0      # number | optional | The minimum number of virtual nodes to use for the hash ring…

    http_cookie { # list [0..1]
      name = ""     # string | optional | Name of the cookie.
      path = ""     # string | optional | Path to set for the cookie.

      ttl { # list [0..1]
        seconds = 0      # number | required | Span of time at a resolution of a second. Must be from 0 to …
        nanos   = 0      # number | optional | Span of time that's a fraction of a second at nanosecond res…

      }

    }

  }

  iap { # list [0..1]
    oauth2_client_id            = ""     # string | required | OAuth2 Client ID for IAP
    oauth2_client_secret        = ""     # string | required+sensitive | OAuth2 Client Secret for IAP

    # oauth2_client_secret_sha256 = ""     # string | computed+sensitive | OAuth2 Client Secret SHA-256 for IAP

  }

  locality_lb_policies { # list

    custom_policy { # list [0..1]
      name = ""     # string | required | Identifies the custom policy.  The value should match the ty…
      data = ""     # string | optional | An optional, arbitrary JSON object with configuration data, …

    }

    policy { # list [0..1]
      name = ""     # string | required | The name of a locality load balancer policy to be used. The …

    }

  }

  log_config { # list [0..1]
    enable      = false  # bool | optional | Whether to enable logging for the load balancer traffic serv…
    sample_rate = 0      # number | optional | This field can only be specified if logging is enabled for t…

  }

  outlier_detection { # list [0..1]
    consecutive_errors                    = 0      # number | optional | Number of errors before a host is ejected from the connectio…
    consecutive_gateway_failure           = 0      # number | optional | The number of consecutive gateway failures (502, 503, 504 st…
    enforcing_consecutive_errors          = 0      # number | optional | The percentage chance that a host will be actually ejected w…
    enforcing_consecutive_gateway_failure = 0      # number | optional | The percentage chance that a host will be actually ejected w…
    enforcing_success_rate                = 0      # number | optional | The percentage chance that a host will be actually ejected w…
    max_ejection_percent                  = 0      # number | optional | Maximum percentage of hosts in the load balancing pool for t…
    success_rate_minimum_hosts            = 0      # number | optional | The number of hosts in a cluster that must have enough reque…
    success_rate_request_volume           = 0      # number | optional | The minimum number of total requests that must be collected …
    success_rate_stdev_factor             = 0      # number | optional | This factor is used to determine the ejection threshold for …

    base_ejection_time { # list [0..1]
      seconds = 0      # number | required | Span of time at a resolution of a second. Must be from 0 to …
      nanos   = 0      # number | optional | Span of time that's a fraction of a second at nanosecond res…

    }

    interval { # list [0..1]
      seconds = 0      # number | required | Span of time at a resolution of a second. Must be from 0 to …
      nanos   = 0      # number | optional | Span of time that's a fraction of a second at nanosecond res…

    }

  }

  security_settings { # list [0..1]
    client_tls_policy = ""     # string | optional | ClientTlsPolicy is a resource that specifies how a client sh…
    subject_alt_names = []     # list(string) | optional | A list of alternate names to verify the subject identity in …

    aws_v4_authentication { # list [0..1]
      access_key         = ""     # string | optional+sensitive | The access key used for s3 bucket authentication. Required f…
      access_key_id      = ""     # string | optional | The identifier of an access key used for s3 bucket authentic…
      access_key_version = ""     # string | optional | The optional version identifier for the access key. You can …
      origin_region      = ""     # string | optional | The name of the cloud region of your origin. This is a free-…

    }

  }

  timeouts { # single
    create = ""     # string | optional
    delete = ""     # string | optional
    update = ""     # string | optional

  }

}

