# ┌──────────────────────────────────────────────────────────────┐
# │  resource: google_compute_address                              │
# └──────────────────────────────────────────────────────────────┘
resource "google_compute_address" "this" {

  name               = ""     # string | required | Name of the resource. The name must be 1-63 characters long,…
  address            = ""     # string | optional+computed | The static external IP address represented by this resource.…
  address_type       = ""     # string | optional | The type of address to reserve. Note: if you set this argume…
  description        = ""     # string | optional | An optional description of this resource.
  id                 = ""     # string | optional+computed
  ip_version         = ""     # string | optional | The IP Version that will be used by this address. The defaul…
  ipv6_endpoint_type = ""     # string | optional | The endpoint type of this address, which should be VM or NET…
  labels             = {}     # map(string) | optional | Labels to apply to this address.  A list of key->value pairs…
  network            = ""     # string | optional | The URL of the network in which to reserve the address. This…
  network_tier       = ""     # string | optional+computed | The networking tier used for configuring this address. If th…
  prefix_length      = 0      # number | optional+computed | The prefix length if the resource represents an IP range.
  project            = ""     # string | optional+computed
  purpose            = ""     # string | optional+computed | The purpose of this resource, which can be one of the follow…
  region             = ""     # string | optional+computed | The Region in which the created address should reside. If it…
  subnetwork         = ""     # string | optional+computed | The URL of the subnetwork in which to reserve the address. I…

  # creation_timestamp = ""     # string | computed | Creation timestamp in RFC3339 text format.
  # effective_labels   = {}     # map(string) | computed | All of labels (key/value pairs) present on the resource in G…
  # label_fingerprint  = ""     # string | computed | The fingerprint used for optimistic locking of this resource…
  # self_link          = ""     # string | computed
  # terraform_labels   = {}     # map(string) | computed | The combination of labels configured directly on the resourc…
  # users              = []     # list(string) | computed | The URLs of the resources that are using this address.

  timeouts { # single
    create = ""     # string | optional
    delete = ""     # string | optional
    update = ""     # string | optional

  }

}

