# ┌──────────────────────────────────────────────────────────────┐
# │  resource: google_pubsub_subscription                          │
# └──────────────────────────────────────────────────────────────┘
resource "google_pubsub_subscription" "this" {

  name                         = ""     # string | required | Name of the subscription.
  topic                        = ""     # string | required | A reference to a Topic resource, of the form projects/{proje…
  ack_deadline_seconds         = 0      # number | optional+computed | This value is the maximum time after a subscriber receives a…
  enable_exactly_once_delivery = false  # bool | optional | If 'true', Pub/Sub provides the following guarantees for the…
  enable_message_ordering      = false  # bool | optional | If 'true', messages published with the same orderingKey in P…
  filter                       = ""     # string | optional | The subscription only delivers the messages that match the f…
  id                           = ""     # string | optional+computed
  labels                       = {}     # map(string) | optional | A set of key/value label pairs to assign to this Subscriptio…
  message_retention_duration   = ""     # string | optional | How long to retain unacknowledged messages in the subscripti…
  project                      = ""     # string | optional+computed
  retain_acked_messages        = false  # bool | optional | Indicates whether to retain acknowledged messages. If 'true'…

  # effective_labels             = {}     # map(string) | computed | All of labels (key/value pairs) present on the resource in G…
  # terraform_labels             = {}     # map(string) | computed | The combination of labels configured directly on the resourc…

  bigquery_config { # list [0..1]
    table                 = ""     # string | required | The name of the table to which to write data, of the form {p…
    drop_unknown_fields   = false  # bool | optional | When true and use_topic_schema or use_table_schema is true, …
    service_account_email = ""     # string | optional | The service account to use to write to BigQuery. If not spec…
    use_table_schema      = false  # bool | optional | When true, use the BigQuery table's schema as the columns to…
    use_topic_schema      = false  # bool | optional | When true, use the topic's schema as the columns to write to…
    write_metadata        = false  # bool | optional | When true, write the subscription name, messageId, publishTi…

  }

  cloud_storage_config { # list [0..1]
    bucket                   = ""     # string | required | User-provided name for the Cloud Storage bucket. The bucket …
    filename_datetime_format = ""     # string | optional | User-provided format string specifying how to represent date…
    filename_prefix          = ""     # string | optional | User-provided prefix for Cloud Storage filename.
    filename_suffix          = ""     # string | optional | User-provided suffix for Cloud Storage filename. Must not en…
    max_bytes                = 0      # number | optional | The maximum bytes that can be written to a Cloud Storage fil…
    max_duration             = ""     # string | optional | The maximum duration that can elapse before a new Cloud Stor…
    service_account_email    = ""     # string | optional | The service account to use to write to Cloud Storage. If not…

    # state                    = ""     # string | computed | An output-only field that indicates whether or not the subsc…

    avro_config { # list [0..1]
      write_metadata = false  # bool | optional | When true, write the subscription name, messageId, publishTi…

    }

  }

  dead_letter_policy { # list [0..1]
    dead_letter_topic     = ""     # string | optional | The name of the topic to which dead letter messages should b…
    max_delivery_attempts = 0      # number | optional | The maximum number of delivery attempts for any message. The…

  }

  expiration_policy { # list [0..1]
    ttl = ""     # string | required | Specifies the "time-to-live" duration for an associated reso…

  }

  push_config { # list [0..1]
    push_endpoint = ""     # string | required | A URL locating the endpoint to which messages should be push…
    attributes    = {}     # map(string) | optional | Endpoint configuration attributes.  Every endpoint has a set…

    no_wrapper { # list [0..1]
      write_metadata = false  # bool | required | When true, writes the Pub/Sub message metadata to 'x-goog-pu…

    }

    oidc_token { # list [0..1]
      service_account_email = ""     # string | required | Service account email to be used for generating the OIDC tok…
      audience              = ""     # string | optional | Audience to be used when generating OIDC token. The audience…

    }

  }

  retry_policy { # list [0..1]
    maximum_backoff = ""     # string | optional+computed | The maximum delay between consecutive deliveries of a given …
    minimum_backoff = ""     # string | optional+computed | The minimum delay between consecutive deliveries of a given …

  }

  timeouts { # single
    create = ""     # string | optional
    delete = ""     # string | optional
    update = ""     # string | optional

  }

}

