# ┌──────────────────────────────────────────────────────────────┐
# │  resource: google_compute_firewall                             │
# └──────────────────────────────────────────────────────────────┘
resource "google_compute_firewall" "this" {

  name                    = ""     # string | required | Name of the resource. Provided by the client when the resour…
  network                 = ""     # string | required | The name or self_link of the network to attach this firewall…
  description             = ""     # string | optional | An optional description of this resource. Provide this prope…
  destination_ranges      = []     # set(string) | optional+computed | If destination ranges are specified, the firewall will apply…
  direction               = ""     # string | optional+computed | Direction of traffic to which this firewall applies; default…
  disabled                = false  # bool | optional | Denotes whether the firewall rule is disabled, i.e not appli…
  enable_logging          = false  # bool | optional+computed+DEPRECATED | This field denotes whether to enable logging for a particula…
  id                      = ""     # string | optional+computed
  priority                = 0      # number | optional | Priority for this rule. This is an integer between 0 and 655…
  project                 = ""     # string | optional+computed
  source_ranges           = []     # set(string) | optional | If source ranges are specified, the firewall will apply only…
  source_service_accounts = []     # set(string) | optional | If source service accounts are specified, the firewall will …
  source_tags             = []     # set(string) | optional | If source tags are specified, the firewall will apply only t…
  target_service_accounts = []     # set(string) | optional | A list of service accounts indicating sets of instances loca…
  target_tags             = []     # set(string) | optional | A list of instance tags indicating sets of instances located…

  # creation_timestamp      = ""     # string | computed | Creation timestamp in RFC3339 text format.
  # self_link               = ""     # string | computed

  allow { # set
    protocol = ""     # string | required | The IP protocol to which this rule applies. The protocol typ…
    ports    = []     # list(string) | optional | An optional list of ports to which this rule applies. This f…

  }

  deny { # set
    protocol = ""     # string | required | The IP protocol to which this rule applies. The protocol typ…
    ports    = []     # list(string) | optional | An optional list of ports to which this rule applies. This f…

  }

  log_config { # list [0..1]
    metadata = ""     # string | required | This field denotes whether to include or exclude metadata fo…

  }

  timeouts { # single
    create = ""     # string | optional
    delete = ""     # string | optional
    update = ""     # string | optional

  }

}

